### ISSUE TITLE
Got error when run workflow  

### ISSUE THREAD

**Issue by parvaj** [keephq/keep#1024]
**Describe the bug**
requirement is get the data from postgres database and alert the message/notify to teams. 
here is my yaml workflow file.  
Attached the error message.
**To Reproduce**
id: query-postgres-and-notify-teams
description: Query postgres and notify teams
triggers:
- filters: null
  type: alert
owners: []
services: []
steps:
- name: postgres-step
  provider:
    config: '{{ providers.jazzpost }}'
    type: postgres
    with:
      query: SELECT * FROM public.ticketinstance LIMIT 1
actions:
- name: trigger-teams
  provider:
    config: '{{ providers.jazzware }}'
    type: teams
    with:
      message: Got alert from postgres {{ steps.postgres-step.results.name }}

**Expected behavior**

**Screenshots**
Error during workflow execution

(builtins.TypeError) Object of type datetime is not JSON serializable

[SQL: UPDATE workflowexecution SET results=? WHERE workflowexecution.id = ?]

[parameters: [{'results': {'trigger-teams': [], 'postgres-step': [[('996d081c-6c2d-4439-ba69-0e923fc5354c', 

<img width="604" alt="error_keeps_sql" src="https://github.com/keephq/keep/assets/8781370/85ae568c-1fbf-4e67-89d2-862f7a5974a5">

Please help me to fix this issue. thanks.

**Comment by talboren** [comment]
Hey @parvaj,

thanks for the issue! I’ll look in to it right away and update ASAP

**Comment by talboren** [comment]
@parvaj how are you deploying Keep? Can you provide `keep-backend` logs?

**Comment by talboren** [comment]
@parvaj is this still relevant?
