### ISSUE TITLE
Condition name should be aligned

### ISSUE THREAD

**Issue by talboren** [keephq/keep#105]
This should be aligned and fixed ASAP.

<img width="830" alt="image" src="https://user-images.githubusercontent.com/68807791/229885454-6b642c78-f7d9-46d3-8bb5-0354f7ac1c7e.png">

cc: @shahargl

**Comment by abhaykv04** [comment]
@talboren Could you kindly elaborate further on the issue? I would like to take this up. Thanks.

**Comment by shahargl** [comment]
we added "condition name" (aka "id") to distinguish between multiple conditions with the same type (in other words - if you want two threshold conditions, you'll need to distinguish them somehow, hence condition name). I've "patched" this with this line but we should revisit all other code/alerts to make it more robust. if you want - I can hop on a quick call and we will review it together @abhaykv04

**Comment by talboren** [comment]
Hey @abhaykv04 👋🏻
Awesome, that could be really amazing! 

What I meant here is that we allows conditions to be “nameless” (no unique identifier) in the YAML spec which in turn yields a strange behavior where we either take the name if it exists or use the condition type — in case we have the same condition more than once, this will probably cause a buggy result. 

IMHO we should enforce id/name for EVERY condition so that we will always use that attribute and never the condition type. (This will also allow direct access to condition results with mustache)

Hope my explanation makes sense, if it doesn’t, I would love to hop on a quick call and further explain. Let me know. 

Thank you!

**Comment by abhaykv04** [comment]
@shahargl / @talboren, Thanks for the responses, guys! It's Friday night here in India. Let me set up the project locally tonight and tinker with it and see how far I can understand the code. We can have a call then @ Sunday 10 PM IST, if that works? Let me know. Thanks.

**Comment by talboren** [comment]
@abhaykv04 perfect. Would you mind jointing our Slack so we can discuss meeting details and I can further help you with the code? https://keephq.dev/slack

**Comment by abhaykv04** [comment]
@talboren I am there!
