### ISSUE TITLE
AppDynamics provider

### ISSUE THREAD

**Issue by shahargl** [keephq/keep#1089]
### Describe the provider you want to add
[AppDynamics](https://www.appdynamics.com/) (free account creation [here](https://accounts.appdynamics.com/trial))

### Describe your use case
Connect AppDynamics account and receive alerts from it.
We should support scopes and auto webhook installation (see other providers for examples, e.g., Datadog, Grafana, SignalFx, etc.)

**Comment by shahargl** [comment]
assigned @35C4n0r

**Comment by ezhil56x** [comment]
@35C4n0r Are you still working on this?

**Comment by 35C4n0r** [comment]
@ezhil56x Yup, the work is almost done
