### ISSUE TITLE
Centreon Provider

### ISSUE THREAD

**Issue by mabed-fr** [keephq/keep#1113]
**Describe the provider you want to add**
Centreon(nagios)

**Describe your use case**
Send alert from each probe in alert

**Are you already using Keep?**
Yes (Grafana, Alertmanager)

**Additional context**
* https://www.centreon.com/fr/editions-centreon/centreon-open-source/

**Comment by shahargl** [comment]
Assigned @35C4n0r

**Comment by 35C4n0r** [comment]
@mabed-fr  Checked both v1 and v2 can't find any alert-related endpoints, though they have notification https://docs-api.centreon.com/api/centreon-web/23.10/#tag/Notification
https://docs.centreon.com/docs/alerts-notifications/notif-concept/
https://docs.centreon.com/docs/category/managing-alerts/

**Comment by mabed-fr** [comment]
> > @mabed-frVérifié à la fois v1 et v2 ne peuvent pas trouver de points de terminaison liés à l'alerte, bien qu'ils aient une notification [https://docs-api.centreon.com/api/centreon-web/23.10/#tag/Notificationhttps](https://docs-api.centreon.com/api/centreon-web/23.10/#tag/Notification)[://docs.centreon.com/docs/alerts-notifications/notif-concept/](https://docs.centreon.com/docs/alerts-notifications/notif-concept/)https://docs.centreon.com/docs/category/managing-alerts/
> 
> @mabed-frpouvez-vous confirmer si nous voulons envoyer des notifications ou des alertes ?

Sorry yes this is an alert in centreon

**Comment by shahargl** [comment]
@35C4n0r how is it going?

**Comment by 35C4n0r** [comment]
I will be dropping this issue.

**Comment by talboren** [comment]
> Hi @shahargl can I pick this up if it isn't already being worked on?

You can! 🥳

**Comment by ezhil56x** [comment]
@mabed-fr 
In case you have missed my comment

> @mabed-fr Can you add more on what is required for this provider integration?

**Comment by joshuanazareth97** [comment]
/attempt #1113

@shahargl @talboren Hi, so just confirming on the plan of implementation, will extend the BaseProvider class, and implement the methods for authentication, config and scope validation, and alert retrieval and formatting. There are 2 fields that require mapping from the Centreon enum to corresponding alert fields in keep:

1. Status:
```
        status_mapping = {
            "UP": AlertStatus.RESOLVED,
            "OK": AlertStatus.RESOLVED,
            "DOWN": AlertStatus.FIRING,
            "WARNING": AlertStatus.FIRING,
            "CRITICAL": AlertStatus.FIRING,
            "UNKNOWN": AlertStatus.FIRING,
            "UNREACHABLE": AlertStatus.FIRING,
            "PENDING": AlertStatus.PENDING
        }
```

2. Severity:
```
severity_mapping = {
    1: AlertSeverity.CRITICAL,  # DOWN or CRITICAL -> CRITICAL
    2: AlertSeverity.WARNING,   # WARNING -> WARNING
    3: AlertSeverity.INFO,      # UNKNOWN or UNREACHABLE -> INFO (As there's no direct match)
    4: AlertSeverity.LOW,       # PENDING -> LOW (Considering PENDING as less severe, could also be INFO I guess)
    5: AlertSeverity.LOW        # UP or OK -> LOW
}
```

Do these mappings and the general approach sound okay? Will go ahead with the implementation then.

**Comment by talboren** [comment]
> /attempt #1113
> 
> @shahargl @talboren Hi, so just confirming on the plan of implementation, will extend the BaseProvider class, and implement the methods for authentication, config and scope validation, and alert retrieval and formatting. There are 2 fields that require mapping from the Centreon enum to corresponding alert fields in keep:
> 
> 1. Status:
> 
> ```
>         status_mapping = {
>             "UP": AlertStatus.RESOLVED,
>             "OK": AlertStatus.RESOLVED,
>             "DOWN": AlertStatus.FIRING,
>             "WARNING": AlertStatus.FIRING,
>             "CRITICAL": AlertStatus.FIRING,
>             "UNKNOWN": AlertStatus.FIRING,
>             "UNREACHABLE": AlertStatus.FIRING,
>             "PENDING": AlertStatus.PENDING
>         }
> ```
> 
> 2. Severity:
> 
> ```
> severity_mapping = {
>     1: AlertSeverity.CRITICAL,  # DOWN or CRITICAL -> CRITICAL
>     2: AlertSeverity.WARNING,   # WARNING -> WARNING
>     3: AlertSeverity.INFO,      # UNKNOWN or UNREACHABLE -> INFO (As there's no direct match)
>     4: AlertSeverity.LOW,       # PENDING -> LOW (Considering PENDING as less severe, could also be INFO I guess)
>     5: AlertSeverity.LOW        # UP or OK -> LOW
> }
> ```
> 
> Do these mappings and the general approach sound okay? Will go ahead with the implementation then.
> 
> Options

Yes, makes sense! Derive your inspiration from other implemented providers -- good examples are Datadog, Grafana, etc.

**Comment by ezhil56x** [comment]
@joshuanazareth97 
Are you still on this or can I take up?

**Comment by joshuanazareth97** [comment]
@ezhil56x will be raising the PR today

**Comment by ezhil56x** [comment]
<details>
  <summary>Keep Documentation for Centreon Provider</summary>

  [Video Link](https://github.com/keephq/keep/assets/103899034/e3e545ad-c76e-46c6-80be-e2651e03bb45)

</details>
