### ISSUE TITLE
ntfy.sh Provider

### ISSUE THREAD

**Issue by mabed-fr** [keephq/keep#1122]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
https://docs.ntfy.sh/publish/

**Additional context**
Integration of ntfy.sh project for send alert

**Comment by ezhil56x** [comment]
Can I get assigned?

**Comment by shahargl** [comment]
Yes I’ll assign you, what’s your estimation on this one?

**Comment by ezhil56x** [comment]
> Yes I’ll assign you, what’s your estimation on this one?

1 or 2 days
