### ISSUE TITLE
pagertree provider 

### ISSUE THREAD

**Issue by mabed-fr** [keephq/keep#1127]
https://pagertree.com/

**Comment by mehulmathur16** [comment]
Hi @shahargl, can I be assigned ?

**Comment by 35C4n0r** [comment]
/attempt
Kindly assign

**Comment by shahargl** [comment]
assigned @35C4n0r 

@mehulmathur16 - can you comment on other providers?

**Comment by mehulmathur16** [comment]
sure @shahargl

**Comment by 35C4n0r** [comment]
@shahargl some issue on their side =, while signing Up.

![image](https://github.com/keephq/keep/assets/70096901/e36cc0ff-4ebc-4f4f-8421-53d726a9a2ad)
