### ISSUE TITLE
statuscake provider 

### ISSUE THREAD

**Issue by mabed-fr** [keephq/keep#1129]
Hello,

can you add statuscake provider?

Is a tool for check website and certificate.

https://www.statuscake.com/statuscake-long-page/?utm_source=google&utm_medium=cpc&utm_term=statuscake_e&utm_campaign_id=12192546667&utm_campaign=csj_g_fr_en_lg_sea_bra_e&gad_source=1&gbraid=0AAAAADsol-URpLtBcOhZagTEqvJRqrlwn&gclid=CjwKCAjwz42xBhB9EiwA48pT78SVA_VKjwP6UENJwfwqNh2i1AR6YM9tlWETfiFJEGe7EYFdIWtTlBoCS5UQAvD_BwE

**Comment by ezhil56x** [comment]
Can I get this assigned?
/attempt #1129

**Comment by shahargl** [comment]
Assigned

**Comment by ezhil56x** [comment]
@mabed-fr 
Statuscake seems to support heartbeat, pagespeed, ssl, uptime through API.
Can you add more on what all are expected in detail?
Thanks!

**Comment by mabed-fr** [comment]
The goal is for pagertree to alert in keep (ssl, uptime, page speed, etc.)

**Comment by ezhil56x** [comment]
Is that the same that is expected for statuscake as well?

**Comment by 35C4n0r** [comment]
I think he meant statuscake, can you confirm @mabed-fr

**Comment by mabed-fr** [comment]
sorry i edit my message
