### ISSUE TITLE
site 24x7 provider

### ISSUE THREAD

**Issue by mabed-fr** [keephq/keep#1130]
Hello

can you add site24x7.com ?

**Comment by mehulmathur16** [comment]
@shahargl can I be assigned ?

**Comment by shahargl** [comment]
assigned @mehulmathur16

**Comment by mehulmathur16** [comment]
@shahargl I am unassigning myself from the issue. I found the api documentation for Site24x7 to be less user-friendly than expected.

**Comment by 35C4n0r** [comment]
@shahargl what features do we need to get all the alerts here.

**Comment by shahargl** [comment]
@mabed-fr can you elaborate please?

**Comment by mabed-fr** [comment]
I want keep to configure a Third Party App (Third-Party Integrations) as best as possible. If this is not possible, a doc would be good.

**Comment by sc231997** [comment]
@mabed-fr as per the 24x7 we need to add a webhook for this integration with keep. The implementation of should look like similar to https://docs.keephq.dev/providers/documentation/gcpmonitoring-provider 
Can I get this assigned?
/attempt #1130

**Comment by shahargl** [comment]
@sc231997 - you got it

**Comment by sc231997** [comment]
Hi @shahargl , I am currently occupied in my day job. I will try to work on this next week. 
In the meantime, if anyone else want to pick this you can give them this ticket.

**Comment by shahargl** [comment]
assigned @35C4n0r
