### ISSUE TITLE
uptime-kuma provider 

### ISSUE THREAD

**Issue by mabed-fr** [keephq/keep#1131]
Hello,

can you add uptime kuma in provider list ?

**Comment by webbdays** [comment]
I will try it.

**Comment by shahargl** [comment]
Assigned @webbdays

**Comment by mabed-fr** [comment]
Hello

The best would be to make a PR directly on the repo: https://github.com/louislam/uptime-kuma

There is a good amount of integration on their side and this is apparently simplified. And what's more, there is no official API yet.

**Comment by shahargl** [comment]
yo @webbdays how is it going?

**Comment by webbdays** [comment]
Sorry, others can attempt.

**Comment by ezhil56x** [comment]
/attempt #1131
Can I get this assigned?
