### ISSUE TITLE
"Load a Workflow" button doesn't respond

### ISSUE THREAD

**Issue by KanvaBhatia** [keephq/keep#1173]
**Describe the bug**
When you have no workflows, `WorkflowsEmptyState` from `app/workflows/noworkflows.tsx` is rendered, which attempts to click on an element with id `workflowFile`. This item is not on the screen yet and hence cannot be clicked, making "Load a Workflow" button unresponsive. 

**To Reproduce**
1. Go to https://platform.keephq.dev/workflows
2. Click on "Load a Workflow" --(visible only if you have no workflows)
3. No response

**Expected behavior**
Expected to either open the Modal which opens when Upload Workflows button is clicked or open a file picker.

**Screenshots**
![image](https://github.com/keephq/keep/assets/56185464/4d0c3b68-3488-48fe-a43d-0de47abb822d)
^^ Clicking on Load a Workflow has no effect

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome
 - Version: Version 124.0.6367.201 (Official Build) (arm64)

**Additional context**
***Possible fix***
Change behaviour to open the Upload Workflows modal when clicked on Load a Workflow.
possible fix- 

https://github.com/keephq/keep/assets/56185464/4602d584-63c3-452c-acc6-22810ade85f0

^^ 

I am willing to work on this issue and open a PR.

**Comment by talboren** [comment]
@KanvaBhatia I've applied a quick fix for this issue that was caused when workflow didn't have a name.
cc: @pehlicd, I think it's related to recent changes of workflow name you added, could that be?

**Comment by KanvaBhatia** [comment]
@talboren I was telling about this button, which is still unresponsive.
https://platform.keephq.dev/workflows
![image](https://github.com/keephq/keep/assets/56185464/fcb34feb-1dda-405c-a408-68108910c942)

I have a potential fix - 

https://github.com/keephq/keep/assets/56185464/278eec5d-766e-4bc0-8a1a-f9565bcfc178
