### ISSUE TITLE
Provider Parameters in workflow builder are missing for providers with both step and action

### ISSUE THREAD

**Issue by KanvaBhatia** [keephq/keep#1179]
**Describe the bug**
For providers which provide both `_query` and `_notify` definitions in backend, the Provider Parameters in workflow builder show the same step parameters for both provider-step and provider-action. 

Here, the `stepParams` gets set to `properties.stepParams` regardless of the type of the item. 
https://github.com/keephq/keep/blob/575ce23ecf4c84a6ff331f85dc094732b55f3344/keep-ui/app/workflows/builder/editors.tsx#L62C1-L64C21

If the type is a step, then it should be `properties.stepParams`, otherwise `properties.actionParams`.

**To Reproduce**
1. Go to https://platform.keephq.dev/workflows
2. Click on "Create a Workflow"
3. Add any provider from toolbox which has both `step` and `action`, for example - `ilert-step` and `ilert-action`.
4. You'll see that the `Provider Parameters` in the Editor are same, whereas the `_notify` definition is - 
`
def _notify(
        self,
        summary: str = "",
        status: IlertIncidentStatus = IlertIncidentStatus.INVESTIGATING,
        message: str = "",
        affectedServices: str | list = "[]",
        id: str = "0",
        **kwargs: dict,
    ):
`
So, the`ilert-action` should have the parameters as `summary`, `status`, `message`, etc..

**Expected behavior**
The provider-action items should have the `properties.actionParams` and provider-step should have `properties.stepParams`.

**Screenshots**

https://github.com/keephq/keep/assets/56185464/0006fa24-cfdb-4244-832b-bb7e71bc8242

^^ Same parameters for step and action of ilert provider, not correct.

**Additional context**
Possible fix - 
If the type is a step, then it should be `properties.stepParams`, otherwise `properties.actionParams`.

After fix it should look like - 

https://github.com/keephq/keep/assets/56185464/937585f8-63f2-4b45-8c24-05ab2b53bb43

If the fix looks fine, I'll create a pull request.

**Comment by KanvaBhatia** [comment]
Sure @talboren. Will fix both and create a PR.

**Comment by KanvaBhatia** [comment]
@talboren I see few providers directly implementing `notify` instead of `_notify`, should that be changed? for example the `PostgresProvider`.

**Comment by talboren** [comment]
> @talboren I see few providers directly implementing `notify` instead of `_notify`, should that be changed? for example the `PostgresProvider`.

Yes @KanvaBhatia, thank you!
