### ISSUE TITLE
prometheus "invalid scopes" on connect

### ISSUE THREAD

**Issue by shahargl** [keephq/keep#1193]
When a connection fails to prometheus, the error message shows:
![CleanShot 2024-05-24 at 11 43 09@2x](https://github.com/keephq/keep/assets/12069200/f7136e24-aa1a-4950-ab74-850d0774c113)

**Comment by ezhil56x** [comment]
@shahargl 
![image](https://github.com/keephq/keep/assets/103899034/14c14567-83d3-4cec-8f5a-704ad726beb7)

Seems to work correctly. I think you have added an extra `/t` in the last of the url which is not required as alert api is on `/api/v1/alerts`

**Comment by shahargl** [comment]
you are probably correct - the question we we can show a better error than "scopes are undefined" (yes we can! :) )

**Comment by shahargl** [comment]
assigned @ezhil56x

**Comment by ezhil56x** [comment]
@shahargl Better errors seems to be already implemented
![image](https://github.com/keephq/keep/assets/103899034/0eaae3d6-3514-44df-afb2-cadca3183063)

**Comment by KanvaBhatia** [comment]
> you are probably correct - the question we we can show a better error than "scopes are undefined" (yes we can! :) )

Hey @shahargl, correct me if I'm wrong but, I think i fixed this in https://github.com/keephq/keep/pull/1172

**Comment by ezhil56x** [comment]
> > you are probably correct - the question we we can show a better error than "scopes are undefined" (yes we can! :) )
> 
> Hey @shahargl, correct me if I'm wrong but, I think i fixed this in #1172

Yes, your fix works here
