### ISSUE TITLE
feat: support oauth2-proxy authentication

### ISSUE THREAD

**Issue by shahargl** [keephq/keep#1203]
full context - https://getkeep.slack.com/archives/C04PT44MATS/p1717007052868319

in short - add a new authentication mode that let the user delegate the authentication from Keep to oauth2-proxy.

Technically, with `AUTH_TYPE=oauth2-proxy` the following should happen:
1. Keep will trust `HTTP_X_FORWARDED_EMAIL` and `HTTP_X_FORWARDED_ROLE` headers and will skip any authentication methods
2. Keep will allow auto-provisioning 

References:
- https://jysk.tech/unleashing-netbox-in-kubernetes-with-fluxcd-a-journey-of-automation-and-high-uptime-cc02cdc3f84b
- https://github.com/healthchecks/healthchecks/discussions/752#discussioncomment-9587451

**Comment by lukasmrtvy** [comment]
@shahargl hi, any update on this? Thanks

**Comment by shahargl** [comment]
hey @lukasmrtvy - I'm ready to work on it.
A few quick questions:
1. Is this still relevant to you?
2. Wdym with "auto-provisioning"? From my understanding - all user management will be done outside of Keep - Keep will just use `HTTP_X_FORWARDED_EMAIL` as the username and `HTTP_X_FORWARDED_ROLE` as the role, so I'm not sure what provisioning is even needed?

**Comment by lukasmrtvy** [comment]
hi @shahargl 

yes to both. I will reach You on Slack :)

**Comment by shahargl** [comment]
@lukasmrtvy once you give a last "ok" this will be merged - https://github.com/keephq/keep/pull/2014
