### ISSUE TITLE
Support for accepting alerts from OpenObserve

### ISSUE THREAD

**Issue by prabhatsharma** [keephq/keep#1209]
**Is your feature request related to a problem? Please describe.**
Support for accepting alerts from OpenObserve - https://github.com/openobserve/openobserve

**Describe the solution you'd like**
Build a provider for OpenObserve.
The provider should support auto webhook installation.

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by 35C4n0r** [comment]
@talboren kindly assign

**Comment by talboren** [comment]
> @talboren kindly assign

@35C4n0r you got it! :) let me know if I can help with anything
