### ISSUE TITLE
Optimize UI for smaller screens

### ISSUE THREAD

**Issue by Matvey-Kuk** [keephq/keep#1220]
**Please don't assign to yourself if you are not going through the interview process:**

> We are hiring at Keep, and one of the stages in our hiring process is a test task. To make working on a test task more fun, we ask candidates to take any issue from our public GitHub. We also assign a small bounty to thank candidates for their time. Issues with the bounty are popular, so **this particular issue is "held" for candidates going through the interview** process. Btw, check our open positions if you want to work at Keep! https://www.ycombinator.com/companies/keep

Currently, Keep's UI is optimized for larger screens only. This issue is a series of minor frontend issues I'm facing as a MacBook (13-inch display) user. Take it if you would like to demonstrate UI skills. I'm pretty sure I didn't catch all of the issues ;)

1) Margins in the list of Providers (and even overflow for some items):
<img width="1337" alt="Screenshot 2024-06-09 at 15 47 22" src="https://github.com/keephq/keep/assets/3284841/ac46161d-12b6-469f-b0b2-062fafded60b">

2) Overflow:
<img width="1337" alt="Screenshot 2024-06-09 at 15 48 19" src="https://github.com/keephq/keep/assets/3284841/6a427f42-486d-4e24-b909-ee06de4144b9">

3) Margins on the bottom of the Provider configuration page:
<img width="1337" alt="Screenshot 2024-06-09 at 15 48 48" src="https://github.com/keephq/keep/assets/3284841/aa7c55e3-c4e9-4286-afd4-e515af45a93a">

4) Give me more space!
<img width="1271" alt="Screenshot 2024-06-09 at 15 53 32" src="https://github.com/keephq/keep/assets/3284841/c3d1bbb8-1693-4881-985a-2d8406232f33">

5) Too vertical ;) 
<img width="1271" alt="Screenshot 2024-06-09 at 15 54 28" src="https://github.com/keephq/keep/assets/3284841/1a22a330-d3a1-46c0-ae43-556afd0b85a4">

**Comment by srikary12** [comment]
I'll be working on this if not @p1kalys

**Comment by asr2003** [comment]
@Matvey-Kuk Can it be assigned to me?

**Comment by srikary12** [comment]
@Matvey-Kuk Can you assign it to me?

**Comment by Matvey-Kuk** [comment]
Hi @srikary12, I can't match your account with anyone interviewing for Keep's engineering position. Please reach out to me in DM!

**Comment by srikary12** [comment]
The required [changes](https://github.com/keephq/keep/pull/1224) are made in the PR

**Comment by Matvey-Kuk** [comment]
Hi @hrshkshri, I can't match your account with anyone interviewing for Keep's engineering position. Please reach out to me in DM!

**Comment by hrshkshri** [comment]
> Hi @hrshkshri, I can't match your account with anyone interviewing for Keep's engineering position. Please reach out to me in DM!

Hello there...
I don't understand, am I missing something...(maybe a little bit of elaboration could help-- thanks)
I'm afraid I don't have any contact to reach you out.

**Comment by shahargl** [comment]
@Matvey-Kuk @talboren - workflows page looks bad on small screen:
![CleanShot 2024-06-24 at 09 05 20@2x](https://github.com/keephq/keep/assets/12069200/2449d53e-ffc7-41f0-85eb-faa352d95751)

**Comment by Kiryous** [comment]
Hey, @Matvey-Kuk, I'm coming back with a small PR to fix the issues described—#1491. Please have a look when you have time.
