### ISSUE TITLE
[➕ Feature] API endpoint to see how many alerts a provider has sent

### ISSUE THREAD

**Issue by talboren** [keephq/keep#1249]
This endpoint could be then used to monitor the "health" of some provider or just expose some BI of trends.

**Describe your use case**
An API endpoint that exposes the number of alerts a specific provider has received (in a specific time time period or ever)

**Are you already using Keep?**
**Yes**/No

**Additional context**
-

**Comment by Matvey-Kuk** [comment]
@talboren maybe worth making it a prometheus-formatted metrics exporter endpoint?

**Comment by kumarvikramshahi** [comment]
/attempt #1249  
would like to give it a shot, if no one is attempting this one. @Matvey-Kuk

**Comment by talboren** [comment]
@kumarvikramshahi youre good to go

**Comment by 35C4n0r** [comment]
I don't see any progress on this, I'll raise a PR for this
/attempt #1249

**Comment by 35C4n0r** [comment]
![image](https://github.com/user-attachments/assets/5b6d6cb3-eac0-451e-926f-5e9910a3d630)

**Comment by talboren** [comment]
@35C4n0r looks great!
