### ISSUE TITLE
[🔌 Provider] Grafana Incident

### ISSUE THREAD

**Issue by Matvey-Kuk** [keephq/keep#1258]
**Describe the provider you want to add**
Provider for https://grafana.com/products/cloud/incident/

**Describe your use case**
I would love this provider to query all incidents from Grafana Incident, including metadata (participants, timeline, some other info?) as an event into Keep.

**Are you already using Keep?**
Yes

**Additional context**
This provider needs to fetch all incidents from the 3rd party retrospectively.

**Comment by ezhil56x** [comment]
Should this be integrated with the current grafana provider or should this be separate?

**Comment by Matvey-Kuk** [comment]
@ezhil56x I believe it should be a separate one because Grafana Incident has a separate API
