### ISSUE TITLE
[🔌 Provider] Incident.IO

### ISSUE THREAD

**Issue by Matvey-Kuk** [keephq/keep#1259]
**Describe the provider you want to add**
Provider for https://incident.io/

**Describe your use case**
I would love this provider to query all incidents, including metadata (participants, timeline, some other info?) as an event into Keep.

**Are you already using Keep?**
Yes/No

**Additional context**
This provider needs to fetch all incidents from the 3rd party retrospectively.

**Comment by 35C4n0r** [comment]
@Matvey-Kuk ig there is a typo in the heading Privider => Provider

**Comment by 35C4n0r** [comment]
![image](https://github.com/keephq/keep/assets/70096901/cd99d574-5601-44d4-ab53-8be138d6bafa)
@Matvey-Kuk, I can still Implement this since the code is straightforward, or if possible kindly provide me an API Key

**Comment by ezhil56x** [comment]
@35C4n0r 
Are you still working on this?

**Comment by 35C4n0r** [comment]
@ezhil56x yup.

**Comment by 35C4n0r** [comment]
@ezhil56x, I've built the provider, but testing the provider wasn't done as we were waiting for the API key.
I'm extremely busy rn due to placements, if you would test it out, we can split the bounty. Lemme know if that works for you :)

**Comment by Matvey-Kuk** [comment]
@35C4n0r I sent the API key to your DM ;)

**Comment by 35C4n0r** [comment]
Yup, I'm still busy and will be for a while. Please go ahead with the testing. I'll split the bounty in this PR. I'll DM you later today.
