### ISSUE TITLE
[🔌 Provider] Make PagerDuty provider to fetch incidents retrospectively

### ISSUE THREAD

**Issue by Matvey-Kuk** [keephq/keep#1262]
**Is your feature request related to a problem? Please describe.**
PagerDuty provider in fetching new Incidents that happened only after it was connected: 
<img width="1189" alt="Screenshot 2024-06-20 at 18 40 39" src="https://github.com/keephq/keep/assets/3284841/712f12ad-2d46-4b9b-9164-8c33bd70d5a5">

Fetched payload is also pretty limited:
```
{
  "environment": "unknown",
  "service": "Default Service",
  "apiKeyRef": null,
  "message": null,
  "labels": {},
  "fingerprint": "ea614d4639cd2ca3e5857adc6189b26b1a73b45858605ed64045615e4d8f6429",
  "dismissUntil": null,
  "dismissed": false,
  "startedAt": "2024-06-20 15:39:30.550000",
  "isNoisy": false,
  "priority": null,
  "escalation_policy": {
    "id": "PPB6DK3",
    "self": "https://api.pagerduty.com/escalation_policies/PPB6DK3",
    "type": "escalation_policy_reference",
    "summary": "Default",
    "html_url": "https://asdlksa.pagerduty.com/escalation_policies/PPB6DK3"
  },
  "number": 2,
  "type": "incident",
  "resolve_reason": null,
  "alert_hash": "15d56631ceea5f7559ba83041f3768227dbc20dde60dffa1eecb9226fe38dd68",
  "urgency": "high",
  "teams": [],
  "conference_bridge": null,
  "incident_key": "4c7286b70d4946ddaccb2b9cd8de824b"
}
```

**Describe the solution you'd like**
1. We would love to see all past incidents also being fetched.
2. Important metadata, such as impacted services, notes, etc, should also be fetched to the event metadata.

It will help to query and analyze PD incidents inside Keep.

**Comment by mobley-trent** [comment]
Hi @onyedikachi-david I appreciate your interest in this issue but I'm already working on a PR for it

**Comment by onyedikachi-david** [comment]
> Hi @onyedikachi-david I appreciate your interest in this issue but I'm already working on a PR for it

@mobley-trent I am sorry, since you were not assigned and it was not specified on the algora comment that the contributor needs to be assigned first, I thought it was like others that anyone can compete for. Should I delete my pull request @Matvey-Kuk

**Comment by Matvey-Kuk** [comment]
@onyedikachi-david I'm sorry, I didn't notice @mobley-trent before I reviewed your PR. We'll continue with @mobley-trent's PR if it will be merged in a few days :)

**Comment by onyedikachi-david** [comment]
Alright.
