### ISSUE TITLE
[🔌 Update Provider] iLert

### ISSUE THREAD

**Issue by Matvey-Kuk** [keephq/keep#1263]
There is an existing "iLert" provider.

This provider needs to fetch all incidents from the 3rd party retrospectively & as much metadata as possible.

**Comment by Matvey-Kuk** [comment]
@ezhil56x my bad! Updated.

**Comment by talboren** [comment]
@ezhil56x seems like https://github.com/keephq/keep/pull/1273 is throwing exceptions and not working properly. Can you please check the issue there?

**Comment by talboren** [comment]
> @ezhil56x seems like #1273 is throwing exceptions and not working properly. Can you please check the issue there?

"Failed to get alerts" with status code 404.
