### ISSUE TITLE
Deploy Keep on Windows/Linux

### ISSUE THREAD

**Issue by shahargl** [keephq/keep#130]
Deploy Keep as a Windows service or Linux Daemon

**Comment by jdoctolero1** [comment]
In the future, will there be an option to install Keep from an RPM for Linux and an MSI file for Windows? This would be for folks in a legacy environment that aren't using Render or Docker. Keep would be a Windows Service or a Linux Daemon in this scenario as well. In Windows you would see Keep running under the Windows Services. In Linux you would see be able to control the keepd daemon wtih systemctl or whatever Linux service control system the machine uses.

On another note, any plans to publish a Docker container to something like Docker Hub that has Keep ready to go? You could start by just publishing a container with the DB Test alarm ready to go.

**Comment by talboren** [comment]
> In the future, will there be an option to install Keep from an RPM for Linux and an MSI file for Windows? This would be for folks in a legacy environment that aren't using Render or Docker. Keep would be a Windows Service or a Linux Daemon in this scenario as well. In Windows you would see Keep running under the Windows Services. In Linux you would see be able to control the keepd daemon wtih systemctl or whatever Linux service control system the machine uses.
> 
> On another note, any plans to publish a Docker container to something like Docker Hub that has Keep ready to go? You could start by just publishing a container with the DB Test alarm ready to go.

> In the future, will there be an option to install Keep from an RPM for Linux and an MSI file for Windows?

Will definitely consider that!

> On another note, any plans to publish a Docker container to something like Docker Hub that has Keep ready to go? You could start by just publishing a container with the DB Test alarm ready to go.

We already have that :) https://hub.docker.com/r/keephq/cli
This is the documentation: https://www.keephq.wiki/deployment#docker
@jdoctolero1 I'd love to help out with anything and get you up and running with Keep whenever you want (join our Slack and let's chat!)
