### ISSUE TITLE
Non deterministic behavior of the parser function  

### ISSUE THREAD

**Issue by GabrielSamberg** [keephq/keep#135]
**Describe the bug**
The different calls  for the parse function are dependent.
reference :
https://github.com/keephq/keep/blob/3e6b8df54c27c791ad647f3975737fcdfc8e244c/tests/test_parser.py#L47

**To Reproduce**
This test reproduces the bug:
https://github.com/keephq/keep/blob/3e6b8df54c27c791ad647f3975737fcdfc8e244c/tests/test_parser.py#L47

**Expected behavior**
If the above tests are passing that would indicate that the calls for parser are no longer dependent and hence the bug is fixed.
  
**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by blaklafter** [comment]
There were some changes to the Parser.parse() in #225, which might make this fail for a different reason.

**Comment by talboren** [comment]
@blaklafter @GabrielSamberg not sure I completely understand the use case here. Would love a clarification so I can address the issue.
