### ISSUE TITLE
[🐛 Bug]: MinimizeMenuButton does not disappear on small screens

### ISSUE THREAD

**Issue by ArtArtem** [keephq/keep#1357]
On large screens, there is a MinimizeMenuButton to hide and display the menu, and for small screens, a Popover.Button.

However, both buttons are displayed on small screens by mistake, and due to the change of grid to flex MinimizeMenuButton takes up too much space.

Video with the problem:

https://github.com/keephq/keep/assets/45171843/d2694015-e315-4bff-aa74-b9580a7b6b97

**Comment by ArtArtem** [comment]
@Matvey-Kuk 

Hi, I tried to solve the problem, I think it got much better. I think the user can use the site on mobile devices or just open a thin page in a computer browser, so this problem should be relevant

https://github.com/keephq/keep/assets/45171843/ec3657f5-9e3e-44c3-b3f3-1d4e8faa5066

**Comment by Matvey-Kuk** [comment]
@ArtArtem sounds great! Do you have a PR for that?

**Comment by ArtArtem** [comment]
@Matvey-Kuk check it out https://github.com/keephq/keep/pull/1364
