### ISSUE TITLE
[🔨 Enhancement]: Introducing new design to Workflows page

### ISSUE THREAD

**Issue by talboren** [keephq/keep#1363]
@fivenp contributed this design for Workflows page:

1. Empty state, no alerts
![no alerts](https://github.com/keephq/keep/assets/68807791/8d8f9633-64a6-4369-8fe1-1f3b96b70097)

2. Empty state, with alerts
![with alerts](https://github.com/keephq/keep/assets/68807791/cf48e77e-7806-42a6-8353-e610d9a1b937)

We have many workflow examples in https://github.com/keephq/keep/tree/main/examples/workflows which we can use as "mocked workflows"

* The navbar already changed, no need to implement the one in the designs here.
* Need to implement the mechanism that gets the mocked workflows from https://github.com/keephq/keep/tree/main/examples/workflows and displays them when alerts exist
* If for some reason, the frontend is unable to fetch the workflow examples, some indicative warning message should be displayed instead of the mocked workflows. (e.g., could not fetch workflows)

TBD

Figma files are available for the grabber ;)

**Comment by hunxjunedo** [comment]
/attempt #1363 
Hey @talboren ! Can I get assigned ?

**Comment by talboren** [comment]
@ydv129 do you need access to the figma file? would love to have you [in our Slack community](https://slack.keephq.dev)

**Comment by rajeshj11** [comment]
@talboren is this still open? I would like to give it a try.

**Comment by talboren** [comment]
> @talboren is this still open? I would like to give it a try.

Looks like @ydv129 is already attempting. Need to ask him

**Comment by talboren** [comment]
@rajeshj11 i think this is up for you to grab

**Comment by rajeshj11** [comment]
> @rajeshj11 i think this is up for you to grab

Can i get access to the figma

**Comment by ketanPC5** [comment]
@talboren Is this still open?

**Comment by ketapi05** [comment]
@talboren Is this still open?

**Comment by ezhil56x** [comment]
@Bhavyajain21 Are you still on this?

**Comment by Bhavyajain21** [comment]
@ezhil56x looks like someone else is still on this.
I'm waiting if it's not completed and I can jump in.

**Comment by talboren** [comment]
@rajeshj11 is on it.

**Comment by rajeshj11** [comment]
> @Bhavyajain21 Are you still on this?

@ezhil56x  I am working on this.
