### ISSUE TITLE
[🐛 Bug]: Broken Accept all and Reject all Cookie at HomePage

### ISSUE THREAD

**Issue by TenzDelek** [keephq/keep#1371]
**Describe the bug**
at home page, when a user enters, the accept all and reject all toast is not responding. whether click both, there is no trigger action.
**To Reproduce**
1. got to https://www.keephq.dev/
2. at bottom left there will be a toast saying accept all , reject all
3. click on it

**Expected behavior**
it should  close when we click the toast
**Screenshots**
<img width="1261" alt="image" src="https://github.com/user-attachments/assets/64999e9c-f13a-4ede-83d0-b15805b9ad2a">

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Brave

**Comment by shahargl** [comment]
Hey @TenzDelek, closing this as the website is not part of this repository. Thanks for opening and we will fix it asap!
