### ISSUE TITLE
[🔨 Enhancement]: Refactoring workflow builder to use React Flow

### ISSUE THREAD

**Issue by talboren** [keephq/keep#1451]
https://reactflow.dev/

Overall, the workflow builder works as expected today, but the code is spaghetti, it's hard to add new features and validations are quite bad.
We want to keep the same state with Workflow Builder but adopting React Flow to enhance overall experience, cleaner code and making future features easier.

Since this task **does not have Figma**, imagination and use of current Keep theme is required :)

1. Enhance users Workflow Builder experience by look and feel
2. Add more validations
3. Clean code and make it easy to enhance/change things in the future

TBD

**Comment by Bhavyajain21** [comment]
@talboren I would like to work on this along with @rajeshj11. Please assign!

**Comment by pradip-allwyn** [comment]
pls take a look at this https://n8n.io/workflows/ for some inspiration.

**Comment by rajeshj11** [comment]
@Bhavyajain21 Please check the pending things.
To Do:
- [ ] handle switch and for-each deletion.

- [ ] reconstruct the new flow into the definition(using nodes and edges)

- [ ] Minor Ui improvements.

let me know which changes you are picking.
