### ISSUE TITLE
[🔨 Enhancement]: Alert groups should generate incident instead of new alert

### ISSUE THREAD

**Issue by talboren** [keephq/keep#1487]

**Comment by Savokr** [comment]
Wanted to take this one, @talboren can you please add a little more context and explanation for some terms like "correlation group"? It's my first issue, so still looking in the process of grasping all the concepts.

**Comment by talboren** [comment]
> Wanted to take this one, @talboren can you please add a little more context and explanation for some terms like "correlation group"? It's my first issue, so still looking in the process of grasping all the concepts.

Absolutely @Savokr, and also happy to help you further in our [Slack community](https://slack.keephq.dev)

We have the alert groups view
![CleanShot 2024-08-04 at 12 07 46@2x](https://github.com/user-attachments/assets/6deb53eb-4653-48cf-b807-41aaae6a45d2)
that lets you configure "alert groups", meaning that you can combine number of alerts together (e.g., if X alerts goes in Keep in a 30 seconds timespan and they share the same `alert.host`, group them together).
Today, when alert group is "matched", it creates a new alert. Instead of creating a new alert, it should create a new incident and correlate all the matched alerts to that incident.

**Comment by Savokr** [comment]
@talboren Thanks for clarification! I'll start on this item then.

**Comment by talboren** [comment]
Seems like I mistakenly duplicated the issue here: https://github.com/keephq/keep/issues/1487

@Savokr can you grab it from there?

**Comment by Savokr** [comment]
> Seems like I mistakenly duplicated the issue here: #1501
> 
> @Savokr can you grab it from there?

@talboren Sure, I can take it but it seems that @rogueloop is working on it.
