### ISSUE TITLE
[🔨 Enhancement]: Ilert provider to support official Keep integration

### ISSUE THREAD

**Issue by talboren** [keephq/keep#1496]
Ilert now supports Keep officially from their platform 🥳 
![CleanShot 2024-08-06 at 15 25 11@2x](https://github.com/user-attachments/assets/9f23b162-793f-453e-9d2e-b4209ec72d65)

Raw details:
The URL is POST [https://api.ilert.com/api/v1/events/keep/{ALERT-SOURCE-API-KEY}](https://api.ilert.com/api/v1/events/keep/%7BALERT-SOURCE-API-KEY%7D)
The request body is equal to our standard event API https://api.ilert.com/api-docs/#tag/events/post/events (you should not send the apiKey body field).
Additional custom fields should be piped or added in the customDetails: {} field.

DoD for this issue:
1. Adjust `_notify` to support the ilert custom Keep integration
2. Adjust documentation to explain how to add Keep to ilert.

Any further instructions/help is always available in our [Slack](https://slack.keephq.dev)

**Comment by 35C4n0r** [comment]
@Matvey-Kuk I don't see any progress on this, I would love to pick this up.

**Comment by Matvey-Kuk** [comment]
@Mubashirshariq do you have any progress with this one? :)

**Comment by Mubashirshariq** [comment]
I wasn't able to get the ilert api key, yesterday I tried it with my college email id and i will raise the PR soon
