### ISSUE TITLE
[🔨 Enhancement]: Alert Groups should create incidents

### ISSUE THREAD

**Issue by talboren** [keephq/keep#1501]
As a user, when configuring Alert Groups rules, I want an **incident** created when the rule matches, **instead of the new alert** that is created as of today.

This work is mostly in the `RulesEngine` (rulesengine.py) at `run_rules` function. Happy to answer any question in our [Slack](https://slack.keephq.dev)

Extra requirements:

* Created incidents are not predictions, so `Incident.is_predicted` should be `False`
* Add flag "Create Incidents as Candidates" to rule config. If it's `True` set `Incident.is_confirmed` to `False`

Optional:
* Send an update to the UI using a [pusher](https://github.com/keephq/keep/blob/7060d721650511bfd39de7ecd010c414417713f6/keep/api/core/dependencies.py#L420) after creating new incidents

**Comment by talboren** [comment]
@rogueloop are you actively working on this?

**Comment by rogueloop** [comment]
Yes

**Comment by Savokr** [comment]
Hi @rogueloop, are you still working on the issue?

**Comment by rogueloop** [comment]
@Savokr 👍 you can take this up. No big progress from my side.

**Comment by Matvey-Kuk** [comment]
Hey @Savokr do you have any updates on this? :)

**Comment by Savokr** [comment]
Hey @Matvey-Kuk, planned to push some things today.

**Comment by Savokr** [comment]
@Matvey-Kuk Sorry for the delay, was busy with other stuff. Created the draft pull request and added a few questions regarding very specific things, would love if someone can take a look at it and answer my comments.
