### ISSUE TITLE
[🐛 Bug]: If query param `labels` has unknown label, providers page will be empty 

### ISSUE THREAD

**Issue by andreizanik** [keephq/keep#1512]
**Describe the bug**
1) If query param `labels` has unknown label, providers page will be empty 
https://platform.keephq.dev/providers?labels=unknown

2) There are no "queue" in the provider filter, but you have kafra provider 

**To Reproduce**
1. Go to 'https://platform.keephq.dev/providers?labels=unknown'
2. Provider page is empty
3. Select filter by labels
4. Providers are displayed by selected labels
5. Clear filter
6. Provider page is empty again 

**Expected behavior**
Ignore unknown labels from query parameters and do not search for them

Add queue to label filter

**Screenshots**
<img width="1726" alt="image" src="https://github.com/user-attachments/assets/4ab47f3e-1207-467e-95f4-0c7d547c68f6">

**Additional context**

**Comment by 35C4n0r** [comment]
My bad, @Matvey-Kuk is someone already working on this?
