### ISSUE TITLE
[📃 Docs]: Getting started documentation for developers looks to be not accurate enough.

### ISSUE THREAD

**Issue by achivkun** [keephq/keep#1524]
**Describe the bug**
It looks like [getting started instruction](https://github.com/keephq/keep/blob/main/docs/development/getting-started.mdx) is either obsolete, or not detailed enough, or there are some problems with docker/compose files. Command `docker-compose -f docker-compose.dev.yml up`, mentioned in this file, can't start without additional manipulations.

*Please assign this tiket to me if it is confirmed to be a bug in docker/compose files.

**To Reproduce**
1. Check [getting started instruction](https://github.com/keephq/keep/blob/main/docs/development/getting-started.mdx) and try to run `docker-compose -f docker-compose.dev.yml up` listed there.
2. See error:
```
ERROR: compose.cli.main.exit_with_metrics: The Compose file is invalid because:
Service keep-backend-dev has neither an image nor a build context specified. At least one must be provided.
```
3. Fix this error by adding `context: .` to `build` section of  ` keep-frontend-dev` and `keep-backend-dev` in `docker-compose.dev.yml`  Or alternativly we can run containers with `docker compose` instead of `docker-compose` (without dash)
4. Try `docker-compose -f docker-compose.dev.yml up` again and see error:
```
 => ERROR [8/8] RUN ln -s /usr/local/lib/node_modules/next/dist/bin/next /usr/local/bin/next                                                                                                                               0.7s
------
 > [8/8] RUN ln -s /usr/local/lib/node_modules/next/dist/bin/next /usr/local/bin/next:
0.408 ln: /usr/local/bin/next: File exists
```
5. Remove line `RUN ln -s /usr/local/lib/node_modules/next/dist/bin/next /usr/local/bin/next` from `Dockerfile.dev.ui` and try again
6. Now everything seems to work

**Expected behavior**
It is expected that commands from  [getting started instruction](https://github.com/keephq/keep/blob/main/docs/development/getting-started.mdx) will work without any problems for as many environments as possible, even if some will have not most fresh versions of some packages.

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04.4 LTS (Jammy Jellyfish)
 - docker-compose: 1.29.2

**Comment by soylent-grin** [comment]
For 4 possible workaround is waiting for approval https://github.com/keephq/keep/pull/1523/files#diff-edc66b35c9059e6f4fd75aa0f568ec86249f535bd0715516621005e8fd9e1949R22

**Comment by achivkun** [comment]
> For 4 possible workaround is waiting for approval https://github.com/keephq/keep/pull/1523/files#diff-edc66b35c9059e6f4fd75aa0f568ec86249f535bd0715516621005e8fd9e1949R22

@soylent-grin yes, agree.
