### ISSUE TITLE
Documentation (Development): wrong set of items in navigation pane.

### ISSUE THREAD

**Issue by achivkun** [keephq/keep#1525]
**Describe the bug**
Currently section `Development` of documentation contains 3 items:
- getting-started,
- authentication,  <<< this one is wrong
- external-url

But if we will click on `authentication`, we will be redirected to the `overview/introduction`.
It is because there is no such file exists in `docs/development`. It looks like `authentication` should be removed from the list (it is related to `Deployment` section and already present there).

Also probably 2 following items should be added to this section (at least such `.mdx` files are exists):
- installation
- overview

But before doing that, filenames and `sidebarTitle`/`title` should be aligned, because now:
- file `installation.mdx` has `sidebarTitle: "Overview"`
- file `overview.mdx` has `title: "Quickstart"`

It is little bit unclear which of thes files is really overview :)

*Please assign it to me if it will be confirmed that it should be fixed.

**To Reproduce**
1. Run documentation with `mintlify dev`
2. Find section `Development` on navigation side bar
3. Try to click `authentication`
4. You will be redireced to `http://localhost:3000/overview/introduction`

**Expected behavior**
Navigation should contain actual items only.

**Screenshots**
![image](https://github.com/user-attachments/assets/b13f4f50-8c95-48f7-a38c-7f69ffa94880)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04.4 LTS (Jammy Jellyfish)
 - Browser: Firefox
 - Version: 128.0.2 (64-bit)

**Comment by talboren** [comment]
@achivkun this doesn't seem to reproduce in https://docs.keephq.dev/overview/introduction, are you sure you're using the latest main branch? can you explain how to reproduce?

**Comment by achivkun** [comment]
> @achivkun this doesn't seem to reproduce in https://docs.keephq.dev/overview/introduction, are you sure you're using the latest main branch? can you explain how to reproduce?

Hi @talboren. I'm on commit 1da8a9e28f83f8423572ac44eda984563f3a3236 (which is actual master now).
Here are the steps:
- go to `docs` directory of keep repo and run `mintlify dev` as recommended in [docs/README.md](https://github.com/keephq/keep/blob/main/docs/README.md)  
- go to locally runned `http://localhost:3000`

As per my understanding, problem should be related to [following line of code](https://github.com/keephq/keep/blob/main/docs/mint.json#L49) in `docs/mint.json`: 
```
    {
      "group": "Development",
      "pages": [
        "development/getting-started",
        "development/authentication",  <<<< this one
        "development/external-url"
      ]
    },
```

**Comment by talboren** [comment]
@achivkun perhaps when running mintlify in dev mode, it doesn't remove non-existing routings.
It could be awesome if you can open the PR to remove the unnecessary links.
