### ISSUE TITLE
[➕ Feature]: Merging of Incidents

### ISSUE THREAD

**Issue by Matvey-Kuk** [keephq/keep#1539]
If there are 2 incidents which are accidentally raised for the same reason, there should be an ability to merge them. 

- All associated objects should be also linked to the new incidents
- There should be a record in the DB that incidents are merged to the new one.
- The old Incident link should work since users send incident links to each other.

**Comment by achivkun** [comment]
@Matvey-Kuk, could you please asign it to me?

**Comment by Matvey-Kuk** [comment]
With pleasure! @achivkun

**Comment by achivkun** [comment]
It looks like for now I have less time than expected for this activity. I started to look at this yesterday, even did something, but then discovered that I most probably went wrong direction. @Matvey-Kuk please let me ask to clarify few things before I'll go further:
1) When we do merge - should we remove original incidents automatically (I guess this was the idea)? Alternative is to keep them, but make linked to new incident as children. Later user may decide if he/she wants to remove them or no. Second alrernative requires to add new field to Incident model to setup relation between incidents. I went second way initially, but then realized that first one is most probably those what was initially supposed here.
But at the same time second alternative (when we keep original incidents) makes it easier to implement following requirement:

> The old Incident link should work since users send incident links to each other.

2) Regarding this requirement: 

> There should be a record in the DB that incidents are merged to the new one.

Is there some specific table for this purpose, which is already exists? Or we have to add kind of "Audit/Timeline" table, which will store different events and their relation to certain object(s)?
In UI I see `Timeline` section, which is marked as `Coming Soon...` and I feel that this is the good place where this info can be placed, but I didn't find corresponding table on DB level. We have `AlertAudit`, but not `IncidentAudit`.

**Comment by frwl404** [comment]
My vacation has ended last week, I have no time to work on this ticket anymore. Please feel free to re-assign it.

**Comment by Kiryous** [comment]
Closed by #2274
