### ISSUE TITLE
[➕ Feature]: Creating incidents from the alert Feed

### ISSUE THREAD

**Issue by Matvey-Kuk** [keephq/keep#1540]
Use-case: As a user, I noticed that some alerts in the feed should be associated with a new incident. I choose those alerts, click "+Associate with an Incident," and can't assign them to the newly created incident; I can only assign them to an existing one. Even if I create a new incident in a new tab, the list of incidents in the popup won't update. If I refresh the Feed, I lose my page 😅 (covered here https://github.com/keephq/keep/issues/1541)

1) Make it possible to create a new incident from the popup
2) Make the list of incidents dynamic, so if an incident was created in the background, I should be able to choose it without updating a page.

<img width="1467" alt="Screenshot 2024-08-05 at 13 13 42" src="https://github.com/user-attachments/assets/7842d429-f809-41b1-b6d0-fac4023bcec1">

**Comment by sergtl** [comment]
@Matvey-Kuk Can I get this issue assigned to me, please

**Comment by Matvey-Kuk** [comment]
Revering this PR since it's failing on production build:
```

./app/alerts/alert-associate-incident-modal.tsx
66:34  Error: React Hook "useCallback" is called conditionally. React Hooks must be called in the exact same order in every component render.  react-hooks/rules-of-hooks
68:34  Error: React Hook "useCallback" is called conditionally. React Hooks must be called in the exact same order in every component render.  react-hooks/rules-of-hooks
70:29  Error: React Hook "useCallback" is called conditionally. React Hooks must be called in the exact same order in every component render.  react-hooks/rules-of-hooks
74:6  Warning: React Hook useCallback has missing dependencies: 'associateAlertsHandler', 'handleClose', and 'hideCreateIncidentForm'. Either include them or remove the dependency array. If 'handleClose' changes too often, find the parent component that defines it and wrap that definition in useCallback.  react-hooks/exhaustive-deps
77:3  Error: React Hook "useEffect" is called conditionally. React Hooks must be called in the exact same order in every component render.  react-hooks/rules-of-hooks
82:6  Warning: React Hook useEffect has a missing dependency: 'hideCreateIncidentForm'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps
```
To reproduce, try:
```
npm run build
```

**Comment by talboren** [comment]
> Revering this PR since it's failing on production build:
> 
> ```
> 
> ./app/alerts/alert-associate-incident-modal.tsx
> 66:34  Error: React Hook "useCallback" is called conditionally. React Hooks must be called in the exact same order in every component render.  react-hooks/rules-of-hooks
> 68:34  Error: React Hook "useCallback" is called conditionally. React Hooks must be called in the exact same order in every component render.  react-hooks/rules-of-hooks
> 70:29  Error: React Hook "useCallback" is called conditionally. React Hooks must be called in the exact same order in every component render.  react-hooks/rules-of-hooks
> 74:6  Warning: React Hook useCallback has missing dependencies: 'associateAlertsHandler', 'handleClose', and 'hideCreateIncidentForm'. Either include them or remove the dependency array. If 'handleClose' changes too often, find the parent component that defines it and wrap that definition in useCallback.  react-hooks/exhaustive-deps
> 77:3  Error: React Hook "useEffect" is called conditionally. React Hooks must be called in the exact same order in every component render.  react-hooks/rules-of-hooks
> 82:6  Warning: React Hook useEffect has a missing dependency: 'hideCreateIncidentForm'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps
> ```
> 
> To reproduce, try:
> 
> ```
> npm run build
> ```

Fixing the build, instead of reverting.
