### ISSUE TITLE
Local dev setup doesn't seem to work

### ISSUE THREAD

**Issue by ezhil56x** [keephq/keep#1546]
**Describe the bug**

Used the below command for starting development containers

```
docker compose -f .\docker-compose.dev.yml up
```

I'm getting error while building the docker image

**Expected behavior**
Development containers should start without any error and build

**Screenshots**
![image](https://github.com/user-attachments/assets/c8133c6b-f899-4878-b6eb-c024972f1a57)

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro

**Comment by Matvey-Kuk** [comment]
Duplicating https://github.com/keephq/keep/issues/1524 ?

**Comment by ezhil56x** [comment]
Just checked #1524, same issue
