### ISSUE TITLE
Background AI execution

### ISSUE THREAD

**Issue by Matvey-Kuk** [keephq/keep#1578]
Discussed in: https://github.com/keephq/keep-private/issues/1

**Comment by frwl404** [comment]
> Discussed in: https://github.com/keephq/keep-private/issues/1

@Matvey-Kuk  Is link in your comment correct? I've got 404 when tried to check that discussion.

**Comment by Matvey-Kuk** [comment]
@frwl404 yep, it's an internal issue, sorry for that.
