### ISSUE TITLE
[🔨 Enhancement]: New workflow execution page

### ISSUE THREAD

**Issue by talboren** [keephq/keep#1727]
![image](https://github.com/user-attachments/assets/1d6a71e7-91d5-41f4-9e84-5bb11c34a2d2)

**Comment by rajeshj11** [comment]
@talboren I would like to work on the feature. can you please assign it to me

**Comment by Maheshwarreddy970** [comment]
[rajeshj11](https://github.com/rajeshj11) if you're working on this . if not let me know.

**Comment by rajeshj11** [comment]
> [rajeshj11](https://github.com/rajeshj11) if you're working on this . if not let me know.

I am working on this.

**Comment by rajeshj11** [comment]
> [rajeshj11](https://github.com/rajeshj11) if you're working on this . if not let me know.

if you want to collaborate with me. I am open to collaborate

**Comment by Maheshwarreddy970** [comment]
yes

**Comment by rajeshj11** [comment]
> yes

I have sent the invite link. please check. below is the development branch. cut a branch on top of it for local development.
feat-1727-new-workflow-execution-page-main

**Comment by rajeshj11** [comment]
> ![image](https://private-user-images.githubusercontent.com/68807791/361333769-1d6a71e7-91d5-41f4-9e84-5bb11c34a2d2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3Mzc1MzYsIm5iZiI6MTcyNDczNzIzNiwicGF0aCI6Ii82ODgwNzc5MS8zNjEzMzM3NjktMWQ2YTcxZTctOTFkNS00MWY0LTllODQtNWJiMTFjMzRhMmQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI3VDA1NDAzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUxOTAxZGE1OTZhNTY5MTBkNWNjODc4NTM0MTZiMTdlNjUzMWZiOGE4NTRjNTk2YWE3ZTJiY2E0NzkzMmI1ODAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.R2Z6oK1eBZTmHUEqDmaqfdkGttJjJdbNVQf3MJt9LHs)
@talboren I have few doubts on the design.
1. on graph how data we need to show.
2. do we need to implement pagination on backend.(for all time filter. we can't fetch all the executions of the workflow at one go. if the workflow triggers every few minutes. It needs pagiantion from backend.)

**Comment by talboren** [comment]
> > ![image](https://private-user-images.githubusercontent.com/68807791/361333769-1d6a71e7-91d5-41f4-9e84-5bb11c34a2d2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3Mzc1MzYsIm5iZiI6MTcyNDczNzIzNiwicGF0aCI6Ii82ODgwNzc5MS8zNjEzMzM3NjktMWQ2YTcxZTctOTFkNS00MWY0LTllODQtNWJiMTFjMzRhMmQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI3VDA1NDAzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUxOTAxZGE1OTZhNTY5MTBkNWNjODc4NTM0MTZiMTdlNjUzMWZiOGE4NTRjNTk2YWE3ZTJiY2E0NzkzMmI1ODAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.R2Z6oK1eBZTmHUEqDmaqfdkGttJjJdbNVQf3MJt9LHs)
> > @talboren I have few doubts on the design.
> 
> 1. on graph how  much data we need to show.
> 2. do we need to implement pagination on backend.(for all time filter. we can't fetch all the executions of the workflow at one go. if the workflow triggers every few minutes. It needs pagiantion from backend.)

1. It depends on upper filter (all time | last 30d | etc.)
2. Sounds like yes! You can see the example @VladimirFilonov implemented for incidents or if it makes things easier start with maximum last 30 days

**Comment by rajeshj11** [comment]
@talboren Completed 80% of the work. need links for below things
1. tutorials.
2. Documentation.

To Do:(post conformation of these changes will work on this)
1. need to add Run button at top right corner.
2. filters needs to be added.
3. in table last column(... need clarification)

**Comment by rajeshj11** [comment]
> @talboren Completed 80% of the work. need links for below things
> 
> 1. tutorials.
> 2. Documentation.
> 
> To Do:(post conformation of these changes will work on this)
> 
> 1. need to add Run button at top right corner.
> 2. filters needs to be added.
> 3. in table last column(... need clarification)

1. need to add Run button at top right corner.(done)

**Comment by talboren** [comment]
> @talboren Dowanlods. what does it mean. is it table or workflow yml download.

It's to download the yaml (already supported via the menu today)

**Comment by rajeshj11** [comment]
> > @talboren Dowanlods. what does it mean. is it table or workflow yml download.
> 
> It's to download the yaml (already supported via the menu today)

https://www.loom.com/share/2a072534e88a413bbe8de542bac9863a
removde downloads. because of this
