### ISSUE TITLE
[🔨 Enhancement]: add the option to disable a workflow

### ISSUE THREAD

**Issue by shahargl** [keephq/keep#1739]

**Comment by shahargl** [comment]
Yea, go for it :)

**Comment by nejcr** [comment]
A linked PR is ready for a review.
@shahargl

**Comment by Mubashirshariq** [comment]
@Matvey-Kuk can I get this assigned or anybody is already working on this?

**Comment by rajeshj11** [comment]
@nejcr Hey, have you tried enabling the workflow back after disabling it?
