### ISSUE TITLE
[➕ Feature]: New widgets for Dashboards: MTTR, Alerts/hour, etc...

### ISSUE THREAD

**Issue by Matvey-Kuk** [keephq/keep#1769]
For now, dashboards support pretty basic preset-based widgets: <img width="1182" alt="Screenshot 2024-09-01 at 14 42 28" src="https://github.com/user-attachments/assets/ae68e914-da7e-413d-92a5-1f8a110f8ce0">

We need more widgets:

1.  MTTR (Mean Time To Resolve) — widget with a items/time graph, resolution: 24h.
2. Alerts / day — widget with a items/time graph, resolution: 24h.
3. Incidents / day — widget with a items/time graph, resolution: 24h.
4. Workflows / day — widget with a items/time graph, resolution: 24h.

**Comment by Matvey-Kuk** [comment]
Note: should work with https://github.com/keephq/keep/issues/1770

**Comment by 35C4n0r** [comment]
@Matvey-Kuk are you working on this?
Can I pick this up?

**Comment by Matvey-Kuk** [comment]
@35C4n0r absolutely! Not working on it myself :)

**Comment by Matvey-Kuk** [comment]
@35C4n0r are you working on this? :)

**Comment by 35C4n0r** [comment]
Yup.

**Comment by Matvey-Kuk** [comment]
@35C4n0r please let me know if you have some progress but for now I'm un-assigning and marking this one as open for grabs

**Comment by ezhil56x** [comment]
/attempt #1769
Can I get this assigned?

**Comment by Matvey-Kuk** [comment]
@35C4n0r Sure, re-assigning back! Could you please publish your questions about this one here?

**Comment by biplab-sutradhar** [comment]
@Matvey-Kuk  I'd like to work on this issue #1769. Could you provide some initial points to the relevant parts of the codebase that I should explore?

**Comment by 35C4n0r** [comment]
@Matvey-Kuk do we want the spark area chart (Used in the providers tile) or the Bar Graph (Used in the workflows Page) for Incidents.
For alerts we can use the spark-area and for the workflows the bar graph.

**Comment by Matvey-Kuk** [comment]
@35C4n0r up to your taste :) I think both any of them will work.

**Comment by 35C4n0r** [comment]
@Matvey-Kuk can you elaborate on what Incidents/day means, is it like
- (No. of incidents created) / day.
- or
- (No. of alerts attached to Incidents) /day

**Comment by Matvey-Kuk** [comment]
Payout for this bounty will be executed via GitHub Sponsors, not via Algora. Please activate https://github.com/sponsors/accounts for your account to receive the payout, sorry for the inconvenience

**Comment by 35C4n0r** [comment]
@Matvey-Kuk, looks good? 

![image](https://github.com/user-attachments/assets/0387de86-18d6-4939-93a5-221bbaa359de)

**Comment by 35C4n0r** [comment]
> @Matvey-Kuk can you elaborate on what Incidents/day means, is it like
> 
> * (No. of incidents created) / day.
> * or
> * (No. of alerts attached to Incidents) /day

@Matvey-Kuk

**Comment by Matvey-Kuk** [comment]
@35C4n0r sorry for the late reply! I meant:
(No. of incidents created) / day.

**Comment by Matvey-Kuk** [comment]
Bounty increased to $150

**Comment by Matvey-Kuk** [comment]
@35C4n0r thank you!
<img width="418" alt="Screenshot 2024-11-14 at 20 00 16" src="https://github.com/user-attachments/assets/310382eb-9d74-41dd-b5a3-45cf5b9ee1b3">
