### ISSUE TITLE
[➕ Feature]: Timeframe definition for the dashboard

### ISSUE THREAD

**Issue by Matvey-Kuk** [keephq/keep#1770]
For now, user can't look at a dashboard's data "week ago" or for a specific dates. Add a timeframe selector to allow users select "timedate start" and "timedate end" for the current dashboard.
<img width="1206" alt="Screenshot 2024-09-01 at 14 48 11" src="https://github.com/user-attachments/assets/e75d3cc7-8e07-4a6d-9948-541d30bd72da">

It's important that the selector's values should be represented in the url to simplify sharing :)

**Comment by destinedcodes** [comment]
@varshith257 are you working on this??

@Matvey-Kuk can I give it a shot???

**Comment by rajeshj11** [comment]
@Matvey-Kuk I’d like to work on this issue since it has been pending for some time

**Comment by rajeshj11** [comment]
@varshith257 If have made any progress on this task. please raise a draft pr. so that we can someone is working on this.

**Comment by rajeshj11** [comment]
> @Matvey-Kuk I’d like to work on this issue since it has been pending for some time

cc:^^
@talboren

**Comment by Matvey-Kuk** [comment]
@rajeshj11 let's check with @varshith257 first. @varshith257 are you working on it?

**Comment by talboren** [comment]
Thanks for the update @varshith257!
@rajeshj11 it's up for grabs :)

**Comment by Matvey-Kuk** [comment]
@rajeshj11 thank you for the contribution!

**Comment by rajeshj11** [comment]
> @rajeshj11 thank you for the contribution!

I have lost the test prod URL. Can you please share with me.  I will verify from my end

**Comment by rajeshj11** [comment]
> > @rajeshj11 thank you for the contribution!
> 
> I have lost the test prod URL. Can you please share with me. I will verify from my end

please ignore it.  found the URL and tested from my end
