### ISSUE TITLE
[➕ Feature]: Alert quality widgets for a dashboard

### ISSUE THREAD

**Issue by Matvey-Kuk** [keephq/keep#1779]
Users connect a lot of providers for Keep, and we should provide some analytics about the quality of events coming out of those providers.

I propose to add a few widgets, and an auto-provisioned dashboard called "Alert quality". 

Imagine a use-case when users wants to make sure that all alert providers provide "severity", "department", "product" and "affected_customer" from the sources. This dashboard should help them.

Widgets:
- A table with a per-provider alert quality. Rows: connected providers. Columns: provider name, amount of alerts received, % of alerts correlated to incidents, % of alerts having a "field" filled. Where field is a configurable set of fields. 
- % of alerts correlated to incidents
- % of alerts having a "field" filled

**Comment by Matvey-Kuk** [comment]
@vikashsprem absolutely! Please keep us updated on the progress :)

**Comment by rajeshj11** [comment]
@vikashsprem I would like to collaborate with you if that works for you. Please let me know how I can assist.

**Comment by vikashsprem** [comment]
@Matvey-Kuk should I add the "Alert Quality" dashboard as a sub-option under one of the Alerts in the sidebar?

Is the widget that should look like this (A rough overview): 
# Alert Quality Dashboard

| Provider Name | Alerts Received | % Alerts Correlated to Incidents | % Alerts with "Severity" | % Alerts with "Department" | % Alerts with "Product" | % Alerts with "Affected Customer" |
|---------------|-----------------|---------------------------------|---------------------------|----------------------------|-------------------------|----------------------------------|
| Provider A    | 1200            | 85%                             | 95%                       | 90%                        | 88%                     | 92%                              |
| Provider B    | 980             | 78%                             | 92%                       | 85%                        | 83%                     | 89%                              |
| Provider C    | 450             | 65%                             | 88%                       | 82%                        | 79%                     | 85%                              |
| Provider D    | 300             | 72%                             | 91%                       | 87%                        | 84%                     | 90%                              |

**Comment by vishalxtyagi** [comment]
@Matvey-Kuk @vikashsprem 
I noticed this open issue for the Alert Quality dashboard feature and I'm interested in contributing. Before I start working on it, I wanted to confirm a few things:

- Is this issue still available for contribution?
- As vikashsprem has already been assigned, are you open to having another contributor work on this as well? If so, would you prefer collaboration or should I wait to see if vikashsprem needs any assistance?
- If I am able to contribute, are there any specific guidelines or requirements I should be aware of before starting?

**Comment by Matvey-Kuk** [comment]
@vikashsprem you are absolutely right about the dashboard view :)

**Comment by Matvey-Kuk** [comment]
@vishalxtyagi it's up to @vikashsprem if he is open to the co-contributor :)

**Comment by rajeshj11** [comment]
@Matvey-Kuk We need information on this column: "% of alerts with a specified field filled."

Could you clarify where we can find the list of available fields? If possible, please provide the expected fields. Currently, we have implemented it as a filter, allowing users to select fields to add to the table.

Ideally, we should restrict users to selecting only one field, as we are aggregating based on these fields. Allowing multiple fields could be costly in terms of performance.

![Screenshot from 2024-09-27 13-04-26](https://github.com/user-attachments/assets/55936920-5e30-477e-8006-15d2675be593)

**Comment by Matvey-Kuk** [comment]
@rajeshj11 it's important to let users to configure the required fields because we can't predict which field is important for which customer. I suggest checking the field selector for "Feed". It's getting populated based on the content of present alerts.
<img width="444" alt="Screenshot 2024-09-29 at 11 55 41" src="https://github.com/user-attachments/assets/030408f1-7684-4ab7-a1d3-f15ad9f51827">

**Comment by rajeshj11** [comment]
> @rajeshj11 it's important to let users to configure the required fields because we can't predict which field is important for which customer. I suggest checking the field selector for "Feed". It's getting populated based on the content of present alerts. <img alt="Screenshot 2024-09-29 at 11 55 41" width="444" src="https://private-user-images.githubusercontent.com/3284841/371840003-030408f1-7684-4ab7-a1d3-f15ad9f51827.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc2MDQ1NTIsIm5iZiI6MTcyNzYwNDI1MiwicGF0aCI6Ii8zMjg0ODQxLzM3MTg0MDAwMy0wMzA0MDhmMS03Njg0LTRhYjctYTFkMy1mMTVhZDlmNTE4MjcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MjlUMTAwNDEyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTM1NjJjZjY2N2JkOTMxNzMxMThhNGZmYTk4YTJmYjBkNDdhOWNjNDgyYzRjMzAyZTJiZTA5YmIxYTVmZWMwMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.bWedG0Fy1Q4GiEQPTGnj-i15E771Z1GtJP2CSTJj6Vo">

@Matvey-Kuk @talboren I am a little confused about the approach. 

Current Implementation:

1. We display the total received, alerts to incidents, and severity as default columns, along with a custom column named "alert with {field} %,"
2. The "alerts with {field} %" column will dynamically update based on the user's field filter selection. To optimize performance and minimize computational load on SQL, users are restricted to selecting only one field at a time.
Reason:
Aggregating multiple fields can be resource-intensive, particularly with large datasets.


My question is should continue with the current approach? or do we need to different approach

**Comment by rajeshj11** [comment]
> @rajeshj11 it's important to let users to configure the required fields because we can't predict which field is important for which customer. I suggest checking the field selector for "Feed". It's getting populated based on the content of present alerts. <img alt="Screenshot 2024-09-29 at 11 55 41" width="444" src="https://private-user-images.githubusercontent.com/3284841/371840003-030408f1-7684-4ab7-a1d3-f15ad9f51827.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc2MDQ1NTIsIm5iZiI6MTcyNzYwNDI1MiwicGF0aCI6Ii8zMjg0ODQxLzM3MTg0MDAwMy0wMzA0MDhmMS03Njg0LTRhYjctYTFkMy1mMTVhZDlmNTE4MjcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MjlUMTAwNDEyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTM1NjJjZjY2N2JkOTMxNzMxMThhNGZmYTk4YTJmYjBkNDdhOWNjNDgyYzRjMzAyZTJiZTA5YmIxYTVmZWMwMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.bWedG0Fy1Q4GiEQPTGnj-i15E771Z1GtJP2CSTJj6Vo">

ack, will add the other options in the filter

**Comment by Matvey-Kuk** [comment]
> Reason: Aggregating multiple fields can be resource-intensive, particularly with large datasets.
Sounds valid! May I ask to add ability to add at least 3? I think 1 will be too limiting.

**Comment by rajeshj11** [comment]
> > Reason: Aggregating multiple fields can be resource-intensive, particularly with large datasets.
> 
> Sounds valid! May I ask to add ability to add at least 3? I think 1 will be too limiting.

okay

**Comment by Matvey-Kuk** [comment]
Payout for this bounty will be executed via GitHub Sponsors, not via Algora. Please activate https://github.com/sponsors/accounts for your account to receive the payout, sorry for the inconvenience

**Comment by vikashsprem** [comment]
> Payout for this bounty will be executed via GitHub Sponsors, not Algora. Please activate https://github.com/sponsors/accounts for your account to receive the payout, sorry for the inconvenience

@Matvey-Kuk I have enabled sponsor option on my github account.

**Comment by Matvey-Kuk** [comment]
<img width="394" alt="Screenshot 2024-10-21 at 11 22 26" src="https://github.com/user-attachments/assets/44a2d093-25ac-4745-98cb-b55890b66988">
@vikashsprem congrats!

**Comment by rajeshj11** [comment]
> <img alt="Screenshot 2024-10-21 at 11 22 26" width="394" src="https://private-user-images.githubusercontent.com/3284841/378334410-44a2d093-25ac-4745-98cb-b55890b66988.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk0OTk0MDQsIm5iZiI6MTcyOTQ5OTEwNCwicGF0aCI6Ii8zMjg0ODQxLzM3ODMzNDQxMC00NGEyZDA5My0yNWFjLTQ3NDUtOThjYi1iNTU4OTBiNjY5ODgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjFUMDgyNTA0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDgzNGM2NmI3ODFkZTJkMzVkODRkYWRjZGQxZTAwYTAxNWFjZDAwYzdmMTE2ZGRmNTY0OTBhYzFhZGMzYzkyNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.CYshB5A6mweI95p49-1Fd2fkFjbzP7PrNymqMB1yf1I"> @vikashsprem congrats!

@Matvey-Kuk We have not informed you about the split. Anyhow we will handle it internally. I will note that next, I will inform you upfront.
