### ISSUE TITLE
[👨🏻‍💻 Internal]: Using standard OTLP env convention on backend service

### ISSUE THREAD

**Issue by ErezLevip** [keephq/keep#1817]
**Describe the solution you'd like**
Using OTEL_EXPORTER_OTLP_ENDPOINT instead of OTLP_ENDPOINT
Using OTEL_SERVICE_NAME instead of SERVICE_NAME
Extracting protocol from the endpoint instead of OTLP_SPAN_EXPORTER
Supporting OTEL_EXPORTER_OTLP_TRACES_ENDPOINT for traces
Supporting OTEL_EXPORTER_OTLP_LOGS_ENDPOINT for logs
Supporting OTEL_EXPORTER_OTLP_METRICS_ENDPOINT for metrics

**Additional context**
OTLP reference https://opentelemetry.io/docs/languages/sdk-configuration/otlp-exporter/

**Comment by talboren** [comment]
Thanks @ErezLevip, we'll have a look on it!

**Comment by talboren** [comment]
@vr-varad absolutely, it's yours!

**Comment by vr-varad** [comment]
hey @talboren I am almost done with the issue just wanted to know what would be endpoints for 
OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
OTEL_EXPORTER_OTLP_LOGS_ENDPOINT
OTEL_EXPORTER_OTLP_METRICS_ENDPOINT

**Comment by vr-varad** [comment]
@talboren

**Comment by talboren** [comment]
Hey @vr-varad, no need for those vars in docker-compose since we're not using OTEL with OTLP by default.

**Comment by talboren** [comment]
Sorry for the slow response btw!

**Comment by vr-varad** [comment]
No problem them I will raise a pr.
