### ISSUE TITLE
[🔨 Enhancement]: Clicking "Save" on step doesn't save the changes on the server (only on deploy)

### ISSUE THREAD

**Issue by shahargl** [keephq/keep#1937]
1. Clicking "Save" should actually save the workflow (maybe change and save & deploy)

**Comment by shahargl** [comment]
![CleanShot 2024-09-16 at 10 39 47@2x](https://github.com/user-attachments/assets/9efcfe32-60b1-4c7e-8ac5-aec273968935)

**Comment by rajeshj11** [comment]
@shahargl I  would like to work on it

**Comment by rajeshj11** [comment]
@shahargl can i get assigned?

**Comment by shahargl** [comment]
@rajeshj11 assigned

**Comment by rajeshj11** [comment]
@shahargl In save & deploy functionality.
1. deployment happens only if the workflow does not have any errors.
2. If no errors on clicking save & deploy.  It should save the step and deploy automatically.

Please confirm

**Comment by shahargl** [comment]
@rajeshj11 I'm not sure whats the difference is between 1 and 2, but I'll answer generally:
when the user clicks on "save and deploy":
1. if there is an error that is validated on the frontend - show an indicative error message
2. o/w, it should save (like today, locally) and then deploy (send PUT to the server like clicking on deploy button)
