### ISSUE TITLE
Tests: basic usability tests

### ISSUE THREAD

**Issue by talboren** [keephq/keep#197]
We need to have some simple usability tests that makes sure Keep works (both in api/cli/ui mode) for every new PR.

**Comment by matdexir** [comment]
Hi
I would like to help with this task. However, I am not too sure how to get started. 
What are your expectations for the usability tests and where should I put those said tests?

**Comment by talboren** [comment]
Hey @matdexir, I'll try to better describe this task and change the description as soon as it's ready :) Thank you for showing this interest!

**Comment by talboren** [comment]
@matdexir I'll reopen this issue with elaborated information.
