### ISSUE TITLE
[🔌 Provider]: Get events from email

### ISSUE THREAD

**Issue by talboren** [keephq/keep#2018]
As a user, I would like to be able to send events/alerts to Keep through an email.

**Comment by shahargl** [comment]
Is it a good first issue?😅

**Comment by talboren** [comment]
Removed, thanks @shahargl

**Comment by talboren** [comment]
For future contributors, please ignore this issue for now as this is an internal issue 🙏🏼

**Comment by AMANCHAUBEY8822** [comment]
yes
