### ISSUE TITLE
[🐛 Bug]: Adding filter to workflow execution table cause refresh of the page

### ISSUE THREAD

**Issue by shahargl** [keephq/keep#2025]
https://github.com/user-attachments/assets/b5562517-104d-43c6-994f-c59ff40d4515

**Comment by talboren** [comment]
@rajeshj11 FYI: i think this was intentional as it fetches data from the backend (filtering happens in the backend)

**Comment by shahargl** [comment]
@rajeshj11 

even if true - there are only 3 filters ("static", "manual" and "alert") why not fetching them ahead? 
second, in nextjs, only the table should refresh, not all the page (which takes more time to load). the problem is that it changes the URL and then router.push which is navigating to another page.

**Comment by rajeshj11** [comment]
@shahargl @talboren will work on the feedback/bug.  please assign it to me.

**Comment by shahargl** [comment]
assigned! 🤴

**Comment by rajeshj11** [comment]
@shahargl How urgent it is. can I pick this after this
 https://github.com/keephq/keep/issues/1780

**Comment by AMANCHAUBEY8822** [comment]
This metric indicates the success rate of the workflows
