### ISSUE TITLE
[📃 Docs]: Missing documentation for a few providers

### ISSUE THREAD

**Issue by Matvey-Kuk** [keephq/keep#2033]
Those providers are missing docs:

```
"service now",
"python",
"prometheus",
"gke",
"github",
"dynatrace",
"kafka",
"auth0",
"bash",
"keep",
"bigquery",
"parseable",
```

Python and bash are disabled for cloud, "keep" provider is a placeholder for alerts without a provider.

**Comment by asr2003** [comment]
@Matvey-Kuk I'd like to work on this.
/attempt #2033

Is it to update in docs/overview.md?

**Comment by Matvey-Kuk** [comment]
@asr2003 thank you! It's to write docs for those providers.

**Comment by asr2003** [comment]
@Matvey-Kuk Got it! I haven't checked this  dir docs/providers/documentation  :)

**Comment by Matvey-Kuk** [comment]
This issue is a follow-up for this PR: https://github.com/keephq/keep/pull/2034/files#diff-5e3398e47b06f1fa9941dcc4cf3717ecec1f38bcc676502cb7943c84a541f744R16 and I hope it will be merged.

Please as part of the PR also remove NON_DOCUMENTED_PROVIDERS array to make sure tests are passing well and picking up new provider docs :)

**Comment by Vishalll07** [comment]
Hey @Matvey-Kuk  is the issue still open , can you please check ? So that I can get into it

**Comment by Matvey-Kuk** [comment]
@asr2003 hey, are you still working on this?

**Comment by asr2003** [comment]
Yes, will draft PR by EOD

**Comment by rishisulakhe** [comment]
/attempt #2033
Plan->Creating various .mdx files as mentioned in issue with each providing all required details accordingly.

**Comment by Matvey-Kuk** [comment]
@algora-pbc

**Comment by Matvey-Kuk** [comment]
@rishisulakhe done!

**Comment by rishisulakhe** [comment]
@Matvey-Kuk Thankyou!!
