### ISSUE TITLE
[➕ Feature]: Allow formatting in the incident description

### ISSUE THREAD

**Issue by Matvey-Kuk** [keephq/keep#2039]
Incident description should support some basic formatting, at least new lines :)
<img width="1172" alt="Screenshot 2024-09-30 at 11 34 50" src="https://github.com/user-attachments/assets/46109f3f-0347-4cdf-8bbc-62c0eea8fbb5">

**Comment by tejasathalye** [comment]
hey @Matvey-Kuk can you assign it to me? 
I can look into this issue!

**Comment by Matvey-Kuk** [comment]
Sure @tejasathalye !

**Comment by shahargl** [comment]
@tejasathalye we use `ReactQuill` as a editor, you can (and should?) use it.

**Comment by tejasathalye** [comment]
yess @shahargl sure!

**Comment by Matvey-Kuk** [comment]
@LitZeus hey, just checking if you still working on this :)

**Comment by LitZeus** [comment]
@Matvey-Kuk Yes yes

**Comment by Matvey-Kuk** [comment]
@LitZeus please let me know if you have progress here :)
