### ISSUE TITLE
[🐛 Bug]: if incident id is not UUID the backend returns 500

### ISSUE THREAD

**Issue by shahargl** [keephq/keep#2057]
![CleanShot 2024-10-01 at 14 03 03@2x](https://github.com/user-attachments/assets/4906e2a3-ac50-4082-8e77-277ede37ac9c)

**Comment by priyanshuverma-dev** [comment]
I would I to work on this issue @shahargl

**Comment by amritansh22** [comment]
/attempt 
@shahargl What is the expectation here? 
I could see the Incident table is having the id of type of UUID. 
I am assuming we have to gracefully handle the error and return a 4xx error ?

**Comment by yashs33244** [comment]
I have fixed this issue, but not authorized to make a pull request. Can U assign me this issue.
