### ISSUE TITLE
[🐛 Bug]: NavBar dancing on page load

### ISSUE THREAD

**Issue by Kiryous** [keephq/keep#2091]
**Describe the bug**
On load there's no dashboards data, so the placeholder is showed, placeholder width is bigger than actual dashboard's links, so if there're dashboards, after loading navbar is "dancing". 

https://github.com/user-attachments/assets/ee029e0e-bf0a-452b-abb6-7a20a22600b0

**Comment by Skapoor1927** [comment]
assigned this issue to me . I am working on the same

**Comment by naaa760** [comment]
Hello @Kiryous  :)
Please assign me this issue!

**Comment by Kiryous** [comment]
hey guys! sorry, this issue is already fixed in https://github.com/keephq/keep/pull/2093
