### ISSUE TITLE
[➕ Feature]: Don't reply 200 to the healthcheck if current migration is not representing the DB state

### ISSUE THREAD

**Issue by Matvey-Kuk** [keephq/keep#2118]
Our services rollout relies on a healthcheck endpoint. Multiple incidents happened when we rolled out the service and migration took longer than expected. 

I propose to reply 503 if current code's latest migration head > db migration head.

**Comment by talboren** [comment]
@Matvey-Kuk IMHO this is not the right approach. We should enable auto migration for our deployments instead and if migration fails the deployment fails as well. The problem right now is we do not distinguish environments good enough and therefore migrations do not run automatically. I propose to fix this issue rather then create a mechanism to "oversee" it
