### ISSUE TITLE
[➕ Feature]: add support for AWS secret manager

### ISSUE THREAD

**Issue by talboren** [keephq/keep#2204]

**Comment by HarshitVashisht11** [comment]
Hi, can you provide some description for this issue. I am willing to solve this issue

**Comment by HarshitVashisht11** [comment]
Got it 👍 can I solve this issue

**Comment by talboren** [comment]
With pleasure! @HarshitVashisht11 assigned it to you.

**Comment by talboren** [comment]
@HarshitVashisht11  any progress here? 🙏🏼
