### ISSUE TITLE
[🐛 Bug]: Improve Efficiency and Performance of `docs_get_providers_list.py`

### ISSUE THREAD

**Issue by Mefisto04** [keephq/keep#2209]
**Describe the bug**
The current implementation of `docs_get_providers_list.py` can be optimized for better performance and efficiency, particularly in file handling and data processing.

**To Reproduce**

- Run the docs_get_providers_list.py script in its current state.
- Observe the performance during file I/O operations.
- Check the time taken for validation checks and regular expression processing.
- Note the memory usage when handling large provider documentation files.

**Expected behavior**
The script should run more efficiently, with reduced I/O time, optimized memory usage, and faster validation processes.

Please assign this issue to me so that i can start working on it.

**Comment by Mefisto04** [comment]
hey @talboren, please review this, and assign me this so that i can start work on it.

**Comment by talboren** [comment]
@Mefisto04 I'm going to go ahead and close this issue since I'm not sure what's the context here. This is a script that runs in <1 seconds and we use it as a manual step in most cases.
If you feel this is wrong please let me know!
