### ISSUE TITLE
[➕ Feature]: Utilise priority for extraction of same attribute

### ISSUE THREAD

**Issue by mfroembgen** [keephq/keep#2214]
**Is your feature request related to a problem? Please describe.**
Currently the extraction ends after the first match so you can't use it multiple times with the usage of prio. 

**Describe the solution you'd like**
It would be helpful to use the prio for the same attribute as a way to not have to supply a full regex in one extraction but rather split into multiple once.  

**Additional context**
https://getkeep.slack.com/archives/C04PT44MATS/p1728982668488089

**Comment by talboren** [comment]
Thank you for this issue @mfroembgen!
