### ISSUE TITLE
[🐛 Bug]: UI extraction page behaviour

### ISSUE THREAD

**Issue by mfroembgen** [keephq/keep#2215]
**Describe the bug**
Extraction page has some weird behaviour. 
 
**To Reproduce**
1. If you edit a extraction the condition does not get shown even though it is existing
2. There is no feedback for adjusting or adding a condition (after pressing enter to apply)
3. The condition stays at the page even after updating the extraction
4. Inside the update message it is mentioning that the mapping was updated instead of extraction  

**Expected behavior**
1. Condition gets loaded with the other settings 
2. Feedback (maybe ui chip) after pressing enter to apply the condition
3. Condition gets removed on update/save 
4. Extraction instead of mapping in the update message 

**Additional context**
![CleanShot 2024-10-16 at 14 09 50](https://github.com/user-attachments/assets/c970eacb-d703-4e18-bf13-563501820d57)

**Comment by talboren** [comment]
@mfroembgen thank you for this issue! I'll get it fixed ASAP
