### ISSUE TITLE
[🐛 Bug]: Create incident form is not cleared

### ISSUE THREAD

**Issue by Kiryous** [keephq/keep#2247]
**Describe the bug**
If you previously clicked "Edit" incident,  and then click the "Create incident" button 

**To Reproduce**

1. Go to Incidents list.
2. Click on **Edit** (pencil icon)
3. Click **Cancel**
4. Click **Create incident**
5. You will see the title, description and assignee from the Incident you tried to edit.

**Expected behavior**
The form should be empty when you click on **Create Incident** 

**Screenshots**
<video src="https://github.com/user-attachments/assets/d680ea57-9369-47ae-96c0-5a0e4d07c8df"/>

**Comment by AkashJana18** [comment]
I would like to work on this issue can you please assign me?

**Comment by Harsh2509** [comment]
I think this bug is resolved as everything works fine for me.

https://github.com/user-attachments/assets/2827d0f0-5cd9-40de-8e74-cd0393f18e9f

**Comment by VladimirFilonov** [comment]
@Harsh2509 It works fine if you click "Cancel". In this case `clearForm` method is called. But if you will press ESC or click outside of the modal - it will be closed without calling `clearForm` inside form controller.

@AkashJana18 are you still up for fixing it?

**Comment by AkashJana18** [comment]
@VladimirFilonov No i haven't worked on this issue
You can solve it.
Thank you.

**Comment by Kiryous** [comment]
Closed by #2274
