### ISSUE TITLE
[🐛 Bug]: "Deduplication Rules" page duplicating deduplication rule

### ISSUE THREAD

**Issue by imorph** [keephq/keep#2264]
**Describe the bug**
Deduplication rules are duplicated after looking inside and exit with "Cancel" button

**To Reproduce**
1. Go to "Deduplication"
2. Choose and click one of the Non-default deduplication rules
3. click "Cancel"
4. Now you have two identical deduplication rules
5. Second one can be retrieved from API as well
6. delete button works

**Expected behavior**
"Cancel" button should not create copy of the rule

**Screenshots**

https://github.com/user-attachments/assets/bf913370-e197-4c4c-b522-cf36fad0eb64

**Comment by shahargl** [comment]
hey @imorph, thanks! looking at it right now.

**Comment by shahargl** [comment]
@imorph released `0.27.1` with the fix, thank you!
