### ISSUE TITLE
[🐛 Bug]: alert.mp3 playing at random time when navigating UI

### ISSUE THREAD

**Issue by imorph** [keephq/keep#2287]
**Describe the bug**
Unrelated music composition ("Into the fire" by ikoliks from artlist.io) playing during navigating UI after some time.
I see it at least in Arc browser (chromium based)

**To Reproduce**
Open UI and click here and there with sound on.

**Expected behavior**
No unrelated music compositions during work with the system.

**Additional context**
This is `alert.mp3` from `./keep-ui/public/music/` that is playing, I understand that this was some kind of mock while there is no proper sounds of alert/incoming event other UI interactions, but it is kinda annoying =)
There is no other way to disable it but mute tab completely.

**Comment by shahargl** [comment]
@imorph did you configure some preset to be noisy before?

**Comment by shahargl** [comment]
![CleanShot 2024-10-24 at 17 24 31@2x](https://github.com/user-attachments/assets/54f52f80-b69f-4841-aee6-83d0e0be82c2)

**Comment by imorph** [comment]
@shahargl I made several, but I don't remember if i used that toggle. Some alerts that are coming from outside have `isNoisy` field set to `true`

**Comment by shahargl** [comment]
oh so this isn't a bug but a feature ^^

some users asked "noisy alerts" - to make some noise using `isNoisy` flag. 
I guess you have some script generating alerts?

**Comment by imorph** [comment]
> I guess you have some script generating alerts?

that is true, I have control over alert generation. So the easy fix is not send `isNoisy` flag and use other some custom field?

Still, some random music composition looks unrelated to anything alert'y, first time I heard it i was scared and did not understood what is happening =)

**Comment by shahargl** [comment]
yea the user who asked it have a NOC room where they have many screens so they need something with noise ^^

**Comment by shahargl** [comment]
> So the easy fix is not send isNoisy flag and use other some custom field?
exactly

**Comment by shahargl** [comment]
Closing for now
