### ISSUE TITLE
[ Dependencies ] Upgrade next-auth to v5

### ISSUE THREAD

**Issue by Kiryous** [keephq/keep#2306]

**Comment by shahargl** [comment]
This is pretty big one. Any reason for that?

Also - v5 is still not GA last time I checked (2 weeks ago~)

**Comment by shahargl** [comment]
https://github.com/nextauthjs/next-auth/discussions/7513

**Comment by shahargl** [comment]
Also this - https://github.com/nextauthjs/next-auth/discussions/9511#discussioncomment-10866829

**Comment by Kiryous** [comment]
I noticed `useSession()` usage delays actual fetch on the incident page, so at the first load user see "No Incidents" for a sec or two, then "loading", then actual incidents. I want to try it out to see if it fixes this. Let's wait for release, no problem.

**Comment by shahargl** [comment]
@Kiryous I think we should somehow use the `useSession` as soon as we can on the app loading, so other pages will already get the initialized session.
