### ISSUE TITLE
[➕ Feature]: Interactive Onboarding Tour

### ISSUE THREAD

**Issue by Dkghuser** [keephq/keep#2319]
**Provide an Interactive Onboarding Tour:** 
Implement an interactive tour that guides new users through the key features and initial setup of the platform.

**Objective:** 
Improve user experience for new users by providing a guided tour of the platform's key features and initial setup process.

**Description:**

**Welcome Screen:** When a user signs in for the first time, they are greeted with a welcome screen that briefly introduces the platform and its capabilities.
**Step-by-Step Guidance:** The tour will guide users through the primary features of the platform, such as creating and managing alerts, configuring notifications, and viewing incident reports. Each step will highlight the relevant UI elements and provide a brief explanation of their functionality.
**Progress Indicators:** Visual indicators such as progress bars or step counters will be included to show users their progress through the tour.
**Interactive Elements:** Users can interact with the tour by clicking on highlighted elements, which will trigger the next step in the tour. This helps users get hands-on experience with the platform features.
**Tooltips and Popovers:** Tooltips and popovers will provide additional information and tips as users navigate through the tour.
**Skip and Resume Options:** Users should have the option to skip the tour at any point or resume it later from where they left off.
**End of Tour Summary:** At the end of the tour, users will receive a summary of the features they have explored, along with links to detailed documentation for further reading.

**Benefits:**

**Enhanced User Engagement:** An interactive tour can significantly reduce the learning curve for new users, making them feel more confident and engaged with the platform.
**Higher Feature Adoption:** By showcasing the key features and their benefits, users are more likely to utilize the full range of functionalities the platform offers.
**Improved User Retention:** A positive initial experience can lead to higher user retention rates, as users are more likely to continue using a platform they understand and find useful.

**Comment by talboren** [comment]
Hey @Dkghuser, thank you for this issue! I'm working on it as part of https://github.com/keephq/keep/issues/2299.
