### ISSUE TITLE
[🐛 Bug]:  SMTP Provider returning error - "SMTP AUTH extension not supported by server."

### ISSUE THREAD

**Issue by gjolps** [keephq/keep#2342]
**Describe the bug**
I'm trying to configure the SMTP Provider. At our organization, we do not have an authentication for SMTP.
But since, username/password was mandatory, I entered test/test as username/password and got the error "SMTP AUTH extension not supported by server."

I tried the test SMTP feature from Settings and it worked perfectly.
I had kept the username and password field blank.

**To Reproduce**

1. Go to Providers
2. Click on SMTP Provider
3. Add Details
PS - SMTP Server does not have authentication 

**Expected behavior**
SMTP Provider should have connected to the server without credentials as we do not have one. 

**Screenshots**
![image](https://github.com/user-attachments/assets/0f541241-76f6-4099-96cf-1955e00fd133)

**Additional context**
Will update in comments if you've any questions/doubts regarding the issue

Thanks!

**Comment by talboren** [comment]
Thank you @gjolps! I’m on it :)

**Comment by gjolps** [comment]
thanks @talboren for the quick response! :)
