### ISSUE TITLE
Missing provider Zabbix

### ISSUE THREAD

**Issue by SomeAverageDev** [keephq/keep#240]
**Is your feature request related to a problem? Please describe.**
no, just a use case

**Describe the solution you'd like**
centralize all Zabbix problems in a single keep pane of glass

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by talboren** [comment]
@SomeAverageDev thank you for this issue! would love to further discuss this with you so I can get to it ASAP.
Would you mind joining [Keep's Slack community](https://slack.keephq.dev) so we can chat over there?

**Comment by talboren** [comment]
@SomeAverageDev would love for you to try it ;)

**Comment by talboren** [comment]
Closed at #246 and #251
