### ISSUE TITLE
[➕ Feature]: add version number to the home page

### ISSUE THREAD

**Issue by pradip-allwyn** [keephq/keep#2495]
can you add the version to the default home page of the software so we know what version are running using Docker?

**Comment by talboren** [comment]
Hey @pradip-allwyn, thanks for creating this issue! I believe we already do that, please see the screenshot here:

![CleanShot 2024-11-14 at 17 43 44](https://github.com/user-attachments/assets/9712d670-c2d2-4129-80bb-a187b9cd8d0c)

Are you meaning anything else?

**Comment by talboren** [comment]
@pradip-allwyn I'm closing this for now - if you still think this is relevant please reopen!
