### ISSUE TITLE
[🐛 Bug]: Provisioned Integrations Default to HTTP Instead of HTTPS Despite HTTPS UI Access

### ISSUE THREAD

**Issue by kirillyu** [keephq/keep#2814]
**Describe the bug**
When creating integrations via the Keep UI, the keep host is set with the http protocol instead of https. This occurs despite the UI being accessed through https://keephq... For example, when creating a Grafana integration under Providers -> Connect to Grafana, the contact point in Grafana is automatically provisioned with an http address, which cannot be edited due to it being provisioned.

**To Reproduce**

Access the Keep UI through https://keephq...
Navigate to Providers -> Connect to Grafana.
Follow the steps to create an integration with Grafana.
Open Grafana and observe the provisioned contact point address.
**Expected behavior**
The integrations created via the Keep UI should have the https protocol for the keep host if the UI is accessed via https.

**Screenshots**
(Add screenshots here if available to demonstrate the issue.)

**Additional context**

Helm chart: [Keep Helm Charts](https://github.com/keephq/helm-charts/tree/main/charts/keep)
Components versions:
Backend: 0.31.4
Frontend: 0.31.4
WebSocket: 1.6.1-16-distroless
Deployment: Kubernetes using the Helm chart.
UI access: https://keephq...

**Comment by talboren** [comment]
Hey @kirillyu, thanks for opening this issue!

May I ask you to check if the `KEEP_API_URL` is set correctly in your keep-backend instance?
A quick way to test that would be to go to the settings page:

![CleanShot 2024-12-12 at 11 18 54](https://github.com/user-attachments/assets/86c21125-60ea-47bc-bf16-b0b48be8692c)

And observing the value in the webhook page

**Comment by Knyage** [comment]
Hi! I'm for @kirillyu .
We are using http.
We have traffic passing through reverse-proxy, which redirects it to ingress-keep. 

But when we try to enable the tls option in the configs, we get the error “too many redirects...”. If tls is disabled - it works (but part of the functionality is broken, I see timeout errors in logs when processing front to backend).
The functionality that I've noticed that breaks - I can't open incidents to which alerts are bound. Incidents without alerts open correctly. 

how can we set the KEEP_API_URL variable explicitly, but leave http in ingress? We have tried various ways to correct the helm-charts, but it still doesn't work. 

Translated with DeepL.com (free version)

**Comment by Matvey-Kuk** [comment]
@Knyage could you please tell me which endpoint exactly is redirecting infinitely using Dev Console in the browser?

**Comment by Knyage** [comment]
@Matvey-Kuk  Hmm, I think we've got it figured out for ourselves. 
Ticket can be closed, thanks for the response!

**Comment by Matvey-Kuk** [comment]
@Knyage happy to hear! What was the problem? :)

**Comment by Knyage** [comment]
The problem was setting up our reverse-proxy =)
