### ISSUE TITLE
[➕ Feature]: Create Deduplication rule on provision

### ISSUE THREAD

**Issue by fues-joe1** [keephq/keep#2872]
**Is your feature request related to a problem? Please describe.**
I'm trying to set up Keep using as much IaC as possible, and it's only possible to create dedupe rules in the console or the API. It'd be great for my use case if they could be set up via configuration.

**Describe the solution you'd like**
Ideally, they should be able to be provisioned resources, in the same manner as workflows, providers, and dashboards.

**Describe alternatives you've considered**
It'd also be cool if Keep resources and rules could be deployed with Terraform

**Additional context**

**Comment by talboren** [comment]
@fues-joe1 We have a terraform module contributed by the amazing @pehlicd, but it's not too maintained, we need to pick it up: https://github.com/pehlicd/terraform-provider-keep
I'll take care of provisioning for deduplication rules for now

**Comment by skynetigor** [comment]
Hi!
I have implemented this feature and added documentation. Details in PR - https://github.com/keephq/keep/pull/2877
