### ISSUE TITLE
[➕ Feature]: Add externalLabels field for prometheus integration

### ISSUE THREAD

**Issue by Nctllnty** [keephq/keep#2873]
**Is your feature request related to a problem? Please describe.**
![image](https://github.com/user-attachments/assets/6c8c1673-a3a1-4c1f-a8a9-3e6421d756ec)

When I configure prometheus to add custom labels, such as cluster: test, I cannot get the custom label information in the keep alarm

**Describe the solution you'd like**

I can get the custom tag by keep

**Describe alternatives you've considered**

**Additional context**

**Comment by talboren** [comment]
@Nctllnty may I ask you to dump in the payload of a prometheus alert you expect to see this externalLabels value but don't see?:

![CleanShot 2024-12-19 at 09 30 55](https://github.com/user-attachments/assets/8815f275-2bbf-4d77-b6f0-45aa16f3b423)

**Comment by Nctllnty** [comment]
`{
  "receiver": "efk-system",
  "status": "firing",
  "alerts": [
    {
      "status": "firing",
      "labels": {
        "alertname": "test",
        "cluster": "tencent-sin153-cycor",
        "prometheus": "monitoring/obs-kube-prometheus-prometheus",
        "scope": "monitoring",
        "severity": "warn",
        "users": "[ivan.wang@eclicktech.com.cn](mailto:ivan.wang@eclicktech.com.cn),[musk.zhang@eclicktech.com.cn](mailto:musk.zhang@eclicktech.com.cn),[george.shang@eclicktech.com.cn](mailto:george.shang@eclicktech.com.cn)"
      },
      "annotations": {
        "description": "test description"
      },
      "startsAt": "2024-09-04T05:48:56.396Z",
      "endsAt": "0001-01-01T00:00:00Z",
      "generatorURL": "http://obs-kube-prometheus-prometheus.monitoring:9090/graph?g0.expr=count%28node_os_info%29+%3E+1\u0026g0.tab=1",
      "fingerprint": "9807524ca7bf3564"
    }
  ],
  "groupLabels": {
    "alertname": "test"
  },
  "commonLabels": {
    "alertname": "test",
    "cluster": "tencent-sin153-cycor",
    "prometheus": "monitoring/obs-kube-prometheus-prometheus",
    "scope": "monitoring",
    "severity": "warn",
    "users": "[ivan.wang@eclicktech.com.cn](mailto:ivan.wang@eclicktech.com.cn),[musk.zhang@eclicktech.com.cn](mailto:musk.zhang@eclicktech.com.cn),[george.shang@eclicktech.com.cn](mailto:george.shang@eclicktech.com.cn)"
  },
  "commonAnnotations": {
    "description": "test description"
  },
  "externalURL": "http://obs-kube-prometheus-alertmanager.monitoring:9093/",
  "version": "4",
  "groupKey": "{}/{alertname=~\"^(?:.*)$\"}:{alertname=\"test\"}",
  "truncatedAlerts": 0
}`

**Comment by Nctllnty** [comment]
> @Nctllnty我可以请您将您希望看到的这个 externalLabels 值看不到 prometheus 的警报的有效负载转储入口吗？
> 
> ![CleanShot 2024-12-19 09 30 55](https://private-user-images.githubusercontent.com/68807791/397265755-8815f275-2bbf-4d77-b6f0-45aa16f3b423.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ2MDA1OTIsIm5iZiI6MTczNDYwMDI5MiwicGF0aCI6Ii82ODgwNzc5MS8zOTcyNjU3NTUtODgxNWYyNzUtMmJiZi00ZDc3LWI2ZjAtNDVhYTE2ZjNiNDIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE5VDA5MjQ1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJkOGFhNDlhNDkxN2I2YWM2NjAxODE3ZmVkMjE5ZjA3MzRlZjFlZDFlZTY1M2I3YjA3NjY3NjE4YWIwOGMyOTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Ak63q3awVbQCxLLiquDRm0Cp-9hgi5a1wMTQiwcvY1s)

```
{

  "id": "KubernetesDiskPressure--cycor-dev",

  "name": "KubernetesDiskPressure--cycor-dev",

  "status": "firing",

  "severity": "info",

  "lastReceived": "2024-12-19T09:12:02.280Z",

  "firingStartTime": "2024-12-19T09:12:02.280Z",

  "environment": "unknown",

  "isFullDuplicate": false,

  "isPartialDuplicate": false,

  "duplicateReason": null,

  "service": "obs-kube-state-metrics",

  "source": [
    "prometheus"
  ],

  "apiKeyRef": "webhook",

  "message": null,

  "description": "10.153.4.94 has DiskPressure condition --->VALUE = 0",

  "pushed": true,

  "event_id": "ad908dfe-d209-4ab7-8fab-8865186ddb6e",

  "url": null,

  "labels": {
    "pod": "obs-kube-state-metrics-746d99c547-tqlkv",
    "node": "10.153.4.94",
    "scope": "cycor-dev",
    "users": "musk.zhang@eclicktech.com.cn",
    "status": "true",
    "cluster": "tencent-sin153-cycor",
    "project": "gears-v4",
    "service": "obs-kube-state-metrics",
    "endpoint": "http",
    "severity": "fatal",
    "alertname": "KubernetesDiskPressure--cycor-dev",
    "condition": "DiskPressure",
    "namespace": "monitoring",
    "prometheus": "monitoring/obs-kube-prometheus-prometheus"
  },

  "fingerprint": "0f008fcc80d7563e083689e00ba2e49f91dafd57d3ac6ea37746ef96dd1782d5",

  "deleted": false,

  "dismissUntil": null,

  "dismissed": false,

  "assignee": null,

  "providerId": null,

  "providerType": "prometheus",

  "note": null,

  "startedAt": "2024-12-19 09:12:03",

  "isNoisy": false,

  "enriched_fields": [],

  "incident": "bf464342fa834eed8db381689ff4a0ee",

  "endsAt": "0001-01-01T00:00:00Z",

  "pod": "obs-kube-state-metrics-746d99c547-tqlkv",

  "namespace": "monitoring",

  "payload": {
    "endsAt": "0001-01-01T00:00:00Z",
    "startsAt": "2024-12-19T09:10:32.101Z",
    "generatorURL": "http://obs-kube-prometheus-prometheus.monitoring:9090/graph?g0.expr=sum+without+%28container%2C+instance%2C+job%29+%28kube_node_status_condition%7Bcondition%3D%22DiskPressure%22%2Cstatus%3D%22true%22%7D%29+%21%3D+1&g0.tab=1"
  },

  "condition": "DiskPressure",

  "endpoint": "http",

  "node": "10.153.4.94",

  "alert_hash": "2ec719ab0e28c614567a881672beea711da99af446653831606f0c6ce324853a",

  "prometheus": "monitoring/obs-kube-prometheus-prometheus",

  "startsAt": "2024-12-19T09:10:32.101Z",

  "cluster": "tencent-sin153-cycor",

  "scope": "cycor-dev",

  "project": "gears-v4",

  "alertname": "KubernetesDiskPressure--cycor-dev",

  "annotations": {},

  "users": "musk.zhang@eclicktech.com.cn",

  "generatorURL": "http://obs-kube-prometheus-prometheus.monitoring:9090/graph?g0.expr=sum+without+%28container%2C+instance%2C+job%29+%28kube_node_status_condition%7Bcondition%3D%22DiskPressure%22%2Cstatus%3D%22true%22%7D%29+%21%3D+1&g0.tab=1"

}
```

**Comment by Nctllnty** [comment]
I'm sorry, I missed this label when I checked, externalLabels is passed in correctly

**Comment by Nctllnty** [comment]
> @Nctllnty我可以请您将您希望看到此 externalLabels 值但却看不到的 prometheus 警报的有效负载转储进去吗？：
> 
> ![CleanShot 2024-12-19 09 30 55](https://private-user-images.githubusercontent.com/68807791/397265755-8815f275-2bbf-4d77-b6f0-45aa16f3b423.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ2MDA4MzIsIm5iZiI6MTczNDYwMDUzMiwicGF0aCI6Ii82ODgwNzc5MS8zOTcyNjU3NTUtODgxNWYyNzUtMmJiZi00ZDc3LWI2ZjAtNDVhYTE2ZjNiNDIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE5VDA5Mjg1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNlMWRmOTRjODNmYjdjMWIzY2Y5ZWVkYjY4NzBhMWFlYmI1NDI0MGI2NjcyYzEwNmM5MGRhY2RlNjY2MmM4NTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.G9Cb0ROTSz-WKD8girWC0ehv4pjWVaF0rKre0qx6Y14)

I'm sorry, I missed this label when I checked, externalLabels is passed in correctly
