### ISSUE TITLE
[➕ Feature]: More filter support in "Correlations"

### ISSUE THREAD

**Issue by Nctllnty** [keephq/keep#2874]
**Is your feature request related to a problem? Please describe.**
There are too few filters supported in "Correlations". For example, I cannot associate the alarms based on the keywords in the alarm name.
![image](https://github.com/user-attachments/assets/46e19af1-50a4-46b7-a344-5f4a5921eedb)

**Describe the solution you'd like**
Use CEL query results to create a "Correlations rule"

**Describe alternatives you've considered**

**Additional context**

**Comment by talboren** [comment]
@Nctllnty thank you for this! A correlation rule that is based on CEL is a great idea (it's actually what we use behind the scenes).
You should be able type down whatever you'd like in the filter, it's a "creatable" input. You can use any attribute you get in alerts there.
![CleanShot 2024-12-19 at 12 17 43](https://github.com/user-attachments/assets/1e3c70e0-af6c-4e2a-a884-09371af2557b)
Just try to type the attribute you want to use and it should work!
