### ISSUE TITLE
Provider: Microsoft Planner

### ISSUE THREAD

**Issue by n-benchoubane** [keephq/keep#307]
I think it would add value to trigger creation of tasks effectively within Microsoft Planner based on the alerts.

Really awesome service ;D

**Comment by shahargl** [comment]
Hey @n-benchoubane, thanks for opening this issue and welcome to Keep’a community!

can you add a little bit about the use case? Are you considering using Keep for that?

**Comment by talboren** [comment]
> I'm exploring the possibility of generating tasks for teams based on alerts from Prometheus or incoming requests (possibly through a Slack bot). These tasks would be created in Planner, with a setup similar to Trello.
> 
> I'm currently delving deeper into Keep. While I haven't explored the Microsoft Teams integration yet, I plan to give it a try next week
> 
> I appreciate Planner for its calendar features, straightforward design, and its ability to generate simple charts based on the tasks created. It puts the onus on the administrators of the Planner space to manage the tasks effectively. It's a simple tool that, while not originally designed as a CMMS, could be exceptionally valuable for reporting in that context. I believe it would bring great value to Keep, opening up a new horizon. Thank you for listening!

Sounds like an interesting use case! I’ll dive in to that deeper this weekend so I can understand Planner better. Would love for you to join our Slack at https://slack.keephq.dev so we can discuss this with more ease.

**Comment by devblin** [comment]
@talboren can I work on this feature?

**Comment by talboren** [comment]
@devblin of course!
