### ISSUE TITLE
Provider: Grafana OnCall

### ISSUE THREAD

**Issue by vladfr** [keephq/keep#309]
**Describe the provider you want to add**
Grafana OnCall is a nice incident management solution. Keep could add support, starting from the existing PD provider.

**Describe your use case**
We use Oncall self-hosted and support for launching incidents in Oncall would really help our Keep adoption.

**Are you already using Keep?**
Evaluating

**Comment by talboren** [comment]
> **Describe the provider you want to add** Grafana OnCall is a nice incident management solution. Keep could add support, starting from the existing PD provider.
> 
> **Describe your use case** We use Oncall self-hosted and support for launching incidents in Oncall would really help our Keep adoption.
> 
> **Are you already using Keep?** Evaluating

Hey @vladfr, thank you for opening this great issue! We’ll have the Grafana OnCall provider ready by early next week 💪🏼 

I welcome you to join our Slack community where we can more easily talk https://slack.keephq.dev


Thanks again!
