### ISSUE TITLE
Provider: Linear

### ISSUE THREAD

**Issue by vladfr** [keephq/keep#310]
**Describe the provider you want to add**
Linear is a new task management tool for Agile teams, loosely built around Scrum, KanBan and Cycles.

**Describe your use case**
Linear works best for developers, but our Dev/Ops Platform team also uses it. I could see an integration to Keep where we create tickets in a Linear project after a set number of alerts have been detected (or manually at the push of a button).

**Are you already using Keep?**
Evaluating

**Comment by talboren** [comment]
@logicncode happy to help with anything you may need (available here or in [Slack](https://slack.keephq.dev))

**Comment by TakshPanchal** [comment]
Hey @logicncode and @chandan1619, are you still working on this issue?

**Comment by TakshPanchal** [comment]
Hey @talboren,  I need help regarding what input should I take for setting up webhook?

According to my search, there are two ways to set up a webhook
**Manual**
Go to Linear-setting -> API and paste a REST API endpoint where an HTTP POST request is received (Ig it should be `/alert/event/{provider_type}`. That's all. It gives a secret value which can be used to verify the HTTP Post request in Keep Server. 

**2. Create Webhook using Linear's GraphQL API** 
We can create a webhook for the whole org or a team using the user's personal API key (and `team_id` if the alert is only for the specific team). We should also take the event options like this. 

<img width="670" alt="image" src="https://github.com/keephq/keep/assets/52617262/74d310cf-5433-4596-849c-30b9124544ff">

**Comment by TakshPanchal** [comment]
In the first, we only need secret_key from the user, so that incoming webhooks should be verified. For the second we need the User's personal API Key, and the options in the images.

**Comment by talboren** [comment]
> Hey @talboren, I need help regarding what input should I take for setting up webhook?
> 
> According to my search, there are two ways to set up a webhook
> 
> **1. Webhook created by User using Linear's UI** Go to Linear-setting -> API and paste a REST API endpoint where an HTTP POST request is received (Ig it should be `/alert/event/{provider_type}`. That's all. It gives a secret value which can be used to verify the HTTP Post request in Keep Server.
> 
> **2. Create Webhook using Linear's GraphQL API** We can create a webhook for the whole org or a team using the user's personal API key (and `team_id` if the alert is only for the specific team). We should also take the event options like this.
> 
> <img alt="image" width="670" src="https://user-images.githubusercontent.com/52617262/268488672-74d310cf-5433-4596-849c-30b9124544ff.png">

Sounds like the second option is a good choice for our "auto webhook installation" method. (setup_webhook in BaseProvider)


> In the first, we only need secret_key from the user, so that incoming webhooks should be verified. For the second we need the User's personal API Key, and the options in the images.

Is there a way for Linear to send HTTP headers? if so - they need to send Keep's API key of that user.


Let me know if something is not clear.

**Comment by TakshPanchal** [comment]
> Is there a way for Linear to send HTTP headers? If so - they need to send Keep's API key of that user.

Linear is sending HTTP Post req to keep's server with their API Key. We should verify that API key I think.

**Comment by talboren** [comment]
> > Is there a way for Linear to send HTTP headers? If so - they need to send Keep's API key of that user.
> 
> Linear is sending HTTP Post req to keep's server with their API Key. We should verify that API key I think.

If we can make them send our API key in the header (we need that) so there's no real need for that. It's just a way to verify the message is coming from Linear.

**Comment by TakshPanchal** [comment]
According to Linear's [webhook docs](https://developers.linear.app/docs/graphql/webhooks), they're sending HTTP requests with their secret. see [securing webhooks](https://developers.linear.app/docs/graphql/webhooks#securing-webhooks).

**Comment by TakshPanchal** [comment]
I tried their graphql API to create a webhook; we can get the secret which is generated by them directly from the API query, so, Can we save that SECRET_KEY and verify alerts using them? 
<img width="839" alt="image" src="https://github.com/keephq/keep/assets/52617262/e152911f-843d-4222-ad9c-6c2931511dc7">

**Comment by TakshPanchal** [comment]
> > > Is there a way for Linear to send HTTP headers? If so - they need to send Keep's API key of that user.
> > 
> > 
> > Linear is sending HTTP Post req to keep's server with their API Key. We should verify that API key I think.
> 
> If we can make them send our API key in the header (we need that) so there's no real need for that. It's just a way to verify the message is coming from Linear.

Hey yes, we can send Keep's the API key while creating or mutating webhooks.
