### ISSUE TITLE
Add Gitlab Pipelines Provider

### ISSUE THREAD

**Issue by shahargl** [keephq/keep#326]
Users should be able to `notify` (action) Gitlab Pipelines, `GitlabpipelinesProvider` should be implemented with the necessary methods implemented.

The provider should be able to execute a [GitLab Pipeline](https://docs.gitlab.com/ee/api/pipelines.html) with parameters.

**Comment by devblin** [comment]
@shahargl I would like to work on this feature.
Also, it would be helpful if you can add the requirements 🙌🏽 .

**Comment by melsonic** [comment]
@shahargl @talboren How can I receive this reward? It is not showing in the dashboard
