### ISSUE TITLE
[UI] Alert item dropdown is cropped

### ISSUE THREAD

**Issue by johnnypez** [keephq/keep#349]
**Describe the bug**

Dropdown is cropped on  alter item on alerts page

**To Reproduce**
1. Go to 'https://platform.keephq.dev/alerts
2. Click on the dropdown icon on the left of the bottom alert
3. Note that the dropdown is barely visible but once it's open you can scroll down to reveal it.

**Expected behavior**

The dropdown should not be cropped inside the container of the alert list items.

**Screenshots**

![image](https://github.com/keephq/keep/assets/181485/49c1fe16-df19-481f-97ad-9b40fd7e4f9b)

**Desktop (please complete the following information):**
 - OS: MacOS Ventura 13.2
 - Browser Chrome Version 
 - Version 116.0.5845.187 (Official Build) (arm64)

**Comment by shahargl** [comment]
Hey @johnnypez, I’ll look into it 👀 thanks for reporting that 👑

**Comment by shahargl** [comment]
@johnnypez - merged! let me know if that's cool for you :)

**Comment by johnnypez** [comment]
Looks good 👍
