### ISSUE TITLE
Hover issue on web icons 

### ISSUE THREAD

**Issue by RANJEETJ06** [keephq/keep#354]
**Describe the bug**

when on web hovering on icons

https://github.com/keephq/keep/assets/121615244/25a9ead7-dd7e-40b2-889f-05e70c5f97fc

**Comment by shahargl** [comment]
Hey @RANJEETJ06, thanks for reporting! I’ll give it a look soon!

**Comment by shahargl** [comment]
fixed! thanks @RANJEETJ06.
