### ISSUE TITLE
add support for `notify` method in linear provider

### ISSUE THREAD

**Issue by devblin** [keephq/keep#369]
**Is your feature request related to a problem? Please describe.**
Linear provider currently doesn't support `notify` method to create issues in linear app.

**Describe the solution you'd like**
- implementing `notify` method in `LinearProvider` class

**Additional context**

**Comment by devblin** [comment]
@shahargl if the issue/feature is confirmed, I would like to work on it 🙌🏽

**Comment by devblin** [comment]
@shahargl also, I found that existing `query` method doesn't work.

**Comment by shahargl** [comment]
@devblin sorry for not seeing it. yea you can start work on it!
