### ISSUE TITLE
feat: dynatrace

### ISSUE THREAD

**Issue by shahargl** [keephq/keep#386]

**Comment by devblin** [comment]
Hey @shahargl, is this feature still active for pick-up?

**Comment by shahargl** [comment]
Yes! It actually is. You can start and I’ll join you because I want to be part of it. @devblin

**Comment by devblin** [comment]
That's great @shahargl , can you please add more details about the provider? I checked the dynatrace and it has so many things in the [platform](https://www.dynatrace.com/platform/).

**Comment by shahargl** [comment]
So part of that task is exploring how alerts works there. The goal is:
1. Get alerts opened in dynatrace
2. Add Keep as a webhook so every alert triggered in dynatrace will invoke the webhook to Keep

**Comment by shahargl** [comment]
@devblin

**Comment by devblin** [comment]
Got it, I will explore and ask you in slack for more queries!

**Comment by Sup3rJ** [comment]
Can give you some information about this:

You can configure in Dynatrace a webhook to be called when there is an alert related to a problem notification profile.

@devblin Some docs that can help:
https://www.dynatrace.com/support/help/dynatrace-api/environment-api/problems/problems/get-details
https://www.dynatrace.com/support/help/dynatrace-api/environment-api/problems-v2/problems/get-problem-details
https://www.dynatrace.com/support/help/dynatrace-api/environment-api/problems-v2/problems/get-problems-list
https://docs.dynatrace.com/docs/observe-and-explore/notifications-and-alerting/problem-notifications/webhook-integration

**Comment by shahargl** [comment]
hey @Sup3rJ, I've started working with dynatrace, can we hop on a chat to get more details from you? are you familiar with dynatrace?
