### ISSUE TITLE
Arm support

### ISSUE THREAD

**Issue by PeterSzegedi** [keephq/keep#390]
**Describe the bug**
If you run keep on Arm, it seqfaults right after loading the providers.
The dev docker-compose build fails on Mac M1 with:

> error: command 'cmake' failed: No such file or directory

This could be an issue for customers who run self-hosted infrastructure on Arm like AWS Graviton or similar

**To Reproduce**
1a. Start keep on Arm
1b. docker-compose -f docker-compose.dev.yml up

**Expected behavior**
Keep works as expected

**Desktop (please complete the following information):**
 - OS: Mac M1

**Comment by talboren** [comment]
@PeterSzegedi I'm using Mac M1 and I have just built Keep using `docker-compose -f docker-compose.dev.yml up`, can you advise on what version of Docker do you use? Can you share the log of the build process?
