### ISSUE TITLE
Cannot update the Prometheus provider

### ISSUE THREAD

**Issue by PeterSzegedi** [keephq/keep#391]
**Describe the bug**
Trying to update the Prometheus provider results in

> Scopes are invalid for prometheus: undefined

**To Reproduce**
1. Create a new Prometheus provider
2. Try to update it

**Expected behavior**
The Prometheus update works

**Comment by talboren** [comment]
Hey @PeterSzegedi, thank you for all the issues, that's awesome and super helpful! 💪🏼 

Regarding this specific issue, is it still reproducing? I just tried to reproduce this issue locally and couldn't. Are you on the latest revision?

**Comment by PeterSzegedi** [comment]
Ah, I should have add the steps. 
I have pulled the latest main of keep. 
`kind create cluster
helm install keep chart/keep/
helm install prometheus prometheus-community/kube-prometheus-stack`

Created a prometheus provider pointing to https://prometheus-kube-prometheus-prometheus.svc.
Tried to change http://prometheus-kube-prometheus-prometheus.default.svc

I have just recreated the issue.
`keep            default         1               2023-10-09 18:49:51.75447 +0100 BST deployed keep-0.0.1                      0.1.0      
prometheus      default         1               2023-10-09 18:50:02.244455 +0100 BSTdeployed kube-prometheus-stack-51.4.0    v0.68.0`

**Comment by talboren** [comment]
> Ah, I should have add the steps. I have pulled the latest main of keep.
> 
> `kind create cluster
> 
> helm install keep chart/keep/
> 
> helm install prometheus prometheus-community/kube-prometheus-stack`
> 
> Created a prometheus provider pointing to https://prometheus-kube-prometheus-prometheus.svc. Tried to change http://prometheus-kube-prometheus-prometheus.default.svc
> 
> `keep default deployed keep-0.0.1 0.1.0
> 
> prometheus default 1 deployed kube-prometheus-stack-51.4.0 v0.68.0`

Thanks!

**Comment by ajaydevtron** [comment]
Hello @talboren .

I am facing the same .

Image version

backend: **us-central1-docker.pkg.dev/keephq/keep/keep-api:latest**
frontend: **us-central1-docker.pkg.dev/keephq/keep/keep-ui:latest**

Could you please share the PULL request in which this issue has fix ?

**Comment by shahargl** [comment]
Hey! Can you share the image ids? Did you try re-pull it?

**Comment by talboren** [comment]
@ajaydevtron I'm not sure about the PR where this was fixed since I couldn't ever reproduce this issue. I'd love to open it once again and address it ASAP if you have the way to reproduce it. Please let me know ❤️
