### ISSUE TITLE
Deleting a provider does not clean up the changes on the infrastructure

### ISSUE THREAD

**Issue by PeterSzegedi** [keephq/keep#392]
**Is your feature request related to a problem? Please describe.**
The delete provider option does not undo the changes or recommends you info about how to undo them. Say you add subscriptions to your sns topics, they will stay there and keep sending data to keep.

**Describe the solution you'd like**
Either clean up the changes done, or recommend actions to clean up

**Comment by skynetigor** [comment]
Hi @PeterSzegedi 
I recently added infra to enable providers to clean up their subscriptions/webhooks/etc.
But since each provider requires specific clean up logic, for now I only implemented webhook removal for PagerDuty.
Please take a look at my PR if you have time.
