### ISSUE TITLE
Cloudwatch provider - make the subscription URL configurable

### ISSUE THREAD

**Issue by PeterSzegedi** [keephq/keep#395]
**Is your feature request related to a problem? Please describe.**
The Cloudwatch provider automatically tries to create the subscription to your backend URL. It might not be a single hop on a prod environment.

This also causes an issue when someone tries to use the provider from the vanilla helm charts. The backend is on http, but the SNS subscription wants to subscribe on https resulting in:

`"errorCode": "InvalidParameterException",
    "errorMessage": "Invalid parameter: Endpoint must match the specified protocol",`

**Describe the solution you'd like**
Maybe provide an option where to subscribe, instead of generating the URL.

**Comment by Ilia1099** [comment]
Hi!
I'd be glad to contribute to your project and take this issue on me.
Are there any additional requirements and notes I need to take into account except for described above and those in CONTRIBUTING.md ?

**Comment by shahargl** [comment]
Hey @Ilia1099, welcome!

nope, we usually suggest contributors to join our Slack. The reason is that in the first issues there are many questions about how to do things and it easier to help there. Do you want me to assign you the ticket?

**Comment by Ilia1099** [comment]
> Hey @Ilia1099, welcome!
> 
> nope, we usually suggest contributors to join our Slack. The reason is that in the first issues there are many questions about how to do things and it easier to help there. Do you want me to assign you the ticket?

Sure, I’d appreciate that!

**Comment by shahargl** [comment]
Assigned

**Comment by Ilia1099** [comment]
> Hey @Ilia1099, welcome!
> 
> nope, we usually suggest contributors to join our Slack. The reason is that in the first issues there are many questions about how to do things and it easier to help there. Do you want me to assign you the ticket?

is it possible to join your slack?

**Comment by talboren** [comment]
> > Hey @Ilia1099, welcome!
> > nope, we usually suggest contributors to join our Slack. The reason is that in the first issues there are many questions about how to do things and it easier to help there. Do you want me to assign you the ticket?
> 
> is it possible to join your slack?

You are more then welcome! [This is the link :)](https://slack.keephq.dev)

**Comment by ezhil56x** [comment]
Can I get this assigned?
/attempt #395

**Comment by ezhil56x** [comment]
@Ilia1099 
Are you still working on this or can I take up?
Thanks!

**Comment by unworld11** [comment]
/attempt #395

1. Modify the Provider Configuration
Add a new configuration option for the subscription URL in the provider's configuration schema
2. Update the Provider Logic
Use the new configuration option when creating the subscription. If the option is not set, fall back to the existing behavior
3. Update the Helm Charts
Add a new value for the subscription URL in the Helm chart values file and template

**Comment by Ayush-Vish** [comment]
@unworld11  Are you still working on this issue.

**Comment by unworld11** [comment]
no i am unassigning myself.

**Comment by HemanthGangula** [comment]
/attempt #395

### Implementation Plan

1. **Update Configuration Schema**:
    - Add a new optional field `subscription_url` to the configuration schema.

2. **Modify Subscription Logic**:
    - Update the logic to use the provided `subscription_url` if available, otherwise generate the default URL.

3. **Update Documentation**:
    - Reflect the new `subscription_url` configuration option in the documentation.
