### ISSUE TITLE
Document the minimum set of permissions to set up the providers

### ISSUE THREAD

**Issue by PeterSzegedi** [keephq/keep#396]
**Is your feature request related to a problem? Please describe.**
It would be nice if the providers or docs would cover the minimum set of permissions required for setting up the pull or push. A good example is the Cloudwatch provider. It can live with a set of SNS and Cloudwatch permissions, but you have to eyeball the code to understand how to narrow it down

**Describe the solution you'd like**
A bit more documentation included on the set up provider parts

**Comment by ericallam** [comment]
👍 for documenting how to properly setup Cloudwatch Logs IAM role/permissions

**Comment by talboren** [comment]
> 👍 for documenting how to properly setup Cloudwatch Logs IAM role/permissions

We’re working on it ASAP

**Comment by talboren** [comment]
FYI @ericallam @PeterSzegedi

@shahargl closed this issue 🫡
