### ISSUE TITLE
Document the changes and undoing those changes for the provider configurations

### ISSUE THREAD

**Issue by PeterSzegedi** [keephq/keep#397]
**Is your feature request related to a problem? Please describe.**
Some of the providers will try to automagically set up themselves for webhook/push mode. This could give an ease of use for some, but I was a bit afraid about not knowing what would happen to my accounts, if I grant a high permission to Keep and let it modify stuff. 
It also introduced an issue that, if I have my environment for example for Datadog or Cloudwatch in IaC (terraform for example), it might make changes that are not in my source control and it will get rolled back on the next run. Or, if I have 500 alarms outside of IaC and all get a small modifications from the providers, I will need to manually undo things, if I want to delete the provider for some reason.

**Describe the solution you'd like**
It would be nice to document what will be modified exactly and to have the delete provider option either recommend undo steps, or do them if the setup was automatic.

**Comment by Matvey-Kuk** [comment]
This bounty is a part of our effort to welcome new contributors to the repo.
