### ISSUE TITLE
Add Apache Kafka Provider

### ISSUE THREAD

**Issue by gavinheale** [keephq/keep#400]
Hi,

Would it be possible to have an https://kafka.apache.org/ provider.  

Regards,
Gavin

**Comment by shahargl** [comment]
Hey @gavinheale thanks for opening this issue! Can you add a little context about what would you imagine Kafka provider to do?

**Comment by gavinheale** [comment]
Hi,

I am thinking of using this for application-related alerts.  

The primary use would be to consume application alerts that are posted on a kafka topic.  

A secondary use would be produce actions from a workflow.

For example, I am thinking of a system that monitors IoT devices.  When it does not see traffic for a while, it could publish an inactivity alert on the "alerts" topic.  Keep could be used to create a workflow that includes both automated actions (by publishing to the "restart" queue) as well as notifications to humans through slack or some other similar technology.

For details on producing and consuming kafka events, see https://kafka-python.readthedocs.io/en/master/

**Comment by shahargl** [comment]
Got you, thanks for that. I’m encouraging you to join our slack where we can collaborate and help you use Keep. Meanwhile I’ll start working on it.
