### ISSUE TITLE
AKS provider

### ISSUE THREAD

**Issue by shahargl** [keephq/keep#407]
Like the GKE provider - add the ability to query on kubernetes clusters running on Azure

**Comment by rishi-raj-jain** [comment]
@talboren @shahargl 

Can you share the GKE provider documentation? Happy to learn and implement.

**Comment by talboren** [comment]
@rishi-raj-jain I guess you mean the AKS documentation: https://learn.microsoft.com/en-us/python/api/overview/azure/mgmt-kubernetesconfiguration-readme?view=azure-python I think this is a good place to start.
Take inspiration from the GKE provider that @shahargl implemented. LMK if I can assist you anyhow.

**Comment by rishi-raj-jain** [comment]
Thanks for the resources, @talboren. Working on it...

**Comment by talboren** [comment]
@rishi-raj-jain how is it going? anything I can assist with?

**Comment by rishi-raj-jain** [comment]
@talboren I just cancelled my attempt as I don't think I'd be able to complete this...

**Comment by talboren** [comment]
@rishi-raj-jain no worries, thanks!

**Comment by cjsanjay** [comment]
@talboren - Do you have a test environment to test the changes?
I am close to the solution. Also, if you can assign this to me it will be great.

**Comment by talboren** [comment]
Yo @cjsanjay, thanks for trying to resolve this issue.

Have you tried creating a new account, using the free tier? (https://azure.microsoft.com/en-us/free/kubernetes-service/)

I'll be happy to see you around our [Slack community](https://slack.keephq.dev).

**Comment by cjsanjay** [comment]
@talboren - Raised a PR with the support for AKS.

**Comment by talboren** [comment]
@cjsanjay sorry for the conflict here. hope to see you contribute in the future. https://github.com/keephq/keep/issues/440 might be a nice place to start
