### ISSUE TITLE
Add provider documentation link in provider side panel

### ISSUE THREAD

**Issue by talboren** [keephq/keep#426]

**Comment by abhishekmishragithub** [comment]
has this been fixed already?

**Comment by talboren** [comment]
@abhishekmishragithub not yet, we welcome contributions :)

**Comment by abhishekmishragithub** [comment]
i did look into doc but the issue is not very descriptive, happy to help here :)
can you attach a screenshot maybe?

**Comment by talboren** [comment]
Yea sure!

So every provider has its documentation in our [docs](https://docs.keephq.dev/overview/introduction).
For example, Zabbix provider documentation can be found [here](https://docs.keephq.dev/providers/documentation/zabbix-provider)

I thought about maybe adding some kind of clickable icon next to the provider name that opens a new tab with the respective documentation:

![CleanShot 2023-11-01 at 17 36 30](https://github.com/keephq/keep/assets/68807791/df2d1ab9-7c06-4b66-b672-7c5754055cae)

Let me know if you didn't fully understand

**Comment by talboren** [comment]
(You can see the providers page at https://platform.keephq.dev)

**Comment by abhishekmishragithub** [comment]
Thanks for the details @talboren,  I will have a look!

**Comment by talboren** [comment]
@abhishekmishragithub any progress with this one? I'd like to close it if you haven't had the time to start yet

**Comment by abhishekmishragithub** [comment]
@talboren I was sick the whole last week, and haven't started on this yet. If this is on priority then please take a stab. If not then i can take care of it this week.

**Comment by talboren** [comment]
@abhishekmishragithub first of all I hope you feel well now! no worries, this is not so high priority and can certainly wait for you to take care of it :)

**Comment by talboren** [comment]
@abhishekmishragithub btw, I would be really happy to see your around our [Slack community](https://slack.keephq.dev)

**Comment by abhishekmishragithub** [comment]
Thanks @talboren, i am doing good, thanks for being kind. 
will join the slack, thanks :)

**Comment by talboren** [comment]
Hey @abhishekmishragithub, is this still relevant? sorry for bugging you around this, just want to know if I should do it or not

**Comment by talboren** [comment]
@abhishekmishragithub pinging one more time to see if this is still relevant :)

**Comment by TakshPanchal** [comment]
Hey I am looking on to it, I am thinking to add document type of icon after the name of the provider, which redirects to the "docs.keephq.dev/providers" page of the respective provider.

**Comment by TakshPanchal** [comment]
I have added this icon and it will redirect to the doc website
<img width="703" alt="image" src="https://github.com/keephq/keep/assets/52617262/ee94b4f1-1a13-47c6-ad7f-4ff18354c2df">

**Comment by TakshPanchal** [comment]
There is also an issue here; I didn't find any slub property in the provider object, so I am taking `provider.type` as a slug for the URL. For a few providers, it is creating issues because the `type` is not equal to the slug of the document URL; for example, for the "newrelic" provider, the type is `newrelic` but in [docs](https://docs.keephq.dev/providers/documentation/new-relic-provider) it is "new-relic" slug.
