### ISSUE TITLE
New Relic Provider: Support incoming webhook, webhook auto-installation and scopes.

### ISSUE THREAD

**Issue by talboren** [keephq/keep#440]
**Describe the provider you want to add**
Enhance New Relic provider to support incoming webhook requests, webhook auto installation and the required scopes (and scope validation).
For reference, you can see how it is implemented in [Zabbix](https://github.com/keephq/keep/blob/main/keep/providers/zabbix_provider/zabbix_provider.py) provider, [Datadog](https://github.com/keephq/keep/blob/main/keep/providers/datadog_provider/datadog_provider.py) provider or [Grafana](https://github.com/keephq/keep/blob/main/keep/providers/grafana_provider/grafana_provider.py) provider.

**Describe your use case**
A few users tried to connect New Relic but lacked the basic capabilities Keep provides.

**Are you already using Keep?**
**Yes**/No

**Additional context**
-

**Comment by punctualprocrastinator** [comment]
/attempt #440
hi i am very new  to opensource and programing . just completed the python  Kaggle course  can you what things  i need to learn in order complete this task

**Comment by talboren** [comment]
Hey @punctualprocrastinator - I'd probably start with https://docs.keephq.dev first and read through to understand how Keep really works. Then you can probably try to start Keep locally using docker-compose and play with the platform a bit.

FYI, this task is a little "advance" in the sense of the knowledge you need to have with both Keep and python in general.

**Comment by talboren** [comment]
> Hey @punctualprocrastinator - I'd probably start with https://docs.keephq.dev first and read through to understand how Keep really works. Then you can probably try to start Keep locally using docker-compose and play with the platform a bit.
> 
> FYI, this task is a little "advance" in the sense of the knowledge you need to have with both Keep and python in general.

Feel free to join [our Slack](https://slack.keephq.dev) if you want to discuss things over a DM

**Comment by punctualprocrastinator** [comment]
> > Hey @punctualprocrastinator - I'd probably start with https://docs.keephq.dev first and read through to understand how Keep really works. Then you can probably try to start Keep locally using docker-compose and play with the platform a bit.
> > FYI, this task is a little "advance" in the sense of the knowledge you need to have with both Keep and python in general.
> 
> Feel free to join [our Slack](https://slack.keephq.dev) if you want to discuss things over a DM

okay thank you ❤️

**Comment by mohanish2504** [comment]
Hey there sorry for conflict.
@punctualprocrastinator are you attempting this?

**Comment by mohanish2504** [comment]
Hey there. 
I think New Relic will be moving maximum APIs to graphql.

https://docs.newrelic.com/docs/apis/intro-apis/introduction-new-relic-apis/#rest-api

Specifically, the one we should be using will be deprecated after 01/2024.

1. To add webhook: https://api.newrelic.com/docs/#/Deprecation%20Notice%20-%20Alerts%20Channels/get_alerts_channels_json
2. Query incidents: https://api.newrelic.com/docs/#/Deprecation%20Notice%20-%20Alerts%20Channels/get_alerts_channels_json
3. Query Events: https://api.newrelic.com/docs/#/Deprecation%20Notice%20-%20Alerts%20Events/get_alerts_events_json
4. To remove webhook: https://api.newrelic.com/docs/#/Deprecation%20Notice%20-%20Alerts%20Channels/delete_alerts_channels__channel_id__json

**Comment by mohanish2504** [comment]
I think I can manage to do that.
@talboren @shahargl sounds good?

**Comment by talboren** [comment]
@mohanish2504 i think you can give it a go. @punctualprocrastinator will first learn a bit about Keep and then will take first contribution :)

**Comment by talboren** [comment]
> /attempt #440 hi i am very new to opensource and programing . just completed the python Kaggle course can you tell me what things I need to learn in order to complete this task
> 
> Options
> * [
>           Cancel my attempt
>         ](https://console.algora.io/api/bounties/clol8c1jf0002l40fe73y1m9q/cancel-attempt)

@punctualprocrastinator I'm cancelling your attempt for now and let's try to find another suitable task for you to contribute!

**Comment by mohanish2504** [comment]
Hey @shahargl @talboren is there any limitation for GraphQL packages I can use?

Sorry texting here, not able to text on Slack. Any other place where we can chat?

**Comment by mohanish2504** [comment]
I tried.

So far I am able to check scopes, add webhooks, fetch issues.
But the template has some issues, due to handlebar formatting.

By any chance you guys have faced this, may be know something I can refer to?
@talboren @shahargl

**Comment by talboren** [comment]
@mohanish2504 wdym by "template"? happy to hop on a call and help you with anything you need

**Comment by mohanish2504** [comment]
not able to text on slack

**Comment by talboren** [comment]
> not able to text on slack

We are working towards fixing that problem together with Slack, sorry for the inconvenience. :(
