### ISSUE TITLE
Add "show deleted" functionality to show alerts that were deleted

### ISSUE THREAD

**Issue by shahargl** [keephq/keep#463]
Expected behavior:
1. An alert was triggered - Keep will show it in the main alerts console.
2. A user deleted the alert
3. Keep will not show the alert in the main alert console, but in another tab - "alert history"

**Comment by talboren** [comment]
This functionality already exists
![CleanShot 2023-11-08 at 12 10 55](https://github.com/keephq/keep/assets/68807791/a7950c02-b1aa-4537-b915-fa57a6f87664)

**Comment by talboren** [comment]
* When deleting an alert it should be marked as "deleted" (in contrast to removing it from the DB, which is what's happening today)
* There should be some UX to show the deleted/archived alerts

**Comment by shahargl** [comment]
closed by @talboren
