### ISSUE TITLE
Error handling in UI is broken (ErrorComponent and ErrorBoundary)

### ISSUE THREAD

**Issue by talboren** [keephq/keep#465]
**Describe the bug**
Error handling in the UI is broken, a simple use case can be when the API is not reachable and we throw the "KeepApiError", the only thing that is shown on the screen is Keep's logo.

**To Reproduce**
1. Take down the API
2. Start the UI
3. Go to localhost:3000

**Expected behavior**
Error should be presented beautifully with all the context that is possible and a clear CTA should be displayed (e.g. "Try Again")

**Screenshots**
![CleanShot 2023-11-08 at 14 30 57](https://github.com/keephq/keep/assets/68807791/79f80dd5-e11c-4561-87a3-d29a50d03fed)

**Comment by TakshPanchal** [comment]
Hey @talboren , I wanted to take this issue. I will look around the code and let you know the solution approach.

**Comment by talboren** [comment]
> Hey @talboren , I wanted to take this issue. I will look around the code and let you know the solution approach.

Perfect @TakshPanchal, thank you! You can reach out to @shahargl who added the ErrorBoundary approach and consult with him.

**Comment by shahargl** [comment]
hey @TakshPanchal , any progress? want me to dive in?

**Comment by ibishal** [comment]
/attempt #465
can i get assigned with it ?

**Comment by 35C4n0r** [comment]
@ibishal is there any update from you, are you still working on this one.

**Comment by TakshPanchal** [comment]
is it possible to discuss this on a meet @shahargl. I have some findings.

**Comment by TakshPanchal** [comment]
I am able to display error to user using error boundry.
![image](https://github.com/keephq/keep/assets/52617262/a9b541f4-7260-4364-b4a4-6a4c82c351d5)

**Comment by ezhil56x** [comment]
@TakshPanchal Are you still working on this?

**Comment by TakshPanchal** [comment]
Yes yes

**Comment by 35C4n0r** [comment]
I don't see any activity, I'm picking this up.

/attempt #465

**Comment by 35C4n0r** [comment]
![image](https://github.com/user-attachments/assets/5008b0a6-ec0c-4784-9d14-38384156f87a)

**Comment by 35C4n0r** [comment]
![image](https://github.com/user-attachments/assets/9c6279a8-49d7-420d-ac30-70f96e0528c0)
