### ISSUE TITLE
Generic webhook needs to be better exposed

### ISSUE THREAD

**Issue by talboren** [keephq/keep#466]
**Is your feature request related to a problem? Please describe.**
Keep has a "generic" webhook mechanism where you can send events to Keep's API and see them in the alerts page.
To see and understand the payload, we have a tab under "Settings" -> "Webhook"

![CleanShot 2023-11-08 at 15 00 58](https://github.com/keephq/keep/assets/68807791/a73dd487-db4e-44ab-9b3f-8d7b0f389cd6)

Today, it's kinda "hidden" that we have this capability and we need to better expose it (either via a dedicated "provider" or via the alerts page) and add documentation about it to the [docs](https://docs.keephq.dev).

**Describe the solution you'd like**
Expose the generic webhook capability better throughout the UI (+better UX) and add documentation about this feature.

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by fivenp** [comment]
I think the webhook could be shown on the provider list (maybe with a special tag to it) so it becomes very obvious for people right away?

**Comment by talboren** [comment]
> I think the webhook could be shown on the provider list (maybe with a special tag to it) so it becomes very obvious for people right away?

Maybe but I'm struggling with the idea on how to show it because:
1. You don't really need to "connect" this provider
2. It works kinda similar to how providers as Prometheus works:
![CleanShot 2023-11-08 at 15 34 39](https://github.com/keephq/keep/assets/68807791/60ed5196-5739-4801-ada0-aa7497e30473)
3. We already have some kind of tag for "Webhook" supporting providers:
![CleanShot 2023-11-08 at 15 35 18](https://github.com/keephq/keep/assets/68807791/040301e3-61a3-4f3d-82ec-5e924fc6b637)

**Comment by fivenp** [comment]
We can easily call it "Incoming webhook" which would make a lot of
questions obsolete :)

**Comment by talboren** [comment]
🤣, I guess we can do something like that and get "another provider"
