### ISSUE TITLE
Create a GitHub action to push workflows from a GitHub repository

### ISSUE THREAD

**Issue by shahargl** [keephq/keep#469]
Read the workflows from GitHub repo

**Comment by talboren** [comment]
This needs https://github.com/keephq/keep/tree/feature/cron-and-cli to be merged

**Comment by shahargl** [comment]
Merged, will start look at this soon :)

**Comment by shahargl** [comment]
Completed - whoever interested - you can use this workflow as an example - https://github.com/keephq/keep/blob/main/.github/workflows/sync-keep-workflows.yml
