### ISSUE TITLE
Invalid token type. Token must be a <class 'bytes'>

### ISSUE THREAD

**Issue by talboren** [keephq/keep#475]
When we do not provide token

**Comment by mohanish2504** [comment]
Please share more details, are you talking about ? verify_bearer_token

**Comment by talboren** [comment]
@mohanish2504 I'm not sure exactly where does this happen but if you just start your API locally (with auth using `KEEP_MULTI_TENANT=true`) and send a request to the API without a token, you will receive this error.
See https://api.keephq.dev/providers as an example.
