### ISSUE TITLE
Community's Slack is malfunctioning

### ISSUE THREAD

**Issue by talboren** [keephq/keep#478]
We are sorry for the inconvenience and we're working with Slack in order to resolve the issue.

<img width="484" alt="CleanShot 2023-11-09 at 18 50 35@2x" src="https://github.com/keephq/keep/assets/68807791/c99a9aec-9397-4e6b-acd2-99c7c6fd21ed">

**Comment by mohanish2504** [comment]
seem to be an issue still?

**Comment by mohanish2504** [comment]
is there anywhere else we can communicate? discord?

**Comment by talboren** [comment]
@mohanish2504 we are trying to reach out to the Slack team once again. If this won't yield anything, we will probably open an alternative Discord for Keep's community.
Sorry for all the mess :(
