### ISSUE TITLE
Missing ntfy as notification provider

### ISSUE THREAD

**Issue by cmeis** [keephq/keep#48]
I think adding [ntfy](https://ntfy.sh/) as a notification provider would be awesome.

ntfy is an open source free notification service to send notification to you phone/desktop.
You can use a public free server instance, or easily self-host it.
Notifications can include text, images, attachments, action buttons to respond to notifications etc.

**Comment by talboren** [comment]
On it ⭐️

**Comment by talboren** [comment]
@cmeis I've added the HTTP provider which can be used to publish to ntfy, see [simple_http_request_ntfy.yml](https://github.com/keephq/keep/blob/main/examples/alerts/simple_http_request_ntfy.yml)
