### ISSUE TITLE
Split keepcli and keep commands

### ISSUE THREAD

**Issue by shahargl** [keephq/keep#497]
Currently, there are two different usages for keep cli:
 1. keepcli - Consume Keep API's (get alerts, workflows, etc)
2. keep - Start the server (`keep api`)

The problem is that if I want only use `keepcli` (for example for applying a workflow as part of my ci/cd) the docker image of keep contains all keep server dependencies (boto3, gcloud, etc).

The solution is to break it into two separate packages - `keep` and `keepcli` where `pip install keep` will install the full server and `pip install keepcli` will just install a lean `cli.py` that consume the APIs.

**Comment by devblin** [comment]
@shahargl this looks good, but I saw that `keepcli` imports various functions from keep /api, /workflowmanager etc, so the keep /cli should be an 
standalone executable right?
