### ISSUE TITLE
Kibana Watcher - Add Webhook integration in Kibana Watcher Json Scripts

### ISSUE THREAD

**Issue by Sup3rJ** [keephq/keep#505]
Kibana Watcher allow to create scripts based on some filters to send alerts. For example, errors 5xx in the last 10 minutes. In these scripts it's possible to add a custom webhook to send this alert:

Example of a webhook configuration:

"webhookCustom": {
   "webhook": {
    "scheme": "https",
    "host": "[n8n.com](http://n8n.com/)",
    "port": 443,
    "method": "post",
    "path": "/webhook/df65",
    "params": {
     "title": "Errors 5xx - APP",
     "sourceRef": """ - Check Kibana https:///cf4123b0-215ae""",
     "description": "-"
    },
    "headers": {},
    "body": "-"
   }
  }
 }
 }

Will be great to push these alerts to keep.

**Comment by talboren** [comment]
Hey @Sup3rJ, I created https://github.com/keephq/keep/pull/515 following your conversation with @shahargl.
I'm trying to understand whether we're speaking about the same thing -- I developed the Kibana provider based on [Kibana 8.1 alerting](https://www.elastic.co/guide/en/kibana/current/alerting-getting-started.html) and [connectors](https://www.elastic.co/guide/en/kibana/current/action-types.html), are we referring to the same thing?
I'll soon add the documentation on how to create the API key, etc.

**Comment by talboren** [comment]
> Hey @Sup3rJ, I created #515 following your conversation with @shahargl. I'm trying to understand whether we're speaking about the same thing -- I developed the Kibana provider based on [Kibana 8.1 alerting](https://www.elastic.co/guide/en/kibana/current/alerting-getting-started.html) and [connectors](https://www.elastic.co/guide/en/kibana/current/action-types.html), are we referring to the same thing? I'll soon add the documentation on how to create the API key, etc.

Here's an alert for example, FWIW
![CleanShot 2023-11-19 at 17 09 54](https://github.com/keephq/keep/assets/68807791/7b1fa482-cf37-4194-9386-f80f15d77f03)

**Comment by talboren** [comment]
I've added support for Kibana Watcher as well.
Please refer to the docs and if it's not clear I'll gladly help with anything :) https://docs.keephq.dev/providers/documentation/kibana-provider

**Comment by Sup3rJ** [comment]
Hello @talboren 

Well i don't think it's the same thing. In Kibana you can create Kibana Watcher based on scripts.

You can add a webhook action in the bottom of the script. 

Something like this:
  "actions": {
    "webhookZendesk": {
      "webhook": {
        "scheme": "https",
        "host": "keephq/alerts/event/kibana",
        "port": 8080,
        "method": "post",
        "params": {
          "title": "5xx Errrors",
          "sourceRef": "",
          "description": "Errors 5xx"
        },
        "headers": {},
        "body": "{{#toJson}}ctx.payload{{/toJson}}"
      }
    }
  }
}

**https://www.elastic.co/guide/en/kibana/current/watcher-ui.html**

**Comment by talboren** [comment]
> Hello @talboren ! Thanks a lot for your work!
> 
> Well i don't think it's the same thing. In Kibana you can create Kibana Watcher based on scripts.
> 
> You can add a webhook action in the bottom of the script.
> 
> Something like this: "actions": { "webhookZendesk": { "webhook": { "scheme": "https", "host": "keephq/alerts/event/kibana", "port": 8080, "method": "post", "params": { "title": "5xx Errrors", "sourceRef": "", "description": "Errors 5xx" }, "headers": {}, "body": "{{#toJson}}ctx.payload{{/toJson}}" } } } }
> 
> **https://www.elastic.co/guide/en/kibana/current/watcher-ui.html**

> I've added support for Kibana Watcher as well.

Taken care of that as well :) LMK if I can help you get it connected.

**Comment by Sup3rJ** [comment]
How should i setup that webhhook part in my script to send to keep?

**Comment by talboren** [comment]
> How should i setup that webhhook part in my script to send to keep?

There are 2 options:
1. Generate an API key as described in the docs I shared and let Keep do the magic
2. I can write a short documentation on how to manually add Keep as an action.


Let me know what do you prefer.

**Comment by Sup3rJ** [comment]
I prefer push alerts. This kibana watchers runs every 10 minutes and if they met the conditions they send the alert to the webhook. If i set an API it will pull eveything correct?

**Comment by talboren** [comment]
> I prefer push alerts. This kibana watchers runs every 10 minutes and if they met the conditions they send the alert to the webhook. If i set an API it will pull eveything correct?

It will just iterate over your watches and add keep as an action by itself, automatically. Then, every 10 minutes it’ll be pushed to Keep

**Comment by Sup3rJ** [comment]
Oh it sounds great! Let me test it out! But great work! Awesome!

**Comment by talboren** [comment]
> Oh it sounds great! Let me test it out! But great work! Awesome!

Let me know if I can assist with anything 💪🏼

**Comment by Sup3rJ** [comment]
Hello @talboren ! How are doing today?

Can you show me how to set the action manually directly in the script? 
Example of action in script.

  "actions": {
    "webhookkeep": {
      "webhook": {
        "scheme": "https",
        "host": "",
        "port": ,
        "method": "post",
        "params": {
          "title": "Errors 503",
          "sourceRef": "Errors 5xxx",
          "description": "Errors 5xx"
        },
        "headers": {},
        "body": "{{#toJson}}ctx.payload{{/toJson}}"
      }
    }
  }
}

**Comment by talboren** [comment]
Absolutely, here's the example from the mock watcher alert Keep has installed for me:
```json
"actions": {
  "keep-keep": {
      "webhook": {
          "scheme": "https",
          "host": "1b8f-77-137-44-66.ngrok-free.app",
          "port": 443,
          "method": "post",
          "path": "/alerts/event/kibana",
          "params": {},
          "headers": {},
          "auth": {
              "basic": {
                  "username": "keep",
                  "password": "::es_redacted::"
              }
          },
          "body": "{\"payload\": {{#toJson}}ctx{{/toJson}}, \"status\": \"Alert\"}"
      }
  }
}
```

Let me know if something doesn't work/if you want me to give you the exact "Dev Tools" commands to execute:
![CleanShot 2023-11-21 at 17 16 52](https://github.com/keephq/keep/assets/68807791/9fb266c4-16ba-42dc-80a0-08cbe9f3fd02)

**Comment by Sup3rJ** [comment]
400 - Failed to handle the event Bad Request.
Something is not passing correctly. Need to investigate from my side.

**Comment by talboren** [comment]
> 400 - Failed to handle the event Bad Request. Something is not passing correctly. Need to investigate from my side.

Here's a Dev Tool example if it helps:

```
# Get Watches
GET /_watcher/_query/watches/

# Update watch based on watch _id and the fields (trigger, condition, transform, actions) taken from the watch ^
PUT _watcher/watch/af390eb2-fa9f-470c-af99-420356ac58bb
{
  "trigger": {
          "schedule": {
            "interval": "1m"
          }
        },
        "input": {
          "search": {
            "request": {
              "search_type": "query_then_fetch",
              "indices": [
                "logs-*"
              ],
              "rest_total_hits_as_int": true,
              "body": {
                "size": 0,
                "query": {
                  "bool": {
                    "filter": {
                      "range": {
                        "@timestamp": {
                          "gte": "{{ctx.trigger.scheduled_time}}||-5m",
                          "lte": "{{ctx.trigger.scheduled_time}}",
                          "format": "strict_date_optional_time||epoch_millis"
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        },
        "condition": {
          "script": {
            "source": "if (ctx.payload.hits.total > params.threshold) { return true; } return false;",
            "lang": "painless",
            "params": {
              "threshold": 1
            }
          }
        },
        "transform": {
          "script": {
            "source": "HashMap result = new HashMap(); result.result = ctx.payload.hits.total; return result;",
            "lang": "painless",
            "params": {
              "threshold": 1
            }
          }
        },
        "actions": {
          "keep-keep": {
            "webhook": {
              "scheme": "https",
              "host": "1b8f-77-137-44-66.ngrok-free.app",
              "port": 443,
              "method": "post",
              "path": "/alerts/event/kibana",
              "params": {},
              "headers": {},
              "auth": {
                "basic": {
                  "username": "keep",
                  "password": "YOUR_API_KEY"
                }
              },
              "body": """{"payload": {{#toJson}}ctx{{/toJson}}, "status": "Alert"}"""
            }
          }
        }
}
```

https://github.com/keephq/keep/assets/68807791/c72efc90-1ed0-43d9-b7ba-ab61c9bd5474

**Comment by talboren** [comment]
@Sup3rJ let me know if there's anyway I can further help. I can hop on a call if that makes sense.
