### ISSUE TITLE
Templatization of our docker-compose files 

### ISSUE THREAD

**Issue by talboren** [keephq/keep#531]
Today we maintain 4 different docker-compose files:

- docker-compose.yml
- docker-compose.dev.yml
- docker-compose-with-otel.yaml
- docker-compose-with-auth.yml

The main difference between them is either extra services or different environment variables.
We need to maintain 1 "baseline" docker-compose file that other docker-compsoe files inherit and extend.

**Comment by mohanish2504** [comment]
will like to work on this please assign this to me

**Comment by mohanish2504** [comment]
@talboren @shahargl apologizes for being late on this.
I hope no one working on this currently as I have some time to work on this.

**Comment by talboren** [comment]
@mohanish2504 happy to have you contribute that :)
