### ISSUE TITLE
Change the bigquery provider to authenticate with file

### ISSUE THREAD

**Issue by shahargl** [keephq/keep#541]
Take a look at GKE provider for reference

**Comment by b4s36t4** [comment]
@talboren I see bigquery provider is using the file related function only, https://cloud.google.com/python/docs/reference/aiplatform/latest/google.cloud.aiplatform_v1beta1.services.model_service.ModelServiceClient#google_cloud_aiplatform_v1beta1_services_model_service_ModelServiceClient_from_service_account_json

GKE provider is using this https://cloud.google.com/python/docs/reference/aiplatform/latest/google.cloud.aiplatform_v1beta1.services.model_service.ModelServiceClient#google_cloud_aiplatform_v1beta1_services_model_service_ModelServiceClient_from_service_account_info. Can you check the descirption again please?

**Comment by b4s36t4** [comment]
If I understand things correctly, user uploads their json file in UI (currently works for GKE provider) in which the code takes it as JSON and do the auth using `from_service_account_info` whereas for the big-query the auth is currently happening with json file (which does require json path) so we need to update the bigquery to accept the file (in UI) same as we do with GKE right?

**Comment by talboren** [comment]
> If I understand things correctly, user uploads their json file in UI (currently works for GKE provider) in which the code takes it as JSON and do the auth using `from_service_account_info` whereas for the big-query the auth is currently happening with json file (which does require json path) so we need to update the bigquery to accept the file (in UI) same as we do with GKE right?

Sounds right!
