### ISSUE TITLE
add scopes to OpsGenie provider

### ISSUE THREAD

**Issue by shahargl** [keephq/keep#543]

**Comment by surendrasomai** [comment]
@talboren , Can you provide me detail ?

**Comment by talboren** [comment]
@surendrasomai you can take a look at Datadog Provider/Grafana Provider/Dynatrace Provider for reference on how to implement the `ProviderScopes` and `validate_scopes()` functions.
If it's still not 100% clear, I'd be happy to elaborate further.

**Comment by sakshambp** [comment]
How do we test the change @talboren what is success criteria?

**Comment by sakshambp** [comment]
Also do we know what all scopes to add?

**Comment by TakshPanchal** [comment]
Hey @talboren, I searched for the API endpoint to get permissions, but I couldn't find any! Lastly, we need `userid` or `username` to [get user role](https://docs.opsgenie.com/docs/user-api#get-user).

**Comment by TakshPanchal** [comment]
> Hey @talboren, I searched for the API endpoint to get permissions, but I couldn't find any! Lastly, we need `userid` or `username` to [get user role](https://docs.opsgenie.com/docs/user-api#get-user).

@shahargl can you help me here 😅

**Comment by shahargl** [comment]
@TakshPanchal couldn't find easy way to do it :( what I suggest is that you'll try to delete it after creating (although delete permissions are higher). let's go with it and wait for user feedback.

**Comment by ezhil56x** [comment]
> @TakshPanchal couldn't find easy way to do it :( what I suggest is that you'll try to delete it after creating (although delete permissions are higher). let's go with it and wait for user feedback.

I have implemented a way to validate the users on the next commit. Can you review my pull request
