### ISSUE TITLE
GitHub stars provider won't work from UI 

### ISSUE THREAD

**Issue by shahargl** [keephq/keep#544]
"sub providers" are not supported in the UI so if you use the github stars workflow in the UI it won't work

**Comment by onyedikachi-david** [comment]
/attempt #544

Please assign

**Comment by Matvey-Kuk** [comment]
@onyedikachi-david assigned!

**Comment by sc231997** [comment]
@Matvey-Kuk is there any video or steps to reproduce this issue?

**Comment by knight-95** [comment]
@shahargl @Matvey-Kuk Can you please provide the brief description of what is expected and what is currently happening, I would like to work on this issue

**Comment by Matvey-Kuk** [comment]
Payout for this bounty will be executed via GitHub Sponsors, not via Algora. Please activate https://github.com/sponsors/accounts for your account to receive the payout, sorry for the inconvenience

**Comment by AkashJana18** [comment]
is this issue solved?
If not i would like to work on it

**Comment by talboren** [comment]
@AkashJana18 I think this is no longer relevant at the moment. Thank you for trying! :)
