### ISSUE TITLE
Alerts assignee

### ISSUE THREAD

**Issue by talboren** [keephq/keep#559]
Allow one to assign alerts to user / get the assignee from the provider itself.

**Comment by Sup3rJ** [comment]
@talboren Just a few things to add 😀

- Is it possible to assign the alerts ONLY to the username that's logged. So if i logged as "john" i can ONLY assign to me. For example, if i click the assign button, it will automatically assign to john(ex: the name should appear on the button). 

- If i delete the Alert without assign, it will assign it automatically to the user that deleted it. In this case, john.

- Also, can t have a list of names to assign nor the user can remove the assign. When its assigned to someone, the ONLY way to change it, is if other user clicked that button and will be assign to that new user.


Let me know if its confusing...😅

**Comment by talboren** [comment]
> @talboren Just a few things to add 😀
> 
> * Is it possible to assign the alerts ONLY to the username that's logged. So if i logged as "john" i can ONLY assign to me. For example, if i click the assign button, it will automatically assign to john(ex: the name should appear on the button).
> * If i delete the Alert without assign, it will assign it automatically to the user that deleted it. In this case, john.
> * Also, can t have a list of names to assign nor the user can remove the assign. When its assigned to someone, the ONLY way to change it, is if other user clicked that button and will be assign to that new user.
> 
> Let me know if its confusing...😅

@Sup3rJ thanks for the comments :) I think it makes sense although I would imagine that once we have RBAC (e.g. a user is admin), assignees can be "overridden" if you have sufficient permissions. WDYT?

**Comment by Sup3rJ** [comment]
Yes with rbac, it makes sense  to change it if the admin want. But maybe it will be interesting to have an history inside the alert of the changes even made by the admin.

**Comment by talboren** [comment]
> Yes with rbac, it makes sense to change it if the admin want. But maybe it will be interesting to have an history inside the alert of the changes even made by the admin.

Makes sense. I'll take consideration of it when implementing. I think it is also interesting for alert deletion (the history part)
