### ISSUE TITLE
Alert enrichment history log

### ISSUE THREAD

**Issue by talboren** [keephq/keep#565]
Whenever we add/remove alert enrichment, we should keep a log of what was changed so users can see the history of enrichments.

For example, when assigning an alert to someone or when deleting/restoring an alert.

Users should be able to open a view (modal?) of the history change log.

**Comment by sergtl** [comment]
I'd like to work on this issue

**Comment by 35C4n0r** [comment]
Cancelling my attempt, It's already assigned.

**Comment by talboren** [comment]
@sergtl @Matvey-Kuk I think this is no longer relevant, I'm sorry for the confusion. It was implemented as part of https://github.com/keephq/keep/pull/1378

Can I go on to close this issue?

**Comment by sergtl** [comment]
@talboren Sure, thanks for the heads up

**Comment by Matvey-Kuk** [comment]
Sorry, I didn't notice it's already implemented 🙏

**Comment by Pious1020** [comment]
is this issue closed?
