### ISSUE TITLE
Providers page responsiveness is buggy 

### ISSUE THREAD

**Issue by talboren** [keephq/keep#570]
**Describe the bug**
Providers page behaves weird on different sized screens and is not properly responsive. 

**To Reproduce**
1. Go to https://platform.keephq.dev
2. Change the size of the screen (simple resizing)
4. See weird behavior of the provider tiles

**Expected behavior**
Providers page should be responsive to all screen sizes. We should have a fixed number of items per line regardless to the size of the screen.

**Screenshots**
![CleanShot 2023-11-27 at 10 10 22](https://github.com/keephq/keep/assets/68807791/be6a6812-1375-4878-a093-966ad7c9894e)

**Desktop (please complete the following information):**
Not Applicable

**Smartphone (please complete the following information):**
Not Applicable

**Additional context**
Not Applicable

**Comment by D-Lite** [comment]
Hi @talboren , can I work on this?

**Comment by talboren** [comment]
https://github.com/keephq/keep/assets/68807791/03379be7-3cca-4fcf-a5f9-edd9289a30f1
