### ISSUE TITLE
Keep CLI doesn't work well with async/pusher 

### ISSUE THREAD

**Issue by shahargl** [keephq/keep#576]
Moving to pusher/async broke how the CLI plays with `get_alerts`.

**Comment by talboren** [comment]
@shahargl can you share more details? 🙏🏼

**Comment by shahargl** [comment]
Yea so the Keep CLI used get_alerts to get all alerts, but now get_alerts returns only pushed alerts, and the pulled alerts are sent on the websocket. 

With the CLI, I can't implement that (it's much harder and weird behavior for the one who uses the CLI to get async alerts).

Basically, I'm fixing it by allowing the old get_alerts, I'll open the PR soon
