### ISSUE TITLE
Add Zenduty Provider

### ISSUE THREAD

**Issue by zenbeam** [keephq/keep#58]
**Is your feature request related to a problem? Please describe.**
Zenduty is an incident response and issue management platform that could be plugged into Keep to route incidents.

**Describe the solution you'd like**
A Zenduty provider similar to other out-of-the-box providers available right now

**Comment by shahargl** [comment]
Thanks @zenbeam, will start and update asap

**Comment by shahargl** [comment]
Hey @zenbeam,

I've added the Zenduty provider on this PR - https://github.com/keephq/keep/pull/62
You can try it using the `db_disk_space_zenduty.yml` alert example.

Let me know if I can help more.

**Comment by zenbeam** [comment]
> Hey @zenbeam,
> 
> I've added the Zenduty provider on this PR - #62 You can try it using the `db_disk_space_zenduty.yml` alert example.
> 
> Let me know if I can help more.

Will surely check it out and let you know if I have any feedback, really appreciate your team's swiftness, godspeed!

**Comment by shahargl** [comment]
Happy to help. Let me know if anything else is missing.

**Comment by shahargl** [comment]
@zenbeam - hey! ever managed to play with Keep? would happy to have any feedback!

**Comment by zenbeam** [comment]
> @zenbeam - hey! ever managed to play with Keep? would be happy to have any feedback!

Did have a look @shahargl, will 'keep' you guys posted on any feedback I have as I explore further :)
