### ISSUE TITLE
Provider Creation Fails

### ISSUE THREAD

**Issue by adideutsch** [keephq/keep#614]
**Describe the bug**
Using onprem helm installation, I tried to connect Keep to OpsGenie and got this error:
"Scopes are invalid for opsgenie: undefined"

Please note - I changed the title and removed OpsGenie since it happened to me with slack as well. So I think it is a wider issue than just opsgenie. 

**To Reproduce**
1. Go to Providers
2. Click on OpsGenie, create new provider
3. Fill in title and api key , click on create

**Expected behavior**
Provider created
**Screenshots**
![image](https://github.com/keephq/keep/assets/8726696/4fe14d5e-4a5c-49a8-a15a-2bdaee778cd5)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Using helm onprem installation

**Comment by shahargl** [comment]
Gonna look at it 👀
