### ISSUE TITLE
opsgenie provider: add close alert and comment on alert

### ISSUE THREAD

**Issue by shahargl** [keephq/keep#618]

**Comment by b4s36t4** [comment]
Would love to work on this, can I get more info about documentation etc?

**Comment by rmaceissoft** [comment]
@b4s36t4 are you still working on this? Otherwise I can take it
cc: @shahargl

**Comment by shahargl** [comment]
For sure! I’ll hopefully merge your other PR tomorrow @rmaceissoft

**Comment by rmaceissoft** [comment]
Here are a couple of questions regarding this matter:

1. Is it possible to use an opsgenie API Key from a trial account? I attempted to do so, but encountered an error (refer to the video below). I'm curious if having a trial account might be the cause.
https://www.loom.com/share/52ceac2abacd44a3ad9c912de96aacc6

2. Should the scopes of the opsgenie provider align with the access rights? With the upcoming support for "close alert," there seems to be a discrepancy where the scope is named `opsgenie:create`, yet the actual permission is listed as `Create and update`. This could raise some confusion.
![Screen Shot 2024-01-22 at 10 18 26](https://github.com/keephq/keep/assets/476427/601baa53-99a9-45b0-b676-7711c1e6f74d)

**Comment by shahargl** [comment]
Hey @rmaceissoft! Thanks for your work!

1. So it looks like the API key is correct (403) but doesn't have the necessary permission (`apiKey is valid but the apiKey cannot do this operation because of permissions`)
2. I think its also align with (1) - there is opsgenie API key, and opsgenie integration API key which aren't the same. You should have the second (opsgenie integration API key). this is somewhat documented in Keep's docs (https://docs.keephq.dev/providers/documentation/opsgenie-provider#connecting-with-the-provider)

How to create API integration - https://support.atlassian.com/opsgenie/docs/create-a-default-api-integration/
How to get an API Key for integration - https://community.atlassian.com/t5/Opsgenie-questions/OpsGenie-API-Create-alert-Authentication-problem/qaq-p/1531047

Let me know if that's help

**Comment by rmaceissoft** [comment]
@shahargl that worked, thanks for pointing that out. I went ahead and pushed a [PR](#744)

A couple of questions:
1. What do you think about each provider method having its own scope? 
`close_alert` -> `opsgenie:close`
`comment_alert` -> `opsgenie:comment`

2. Should the docs be updated as part of this PR?

**Comment by shahargl** [comment]
(1) that’s interesting, I need to think about the UX of that in the UI, do you have any thoughts on that?
(2) that would be amazing
