### ISSUE TITLE
Add mongodb as a provider

### ISSUE THREAD

**Issue by vijay-jangir** [keephq/keep#624]
**Is your feature request related to a problem? Please describe.**
I'm looking to read data from mongodb in my workflow.

**Describe the solution you'd like**
In my workflow, i have few configurable parameters which are stored in mongodb. I want to fetch them against an evernt (like trigger interval, or email address etc) and use in workflow

**Describe alternatives you've considered**
as our configuraiton needs to be externalized, i'm not able to think of any other alternative. I'm open for discussion regarding this.

**Additional context**

**Comment by rishi-raj-jain** [comment]
@shahargl 

We want to connect mongodb using `pymongo` https://www.w3schools.com/python/python_mongodb_create_db.asp,  right?

**Comment by shahargl** [comment]
yea you can use `pymongo` for that. notice that you need also `scopes` and `validate_scopes` (you can see datadog provider for example). also note that this should support self hosted mongo so the URL is also necessary.

**Comment by rishi-raj-jain** [comment]
Awesome, that sounds great. I think the URL part is already handled by the below whether it's localhost or a production URL.

```
myclient = pymongo.MongoClient("mongodb://localhost:27017/")
```

> you need also scopes and validate_scopes

I did see the datadog provider but that seems too heavy to parse, do we have a guide on what are these scopes and validate_scopes?

**Comment by shahargl** [comment]
So look at `mysql_provider`, much easier

**Comment by rishi-raj-jain** [comment]
Thanks for the refernece! Makes sense now

**Comment by rishi-raj-jain** [comment]
@shahargl 

Can I have the bounty?

**Comment by rishi-raj-jain** [comment]
@shahargl

Can I be awarded the bounty?

**Comment by rishi-raj-jain** [comment]
@shahargl 

Can i be awarded the bounty?
