### ISSUE TITLE
Create presets for each user

### ISSUE THREAD

**Issue by Sup3rJ** [keephq/keep#640]
The feature to create presets it's awesome but right now if i create a preset, all users have the same presets. I think it will be great that each user have their own presets. This way each user can choose the alerts they want to see and have their own customize dashboard.

**Comment by talboren** [comment]
This one requires a little UX thinking. Will update once we have a thought on how to implement this to get your feedback @Sup3rJ! Thanks for the issue.

**Comment by talboren** [comment]
### What needs to be done
1. Presets are currently kept in localStorage -> should move to API
2. One should be able to save Preset as a `Global` vs. `Private` (only available for the current user)
3. Columns order and visibility should be kept under the new created Preset API (it's currently saved in the localStorage as well, respective to the selected preset)

**Comment by MayorChristopher** [comment]
Can I take this up / #640

**Comment by talboren** [comment]
@mohanish2504 @MayorChristopher lmk who takes this folks

**Comment by mohanish2504** [comment]
Hey @talboren I have already started working on this. May I please take this up?

**Comment by MayorChristopher** [comment]
Let me take it @talboren

**Comment by mohanish2504** [comment]
Since I have added my attempt first, @MayorChristopher @talboren I should give it a shot?
@talboren please pitch in and lmk.

**Comment by talboren** [comment]
> Since I have added my attempt first, @MayorChristopher @talboren I should give it a shot? @talboren please pitch in and lmk.

Perhaps some OSS collaboration? 🥹 one can have the BE and one can have the FE, you can finish faster and share the bounty. Wdyt folks?

**Comment by mohanish2504** [comment]
Sounds good to me, since I am already familiar with the backend part it
will be quick for me!
Can you take up the FE part please  @MayorChristopher
<https://github.com/MayorChristopher>?

**Comment by talboren** [comment]
@MayorChristopher let me know if this works.

**Comment by MayorChristopher** [comment]
@mohanish2504 how is it going, I'm thinking on how to go about the FE

**Comment by MayorChristopher** [comment]
@talboren thank you, I'm fine with it

**Comment by talboren** [comment]
> @mohanish2504 how is it going, I'm thinking on how to go about the FE

@MayorChristopher how about joining our [Slack](https://slack.keephq.dev) and I can open a channel for the 3 of us to chat about it. @mohanish2504 is already there!

**Comment by MayorChristopher** [comment]
@ta

> > @mohanish2504 how is it going, I'm thinking on how to go about the FE
> 
> @MayorChristopher how about joining our [Slack](https://slack.keephq.dev) and I can open a channel for the 3 of us to chat about it. @mohanish2504 is already there!

Great thank you, I will expecting to join

**Comment by MayorChristopher** [comment]
> > @mohanish2504 how is it going, I'm thinking on how to go about the FE
> 
> @MayorChristopher how about joining our [Slack](https://slack.keephq.dev) and I can open a channel for the 3 of us to chat about it. @mohanish2504 is already there!

@talboren, I'm so sorry, I'm having some technical issues setting up slack. Don't know if we could continue our conversation here.
How would want the UI to be, for each presets ?

**Comment by mohanish2504** [comment]
@talboren it seems @MayorChristopher is busy on #804 can I complete rest meanwhile?

**Comment by MayorChristopher** [comment]
I was assigned, and I'm on it, its a critical one, a UX thinking one, i
wouldn't just rush it, i will commit soon.

**Comment by 35C4n0r** [comment]
👍🏻 /attempt #640
