### ISSUE TITLE
Getting alerts loading freeze

### ISSUE THREAD

**Issue by Sup3rJ** [keephq/keep#641]
Sometimes when the page is refreshed or we change to providers and come back to alerts, the getting alerts freeze in the loading.

Need to refresh again to get back to normal. Sometimes it takes 3 or 4 refreshes to return to normal behavior.

It seems the pusher message (the async notifying system) gets before the page completes on loading.

![image](https://github.com/keephq/keep/assets/45700493/97d73012-f496-40b0-b273-8d2e162cb4d9)

**Comment by talboren** [comment]
Fixed as part of #643
