### ISSUE TITLE
Chart on openshift leaves webhook secret upon deletion

### ISSUE THREAD

**Issue by momoadc** [keephq/keep#646]
**Describe the bug**
Keep creates a secret called keep-webhook for use as a password for prometheus alert-manager integration
However, upon deletion of the chart (at least on openshift), this secret remains, and when re-installing the chart on the same namespace keep gets an error because it tries to generate a secret with the exact same name
(another suggestion is to save this information not in plain-text)

**To Reproduce**
install the chart on an openshift namespace, open the prometheus provider window, and re-install the chart

**Expected behavior**
an un-install of the chart should also delete the secret, or the code can delete it itself upon regeneration

**Comment by shahargl** [comment]
closed by https://github.com/keephq/keep/pull/647
