### ISSUE TITLE
Missing Telegram Provider

### ISSUE THREAD

**Issue by sonovice** [keephq/keep#66]
It would be great to get alert messages on telegram. This would probably involve creating a bot and passing the bot token to such a new provider.

**Comment by shahargl** [comment]
Hey @sonovice, will have a look soon. Can you meanwhile elaborate on your use case? Are you going to use Keep? 😄

**Comment by sonovice** [comment]
Thanks for looking into it! I have a couple of services running on a VPS and would like to be notified in case one of them goes down. Telegram simultaneously pushes messages to basically all my devices (phone, tablet, notebook etc.) which maximizes the chances of me getting any alerts ASAP. So with telegram support, I will most probably build alerting with Keep.

**Comment by shahargl** [comment]
Hey @sonovice,
I've added telegram provider for you to use :)
You can look at https://github.com/keephq/keep/pull/67
<img width="281" alt="image" src="https://user-images.githubusercontent.com/12069200/221124666-64224188-2685-4613-8e0d-e5aba2f8f4bd.png">

You'll need to create a bot (see attached docs) and pretty much that's it.
I've added `examples/alert/db_disk_space_telegram.yml` as a fully working example.

Please let me know for any bugs/problems.

**Comment by sonovice** [comment]
Wait, what? :laughing: 
Thank you so much for the lightning speed response! Will incorporate Keep into my pipeline first thing on Monday.

**Comment by shahargl** [comment]
Awesome!
Let me know for any challenge you have so I'll be able to help.

**Comment by shahargl** [comment]
and btw - let me know how you are going to deploy it (schedule/automate) because we are still early there and we want to expand our deployments method, so we can help there too.

**Comment by sonovice** [comment]
It will have to be part of a docker-compose structure. I expect Keep to periodically "ping" some REST endpoints to check their health.

**Comment by shahargl** [comment]
so you'll use Keep's Dockerfile? 
and we are thinking to add some flag that will poll the alert every interval, will it help you?
let's say something like
```
keep run --au alert.yaml --interval 1m
```
(you probably can achieve same results by using crontab but maybe it'll be easier)

**Comment by talboren** [comment]
@shahargl @sonovice —interval is already in place :) would love to help anyhow. 
@sonovice I wrote the simple HTTP provider so if any modifications are needed, ping me and I’ll be glad to do them.

**Comment by sonovice** [comment]
Yes, that would indeed help and would be slightly more convenient than even a simple cronjob.

**Comment by sonovice** [comment]
One thing that comes to mind: If one of my services fails, I want one message, not a flood of them at reach interval. Is this somehow supported or would I need to kill the keep process on my own?
Also: Is it possible to define several alerts in one yaml?

**Comment by shahargl** [comment]
> One thing that comes to mind: If one of my services fails, I want one message, not a flood of them at each interval. Is this somehow supported or would I need to kill the keep process on my own?

So let's say you wrote some yaml that monitors if process X is down and let's say that process X is really down - what behavior do you want? that the first time the ping failed, keep will trigger alert, and then it'll stop alerting until the process is up again?

> Also: Is it possible to define several alerts in one yaml?
Yes, you can use https://github.com/keephq/keep/blob/main/examples/alerts/db_disk_space_several_alerts_in_one_yaml.yml
as reference

**Comment by sonovice** [comment]
> So let's say you wrote some yaml that monitors if process X is down and let's say that process X is really down - what behavior do you want? that the first time the ping failed, keep will trigger alert, and then it'll stop alerting until the process is up again?

Yes, maybe with an optional message if the service is back online. But that could be a second alert working in basically the same way.

> Yes, you can use https://github.com/keephq/keep/blob/main/examples/alerts/db_disk_space_several_alerts_in_one_yaml.yml as reference

Thanks!

**Comment by shahargl** [comment]
I've created a PR with adding state so you'll be able to throttle alert so it's easy to implement what you need.
It's bunch of code so @talboren will get to review it on Sunday.

**Comment by sonovice** [comment]
@shahargl Any news on the state PR? (No pressure, just curious.)

**Comment by shahargl** [comment]
It’s already merged! I’ve added docs and example. Give it a try and let me know if it fit your needs! @sonovice
