### ISSUE TITLE
Unable to Launch Keep  with quickstart docker compose commands provided in README

### ISSUE THREAD

**Issue by avaidhyajc** [keephq/keep#674]
**Describe the bug**
I followed this link to launch Keep on my MAC M1 system : 
https://github.com/keephq/keep?tab=readme-ov-file#spinning-up-keep-with-docker-compose

However launch failed with an error 
```
open /Users/xxx/go/src/github.com/TheJumpCloud/keephq/docker-compose.common.yml: no such file or directory
```

**To Reproduce**
1. Go to https://github.com/keephq/keep?tab=readme-ov-file#spinning-up-keep-with-docker-compose
2. Try installing with the mentioned bash commands

**Expected behavior**
Keep Container is launched , up and running

**Screenshots**
```
--2024-01-02 12:11:20--  https://raw.githubusercontent.com/keephq/keep/main/docker-compose.yml
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 2405:200:1607:2820:41::36, 185.199.108.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|2405:200:1607:2820:41::36|:443... failed: Operation timed out.
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 690 [text/plain]
Saving to: ‘docker-compose.yml’

docker-compose.yml                                    100%[=======================================================================================================================>]     690  --.-KB/s    in 0s

2024-01-02 12:12:35 (16.0 MB/s) - ‘docker-compose.yml’ saved [690/690]

open /Users/xxx/go/src/github.com/TheJumpCloud/keephq/docker-compose.common.yml: no such file or directory
```

**Desktop (please complete the following information):**
 - OS: MAC
 - Version NA

**Additional context**
Possible breakage from https://github.com/keephq/keep/pull/651

This also breaks the core documentation  https://docs.keephq.dev/development/getting-started#docker-compose
Pls suggest a workaround

**Comment by talboren** [comment]
Hey @avaidhyajc, thank you for the issue! Please see https://github.com/keephq/keep/pull/668 as it addresses the issue. 
we’ve made several changes to the way our compose files are structured so this is the reason. You can follow the instructions on the PR or shortly wait for the revised version :)

**Comment by talboren** [comment]
Closed at https://github.com/keephq/keep/pull/695
