### ISSUE TITLE
Deleted Group Rules

### ISSUE THREAD

**Issue by Sup3rJ** [keephq/keep#685]
When i create a group rule and then i delete it, if i refresh the page,  the group rule alert appears again in feed. I built several group rules and delete them all. When i refresh the page they all appear again in feed.

**Comment by talboren** [comment]
> When i create a group rule and then i delete it, if i refresh the page, the group rule alert appears again in feed. I built several group rules and delete them all. When i refresh the page they all appear again in feed.

@Sup3rJ just to make sure, when deleting an "Group Alert", you'd like to see the alerts connected with that rule disappear from the alerts feed?

**Comment by Sup3rJ** [comment]
I think maybe the alerts should stay and delete them manually after. Because i could delete the group rule and still take care of those alerts.

Wdyt?

**Comment by talboren** [comment]
> I think maybe the alerts should stay and delete them manually after. Because i could delete the group rule and still take care of those alerts.
> 
> Wdyt?

So I am not 100% sure what's the bug here. You delete the rules from the "Alert Groups" tab but after a refresh they come back in as if you didn't delete them?

**Comment by Sup3rJ** [comment]
Yes. The small refresh button don't cause this but if i refresh the all page with F5 the group alert will appear again in feed. 

https://github.com/keephq/keep/assets/45700493/6604e44f-d151-4955-99bd-d02919d05924

**Comment by talboren** [comment]
Gotcha, thanks!
