### ISSUE TITLE
Name column does not scale when columns are removed

### ISSUE THREAD

**Issue by momoadc** [keephq/keep#690]
**Describe the bug**
columns do not scale up properly when other columns are removed.
A lot of whitespace is left
**To Reproduce**
remove all columns except name (for example)

**Expected behavior**
columns scale to fill the whole widget

**Comment by talboren** [comment]
Adding a note here: this is specifically for the `name` column since we restrict the max width (`<div className="max-w-[340px]">`).

**Comment by asharonbaltazar** [comment]
Please assign me

**Comment by talboren** [comment]
> Please assign me

With pleasure!
