### ISSUE TITLE
Add "rules from plain english" capability to Keep

### ISSUE THREAD

**Issue by shahargl** [keephq/keep#697]
**Description**
Today Keep has the "Alert Groups" concept - rules that consolidate and aggregate alerts into consolidated alerts.

**Current Behavior**
The user can build the rule using react query builder:
<img width="1368" alt="CleanShot 2024-01-08 at 16 27 56@2x" src="https://github.com/keephq/keep/assets/12069200/7035ea02-5a5b-4c46-ab37-5a043dcbdecd">

**Expected Behavior**
The user will also be able to build rules using plain English. 
_This issue is only for the frontend, the backend will be handled in another issue._
The UI should allow things such as:
"When alert with name X with another alert with name Y"
"When alert with attribute X with value Y"
".."

And translate them to the backend format.

**Comment by talboren** [comment]
Closing this in the meanwhile, until we have clear definition for it.
