### ISSUE TITLE
Ability to set labels or custom fields like Component/s when creating Jira ticket

### ISSUE THREAD

**Issue by sandersietses** [keephq/keep#699]
**Describe the solution you'd like**
When I create a Jira ticket I would like to be able to set labels or custom fields so that I am able to use those fields for filtering in Jira.

I would like to set the label, component and fill in a custom field.

See:
https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-issues/#api-rest-api-3-issue-post
https://support.atlassian.com/jira-cloud-administration/docs/configure-issue-custom-fields/

**Comment by Min2who** [comment]
can i get assigned?

**Comment by Min2who** [comment]
@talboren can you reapprove the bounty 😅
