### ISSUE TITLE
Signup Page / Signup button in the Login page

### ISSUE THREAD

**Issue by DanksG** [keephq/keep#705]
Just tried to enter the web and see how does it look like, in order to contribute code next, and didn't have any access to signup..

I believe maybe when using the Github/Google account there's no need for such thing, but I'm usually signing up with my email.
Even if Signup meant to be using a Github/Google account it is unclear where you signup.

A solution would probably be a small conversion for the login page to be used as signup page, and to make sure all "Try it for free" links redirect to that page.

Actually it seems like the "Try it for free" link redirects to a signin page (appears in the address bar), but immediately after that I'm redirected to the login page.

**Comment by shahargl** [comment]
Yea we let Auth0 handle it for us. I’ll try to add user/password signup flow. Meanwhile feel free to join our Slack and we can help you set up local environment with user/password authentication.

**Comment by talboren** [comment]
![CleanShot 2024-01-11 at 12 56 03](https://github.com/keephq/keep/assets/68807791/607e1053-8203-4305-9fc1-52fb198a09f3)

Thank you for the issue!
