### ISSUE TITLE
API Key improvements

### ISSUE THREAD

**Issue by shahargl** [keephq/keep#708]
Improve API Key UX with:
UI 
Settings -> API Key
1. Improve UX with CRUD
2. Add name and details ("api key for team X")

Alerts
3. Add the ability to filter by api key in the UI (or make sure it works)

Backend
4. When pushing alerts via api key, save the relation so it can be later filtered

**Comment by Min2who** [comment]
@shahargl can i get assigned

**Comment by shahargl** [comment]
Yep

**Comment by mrkirthi-24** [comment]
/attempt #708 I am in waitlist if @Min2who gives up

**Comment by sy425191** [comment]
I would really like to /attempt #708

**Comment by PlanetKumbhaj** [comment]
curious to fix the issue /attempt #708

**Comment by shahargl** [comment]
@Min2who any progress? There are some other folks who wanna try

**Comment by Min2who** [comment]
can i get some time its been 1day only 

cc @shahargl @talboren

**Comment by TakshPanchal** [comment]
> 1. Improve UX with CRUD

Hey @shahargl, I didn't get it what it means. Can you please provide a description of the points?

**Comment by shahargl** [comment]
@Min2who yea for sure
