### ISSUE TITLE
Alert console leaks memory when the user is idle

### ISSUE THREAD

**Issue by shahargl** [keephq/keep#711]
**Describe the bug**
On the alert console, when new alerts arrive (websocket), memory consumptions goes up until the tab crashes.

**To Reproduce**
1. Go to alerts tab
2. Send A LOT (100/s) alerts
3. Do not refresh the page / do any action
4. The tab would crash

**Expected behavior**
Tab should not leak memory/crash

**Additional context**
When opening the History modal, the memory cleans itself, so I guess its something with websocket/idle.

**Comment by TakshPanchal** [comment]
May I start inspecting this issue?
