### ISSUE TITLE
Alerts table re-renders whenever a new alert is pushed

### ISSUE THREAD

**Issue by talboren** [keephq/keep#719]
**Describe the bug**
Whenever Keep gets a new alert (via push/pull), the whole alerts table re-renders.
If the menu is open -> it will close
If the history modal is open -> it will close
If the extra payload is open -> it will close

It makes it quite hard to work with a specific alert when you're viewing the alerts table.

**To Reproduce**
1. Go to Alerts page
2. Open "Extra Payload" or "History" for example
3. Open a new tab
4. Go to Keep
5. Push an alert via webhook (CMD/CTRL+K -> webhook -> "Click to create example alert")
![CleanShot 2024-01-16 at 18 22 23](https://github.com/keephq/keep/assets/68807791/3e5b5f6d-397d-4e12-9a40-709c7ab05020)
6. See extra payload getting minimized in the first tab

**Expected behavior**
Alert table shouldn't be re-rendered but only the updated (or newly inserted alert) should be updated. (fingerprint is our unique identifier for a row)

**Screenshots**

https://github.com/keephq/keep/assets/68807791/20ed4a6a-7824-4119-b4ca-42f1b1e3cdd0

**Comment by asharonbaltazar** [comment]
👀
