### ISSUE TITLE
Message column does not show on the alerts table

### ISSUE THREAD

**Issue by shahargl** [keephq/keep#723]

**Comment by ezhil56x** [comment]
Can I get assigned?
/attempt #723

**Comment by shahargl** [comment]
assigned

**Comment by TakshPanchal** [comment]
@shahargl can you please provide a bit of information regarding this bug?

**Comment by ezhil56x** [comment]
@shahargl Can you give more context or screenshot explaining this issue?

**Comment by talboren** [comment]
@shahargl @ezhil56x i've resolved the issue, please see the merged PR for more details.
