### ISSUE TITLE
Provider Request: SIGNL4

### ISSUE THREAD

**Issue by rons4** [keephq/keep#734]
**Describe the provider you want to add**
[SIGNL4](https://www.signl4.com/) is a mobile alerting and incident response service for operational teams. It notifies responsible users and teams about critical situations quickly and reliable via app push, SMS text, and voice call including escalation, on-call duty scheduling, collaboration and more.

**Describe your use case**
Our customers connect to various system (https://www.signl4.com/webhook-rest-smtp-api-integration/#integration) from IT, SecOps, but also IoT and production. They sometimes need a consolitation layer for alert.

**Are you already using Keep?**
No

**Additional context**
We provide SIGNL4 and will be happy to provide the Python code for the provider.

**Comment by shahargl** [comment]
Hey @rons4, sounds awesome! Feel free to join our Slack if you need any technical assistant, I’ll be more than happy to help with that!

**Comment by rons4** [comment]
Thanks @shahargl for all your assistance. I have just created the Pull Request for adding the SIGNL4 provider.
