### ISSUE TITLE
Alerts commenting

### ISSUE THREAD

**Issue by shahargl** [keephq/keep#736]
*** TBD ***

**Comment by asif-reh** [comment]
Hi @talboren would you please provide a description, I would like to try and contribute to UI.

**Comment by talboren** [comment]
@asif-reh this is not yet fully described. I'll let you know once we're ready to work on this one.
We have other things in the sleeve if you want, maybe we can discuss it further over Slack.
https://github.com/keephq/keep/issues/640 this could be something interesting to work on.

**Comment by asif-reh** [comment]
Thank you @talboren will try to solve this #640.
