### ISSUE TITLE
Feature Request - Alert group - Change status to resolve if all the alerts are resolved in that group 

### ISSUE THREAD

**Issue by BhuviTheDataGuy** [keephq/keep#780]
Current status:
The alert group won't be in resolve status even if all the alerts in that group are resolved. 

![image](https://github.com/keephq/keep/assets/47310439/271342cd-996d-46fe-b3c5-282593bcfa4c)

We want to make a workflow to trigger the pager, but this limitation will keep the pager open until we manually make it resolve(in the pager duty)

If all the alerts belonging to that group have been resolved, the alert group also should show its resolved.

**Comment by shahargl** [comment]
closed by https://github.com/keephq/keep/pull/783
