### ISSUE TITLE
New Provider - AWS Incident Manager

### ISSUE THREAD

**Issue by BhuviTheDataGuy** [keephq/keep#804]
AWS incident manager is a native AWS Service that is very similar to pager duty. Every incident will have its own ARN(amazon resource name).

When an alert triggers, we can create an incident in the alert manager. While sending the resolved we need to run the API call to the incident manager and pass the ARN of that incident. So somewhere the Keep should maintain the track of ARN id so it can send the resolved status to the incident manager.

**Comment by MayorChristopher** [comment]
/#804 I will like to me assigned

**Comment by shahargl** [comment]
@guhitb any progress? Or I’ll assign @MayorChristopher?

**Comment by shahargl** [comment]
@MayorChristopher assigned

**Comment by MayorChristopher** [comment]
@shahargl thanks, and I'm grateful

**Comment by mohanish2504** [comment]
Adding myself in queue!

**Comment by shahargl** [comment]
@MayorChristopher any progress?

**Comment by MayorChristopher** [comment]
> @MayorChristopher any progress?

Yes ik on it, I will soon show it

**Comment by MayorChristopher** [comment]
Good day, yes there is

**Comment by shahargl** [comment]
@MayorChristopher - can I assign @mohanish2504?

**Comment by MayorChristopher** [comment]
Good day, No, I have been doing some research on how to go about the
implementation hence the delay, I've made reasonable progress so far, and
will make a draft pull request in few hours time.

Thanks.

**Comment by mohanish2504** [comment]
@shahargl can I take this up?

**Comment by shahargl** [comment]
@MayorChristopher any update?

**Comment by 35C4n0r** [comment]
@shahargl Adding myself to the queue!

**Comment by MayorChristopher** [comment]
> @MayorChristopher any update?

Yes, I have made a draft, once I am done, I will push it

**Comment by mohanish2504** [comment]
@shahargl shall I go ahead with this?

**Comment by shahargl** [comment]
Yea you can try if you want. No progress from @MayorChristopher and its been more than a month

**Comment by mohanish2504** [comment]
@shahargl @talboren 
I was able to query the incident records here.

Incident as it seems created by the person. 
  Issue I am facing is to setup webhook. 

In response plan we have chat option, but I can only add sns topic if chat channel is activated.

Here I am getting 2 options:
- Ask user for the channel arn too?
- If not, than only query option will be enabled?

@BhuviTheDataGuy your insights will also be valuable.

![Screenshot from 2024-03-13 01-37-50](https://github.com/keephq/keep/assets/47126953/056f9848-379d-4202-88b9-f12d53ca4024)

**Comment by BhuviTheDataGuy** [comment]
Amazing, thanks a lot for your efforts @shahargl  and special thanks to @mohanish2504 for your interest on this and get this implemented.

**Comment by shahargl** [comment]
Let me know when you give it a try @BhuviTheDataGuy
