### ISSUE TITLE
New Provider: Squadcast

### ISSUE THREAD

**Issue by mfroembgen** [keephq/keep#867]
**Describe the provider you want to add**
Squadcast is a incident management tool similar to Grafana OnCall or PagerDuty.  

**Describe your use case**
We route all our alerts through Squadcast for escalation, schedules and notification routing. With the discovery of keep we would like to have keep in the middle for using keeps workflows and mappings.

**Are you already using Keep?**
Yes, we plan to implement it.

**Comment by mfroembgen** [comment]
Hey @shahargl, thank you for getting back that quickly :) What we need function wise it could be actually quite simple. Even if squadcast offers more possibilities it would be enough for us if keep would just send the payload to an endpoint.

Maybe it would be enough to have a general webhook provider where you could just define the endpoint for sending the payload. (https://support.squadcast.com/integrations/incident-webhook-incident-webhook-api)

But of cause there is as well the option to use the incident api directly(https://apidocs.squadcast.com/#9621f1a7-7263-44f1-b5e0-816b971f78ee) and maybe become a official alert source integration.

Please let me know if you need some more information or details :)

**Comment by shahargl** [comment]
@mfroembgen no problem! my first priority is to help our users :)

First, we already have that :) You can use our generic HTTP provider where you can trigger any HTTP request you want, based on alerts - https://docs.keephq.dev/providers/documentation/http-provider - if you have any questions about it feel free to join our Slack at https://slack.keephq.dev and I'll answer pretty fast :)

But of course, we want to make our user's life better than that, so I'll start working on it. I'll start with creating incident and we will go from there.

**Comment by mfroembgen** [comment]
@shahargl Thank you so much! I seem to have missed that somehow.

**Comment by 35C4n0r** [comment]
I would like to attempt it.

**Comment by shahargl** [comment]
@35C4n0r assigned

**Comment by weirdo-github** [comment]
I'd like to work on this. I've submitted a PR here: https://github.com/keephq/keep/pull/6561

Let me know if there's anything you'd like me to adjust.

**Comment by weirdo-github** [comment]
I'd like to work on this. I've submitted a PR here: https://github.com/keephq/keep/pull/6562

Let me know if there's anything you'd like me to adjust.
