### ISSUE TITLE
New Provider: GitLab on-prem

### ISSUE THREAD

**Issue by mfroembgen** [keephq/keep#868]
**Describe the provider you want to add**
Gitlab could be used for ticketing like Jira.

**Describe your use case**
We use Gitlab for for all of our planning and tickets as all of our repos are there.

**Are you already using Keep?**
Yes, we plan to implement it.

**Comment by shahargl** [comment]
Please focus on:
1. Authentication Methods
2. Validating Scopes
3. Opening a ticket
4. Documentation on how to connect GitLab provider

Please take Jira Provider as an example.

**Comment by 35C4n0r** [comment]
I would like to attempt it/

**Comment by shahargl** [comment]
@35C4n0r assigned. Please read my previous comment on what to focus on.
