### ISSUE TITLE
Request for an official hosted helm chart repository

### ISSUE THREAD

**Issue by jackrh** [keephq/keep#869]
**Is your feature request related to a problem? Please describe.**
When wanting to run the helm chart I have to fork it locally, which is not an option from our helm pipeline. 

**Describe the solution you'd like**
An official repository location that I can run the helm chart from, for use in our pipelines or with "helm repo add". Lots of projects just use Github pages for this. 

**Describe alternatives you've considered**
I can host the helm chart locally easily enough, our container registry supports that or I could just use any simple http server, but that's another thing to worry about and update.

**Comment by pehlicd** [comment]
I can work on that

**Comment by shahargl** [comment]
assigned + created https://github.com/keephq/helm-charts
