### ISSUE TITLE
vmalert (victoria metrics integration)

### ISSUE THREAD

**Issue by ManuGeodis** [keephq/keep#893]
Can you please integrate vmalert (victoria metrics) as I'm using victoria metrics as monitoring tool?
**Describe your use case**
Monitoring tool is victoria metrics. So alerts should be picked up from vmalert

**Are you already using Keep?**
Started using keep

**Additional context**
Add any other context or screenshots about the provider request here.

**Comment by ManuGeodis** [comment]
vm alert is self hosted
We need to pull alerts from vmalert.
In a day commonly we have 20-30 alerts

**Comment by ManuGeodis** [comment]
https://docs.victoriametrics.com/vmalert/

**Comment by 35C4n0r** [comment]
/attempt #893
Kindly assign it to me.

**Comment by 35C4n0r** [comment]
@onyedikachi-david I'm already attempting this issue.

**Comment by onyedikachi-david** [comment]
Alright

**Comment by shahargl** [comment]
@35C4n0r assigned
