### ISSUE TITLE
feat: implement mapping priority

### ISSUE THREAD

**Issue by pehlicd** [keephq/keep#905]
Hey,

For our use case we need priority in mappings. For example:

| priority | mapping | description |
| :------: | --------------- | ----------------------------------------- |
| 0 | general_rules.csv | enrich alerts using specific labels and add environment labels |
| 1 | env_specific_rules.csv | enrich alerts using environment labels and add more identifiers |
| 2 | alert_specific_rules.csv | do the rest of rulings |

I also saw that when a new mapping is created api responses with priority. A simple csv example would be like:

### Priority 0
matchers are = source, cluster
| source | cluster | environment |
| ------------ | -------------- | ------------- | 
| prometheus | dev-k8s-1 | sandbox |
| prometheus | prod-k8s-1 | prod |
| sentry | dev-sentry | sandbox |
| sentry | prod-sentry | prod |

### Priority 1
matchers are = environment, service
| environment | service | owner |
| ------------ | -------------- | ------------- | 
| sandbox | dev-frontend | frontend-team |
| sandbox | cart-service | backend-team |
| sandbox | kube-prometheus | (empty because we dont care alerts coming from this service) |
| prod | * (match every service) | all |
| prod | service-1 (for this service override the owner=all) | devops |

**Comment by talboren** [comment]
Closed by mistake

**Comment by talboren** [comment]
@pehlicd any chance you can check https://github.com/keephq/keep/pull/908 to see if it answers your requirements? :)

**Comment by pehlicd** [comment]
As starter it seems perfect 🚀
