### ISSUE TITLE
Splunk Enterprise Provider

### ISSUE THREAD

**Issue by talboren** [keephq/keep#917]
**Describe the provider you want to add**
Splunk Enterprise

**Describe your use case**
Connect Splunk Enterprise account and receive alerts from it.
We should support scopes and auto webhook installation (see other providers for examples, e.g., Datadog, Grafana, SignalFx, etc.)

**Are you already using Keep?**
**Yes**/No

**Additional context**
https://www.splunk.com/en_us/download/splunk-enterprise.html

**Comment by talboren** [comment]
> /attempt #917
> 
> [Algora profile](https://console.algora.io/@/35C4n0r)	Completed bounties	Tech	Active attempts	Options
> @35C4n0r	   2 keephq bounties
> + 2 bounties from 1 project	
> Python, JavaScript,
> HTML & more
> [Cancel attempt](https://console.algora.io/api/bounties/clthv1jdk0002l20fmrruf67n/cancel-attempt)

My bad! I'll award it with a tip of another 15$ :)

**Comment by Bhavyajain21** [comment]
Can I be assigned?
