### ISSUE TITLE
Run workflow from Workflow Builder

### ISSUE THREAD

**Issue by talboren** [keephq/keep#932]
- Run workflow from within the Workflow Builder (before deploying)
- Get feedback on specific steps / general flow (e.g., see how far the workflow went through and output of specific steps)
- Debug failures

**Comment by Matvey-Kuk** [comment]
This bounty is a part of our effort to welcome new contributors to the repo.

@35C4n0r I hope you don't mind if we wait a few days to see if new contributors will be willing to participate? 🙏

**Comment by shashank40** [comment]
/attempt #932
Hi @Matvey-Kuk can i pick this up?

**Comment by asr2003** [comment]
@Matvey-Kuk I will be great to contribute to this project. I have a similar experience of working with workflows. Givivng it a try:

/attempt #932

**Comment by onurio** [comment]
@Matvey-Kuk  I'd love to attempt this one. Will start working on it today.

/attempt #932

**Comment by Matvey-Kuk** [comment]
@onurio assigned to you!

**Comment by Matvey-Kuk** [comment]
Yep, exactly!

Best regards,
Matvey Kukuy

**Comment by Matvey-Kuk** [comment]
@onurio I think it's mostly related to the Workflow web editor.

**Comment by onurio** [comment]
@Matvey-Kuk I understand, I think it's a prerequisite for it, since otherwise you will have to deploy every time you want to run the updated version of the workflow. But I don't want to assume too much.
