### ISSUE TITLE
SSH provider - improper parsing of `private key` field

### ISSUE THREAD

**Issue by equals215** [keephq/keep#939]
**Describe the bug**
When configuring a SSH provider, the `private key` field accepts a string and parses it in a way that makes it unusable by the backend.  
- If you provide the private key unescaped, the UI/backend will escape newlines to single spaces  
- If you provide an escaped private key, the UI/backend will escape the `\n` to `\\n`  

In both cases the backend will be unable to process the private key and will give a `not a valid RSA private key file` error. 

**To Reproduce**
1. Create a new SSH provider and give it either escaped or unescaped private key
2. Create a manual workflow that runs a command on the given SSH provider
3. Execute the workflow
4. See the error

**Expected behavior**
The given escaped private key is not escaped again and the key is stored like this in the provider JSON file : 
```json
{"pkey": "-----BEGIN OPENSSH PRIVATE KEY-----\nb3BlbnNzaC1rZXktdjEAAAAABG5vbmUAA...xvY2FsAQID\n-----END OPENSSH PRIVATE KEY-----\n"}
```
 
OR  
The frontend accept a private key file and store it's content unescaped in the in the provider JSON file

**Version**
Backend : us-central1-docker.pkg.dev/keephq/keep/keep-api@sha256:398e51d322ad512f18227fa2c5a703b8d054f65b81badd50a0f75136050bb974
Frontend : us-central1-docker.pkg.dev/keephq/keep/keep-ui@sha256:da47514cd26f85e10d32021f705eb9f2cf7382775325198a7d6d15dcc424ba69

**Misc**
Issue from [Slack thread](https://getkeep.slack.com/archives/C04PT44MATS/p1710049725885959)
Issue linked to [Shahar previous issue](https://github.com/keephq/keep/issues/931)

**Comment by talboren** [comment]
![CleanShot 2024-03-11 at 16 52 25](https://github.com/keephq/keep/assets/68807791/041f39a2-e1d0-4664-9f36-c37c878f0ef4)
