### ISSUE TITLE
Install providers separately 

### ISSUE THREAD

**Issue by shahargl** [keephq/keep#98]
Be able to install only parts of keep if I don't need all of the providers.
e.g.
```
keep install provider ssh
keep install provider gcloud
```
The goal is to decrease the overall size and dependencies needed to start working

**Comment by talboren** [comment]
https://stackoverflow.com/questions/60971502/python-poetry-how-to-install-optional-dependencies this might be interesting as well

**Comment by devblin** [comment]
@shahargl so, when we install a provider, for example: `keep install provider gcloud`, all the dependencies related to gcloud provider will be installed?

**Comment by talboren** [comment]
@devblin I'm not sure this is still relevant, let's wait for @shahargl to approve

**Comment by talboren** [comment]
Let's reopen this when it's more relevant.
