### ISSUE TITLE
Add support for AWS Secrets Manager as SECRET_MANAGER_TYPE

### ISSUE THREAD

**Issue by AmgadH89** [keephq/keep#992]
After deploying Keep to AWS ECS, I noticed that the external file system is only used to store the webhook and providers files, so after testing it out with EFS file system, I was thinking about using AWS Secrets Manager instead as there is no actual use for the EFS filesystem, so from a cost optimization point of view Secrets Manager would be more beneficial.

**Comment by shahargl** [comment]
close by https://github.com/keephq/keep/pull/2222
